// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: chat.sql

package dao

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimPendingChatEventOutbox = `-- name: ClaimPendingChatEventOutbox :many
WITH picked AS (
  SELECT e.id
  FROM "chat_event_outbox" e
  WHERE (
    e.status = 'pending'
    AND e.next_retry_at <= $2
  ) OR (
    e.status = 'publishing'
    AND e.utime <= $3
  )
  ORDER BY e.id ASC
  LIMIT $4
  FOR UPDATE SKIP LOCKED
)
UPDATE "chat_event_outbox" o
SET status = 'publishing',
    utime = $1
FROM picked
WHERE o.id = picked.id
RETURNING
  o.id,
  o.event_id,
  o.routing_key,
  o.payload,
  o.attempts,
  o.ctime
`

type ClaimPendingChatEventOutboxParams struct {
	ClaimedAt   int64
	RetryBefore int64
	StaleBefore int64
	ClaimLimit  int32
}

type ClaimPendingChatEventOutboxRow struct {
	ID         int64
	EventID    string
	RoutingKey string
	Payload    string
	Attempts   int32
	Ctime      int64
}

func (q *Queries) ClaimPendingChatEventOutbox(ctx context.Context, arg ClaimPendingChatEventOutboxParams) ([]ClaimPendingChatEventOutboxRow, error) {
	rows, err := q.db.Query(ctx, claimPendingChatEventOutbox,
		arg.ClaimedAt,
		arg.RetryBefore,
		arg.StaleBefore,
		arg.ClaimLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ClaimPendingChatEventOutboxRow
	for rows.Next() {
		var i ClaimPendingChatEventOutboxRow
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.RoutingKey,
			&i.Payload,
			&i.Attempts,
			&i.Ctime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createChatDirectMessage = `-- name: CreateChatDirectMessage :execrows
INSERT INTO "chat_direct_message" (
  message_id, from_user_id, to_user_id, type, content, ctime, utime
) VALUES (
  $1, $2, $3, $4, $5, $6, $6
)
ON CONFLICT (from_user_id, to_user_id, message_id) DO NOTHING
`

type CreateChatDirectMessageParams struct {
	MessageID  pgtype.UUID
	FromUserID pgtype.UUID
	ToUserID   pgtype.UUID
	Type       string
	Content    string
	Ctime      int64
}

func (q *Queries) CreateChatDirectMessage(ctx context.Context, arg CreateChatDirectMessageParams) (int64, error) {
	result, err := q.db.Exec(ctx, createChatDirectMessage,
		arg.MessageID,
		arg.FromUserID,
		arg.ToUserID,
		arg.Type,
		arg.Content,
		arg.Ctime,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createChatEventOutbox = `-- name: CreateChatEventOutbox :execrows
INSERT INTO "chat_event_outbox" (
  event_id, routing_key, payload, status,
  attempts, next_retry_at, published_at, ctime, utime
) VALUES (
  $1, $2, $3, 'pending',
  0, 0, 0, $4, $4
)
ON CONFLICT (event_id) DO NOTHING
`

type CreateChatEventOutboxParams struct {
	EventID    string
	RoutingKey string
	Payload    string
	Ctime      int64
}

func (q *Queries) CreateChatEventOutbox(ctx context.Context, arg CreateChatEventOutboxParams) (int64, error) {
	result, err := q.db.Exec(ctx, createChatEventOutbox,
		arg.EventID,
		arg.RoutingKey,
		arg.Payload,
		arg.Ctime,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createChatGroup = `-- name: CreateChatGroup :exec
WITH g AS (
  INSERT INTO "chat_group" (
    group_id, owner_id, name, avatar, description,
    member_limit, member_count, ctime, utime
  ) VALUES (
    $1, $2, $3, $4, $5,
    $6, 1, $7, $7
  )
  RETURNING group_id, owner_id, ctime, utime
)
INSERT INTO "chat_group_member" (
  group_id, user_id, role, ctime, utime
) SELECT
  group_id, owner_id, 'owner', ctime, utime
FROM g
`

type CreateChatGroupParams struct {
	GroupID     pgtype.UUID
	OwnerID     pgtype.UUID
	Name        string
	Avatar      string
	Description string
	MemberLimit int32
	Ctime       int64
}

func (q *Queries) CreateChatGroup(ctx context.Context, arg CreateChatGroupParams) error {
	_, err := q.db.Exec(ctx, createChatGroup,
		arg.GroupID,
		arg.OwnerID,
		arg.Name,
		arg.Avatar,
		arg.Description,
		arg.MemberLimit,
		arg.Ctime,
	)
	return err
}

const createChatGroupMember = `-- name: CreateChatGroupMember :exec
INSERT INTO "chat_group_member" (
  group_id, user_id, role, ctime, utime
) VALUES (
  $1, $2, $3, $4, $4
)
ON CONFLICT (group_id, user_id) DO NOTHING
`

type CreateChatGroupMemberParams struct {
	GroupID pgtype.UUID
	UserID  pgtype.UUID
	Role    string
	Ctime   int64
}

func (q *Queries) CreateChatGroupMember(ctx context.Context, arg CreateChatGroupMemberParams) error {
	_, err := q.db.Exec(ctx, createChatGroupMember,
		arg.GroupID,
		arg.UserID,
		arg.Role,
		arg.Ctime,
	)
	return err
}

const createChatGroupMessage = `-- name: CreateChatGroupMessage :execrows
INSERT INTO "chat_group_message" (
  message_id, group_id, from_user_id, type, content, ctime, utime
) VALUES (
  $1, $2, $3, $4, $5, $6, $6
)
ON CONFLICT (group_id, message_id) DO NOTHING
`

type CreateChatGroupMessageParams struct {
	MessageID  pgtype.UUID
	GroupID    pgtype.UUID
	FromUserID pgtype.UUID
	Type       string
	Content    string
	Ctime      int64
}

func (q *Queries) CreateChatGroupMessage(ctx context.Context, arg CreateChatGroupMessageParams) (int64, error) {
	result, err := q.db.Exec(ctx, createChatGroupMessage,
		arg.MessageID,
		arg.GroupID,
		arg.FromUserID,
		arg.Type,
		arg.Content,
		arg.Ctime,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const decChatGroupMemberCount = `-- name: DecChatGroupMemberCount :execrows
UPDATE "chat_group"
SET member_count = member_count - 1,
    utime = $2
WHERE group_id = $1
`

type DecChatGroupMemberCountParams struct {
	GroupID pgtype.UUID
	Utime   int64
}

func (q *Queries) DecChatGroupMemberCount(ctx context.Context, arg DecChatGroupMemberCountParams) (int64, error) {
	result, err := q.db.Exec(ctx, decChatGroupMemberCount, arg.GroupID, arg.Utime)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteChatGroupByID = `-- name: DeleteChatGroupByID :execrows
DELETE FROM "chat_group"
WHERE group_id = $1
`

func (q *Queries) DeleteChatGroupByID(ctx context.Context, groupID pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteChatGroupByID, groupID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteChatGroupMember = `-- name: DeleteChatGroupMember :execrows
DELETE FROM "chat_group_member"
WHERE group_id = $1 AND user_id = $2
`

type DeleteChatGroupMemberParams struct {
	GroupID pgtype.UUID
	UserID  pgtype.UUID
}

func (q *Queries) DeleteChatGroupMember(ctx context.Context, arg DeleteChatGroupMemberParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteChatGroupMember, arg.GroupID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteChatGroupMembersByGroupID = `-- name: DeleteChatGroupMembersByGroupID :execrows
DELETE FROM "chat_group_member"
WHERE group_id = $1
`

func (q *Queries) DeleteChatGroupMembersByGroupID(ctx context.Context, groupID pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteChatGroupMembersByGroupID, groupID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteChatGroupMessagesByGroupID = `-- name: DeleteChatGroupMessagesByGroupID :execrows
DELETE FROM "chat_group_message"
WHERE group_id = $1
`

func (q *Queries) DeleteChatGroupMessagesByGroupID(ctx context.Context, groupID pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteChatGroupMessagesByGroupID, groupID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getChatGroupByID = `-- name: GetChatGroupByID :one
SELECT id, group_id, owner_id, name, avatar, description, member_limit, member_count, ctime, utime FROM "chat_group"
WHERE group_id = $1
LIMIT 1
`

func (q *Queries) GetChatGroupByID(ctx context.Context, groupID pgtype.UUID) (ChatGroup, error) {
	row := q.db.QueryRow(ctx, getChatGroupByID, groupID)
	var i ChatGroup
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.OwnerID,
		&i.Name,
		&i.Avatar,
		&i.Description,
		&i.MemberLimit,
		&i.MemberCount,
		&i.Ctime,
		&i.Utime,
	)
	return i, err
}

const getChatGroupMemberRole = `-- name: GetChatGroupMemberRole :one
SELECT role
FROM "chat_group_member"
WHERE group_id = $1 AND user_id = $2
LIMIT 1
`

type GetChatGroupMemberRoleParams struct {
	GroupID pgtype.UUID
	UserID  pgtype.UUID
}

func (q *Queries) GetChatGroupMemberRole(ctx context.Context, arg GetChatGroupMemberRoleParams) (string, error) {
	row := q.db.QueryRow(ctx, getChatGroupMemberRole, arg.GroupID, arg.UserID)
	var role string
	err := row.Scan(&role)
	return role, err
}

const getChatGroupProfile = `-- name: GetChatGroupProfile :one
SELECT
  g.group_id::text AS group_id,
  g.owner_id::text AS owner_user_id,
  COALESCE(ua.username, '') AS owner_username,
  COALESCE(ua.avatar, '') AS owner_avatar,
  g.name,
  g.avatar,
  g.description,
  g.member_limit,
  g.member_count,
  g.ctime,
  g.utime
FROM "chat_group" g
LEFT JOIN "user_addition" ua ON ua.user_id = g.owner_id
WHERE g.group_id = $1
LIMIT 1
`

type GetChatGroupProfileRow struct {
	GroupID       string
	OwnerUserID   string
	OwnerUsername string
	OwnerAvatar   string
	Name          string
	Avatar        string
	Description   string
	MemberLimit   int32
	MemberCount   int32
	Ctime         int64
	Utime         int64
}

func (q *Queries) GetChatGroupProfile(ctx context.Context, groupID pgtype.UUID) (GetChatGroupProfileRow, error) {
	row := q.db.QueryRow(ctx, getChatGroupProfile, groupID)
	var i GetChatGroupProfileRow
	err := row.Scan(
		&i.GroupID,
		&i.OwnerUserID,
		&i.OwnerUsername,
		&i.OwnerAvatar,
		&i.Name,
		&i.Avatar,
		&i.Description,
		&i.MemberLimit,
		&i.MemberCount,
		&i.Ctime,
		&i.Utime,
	)
	return i, err
}

const incChatGroupMemberCount = `-- name: IncChatGroupMemberCount :execrows
UPDATE "chat_group"
SET member_count = member_count + 1,
    utime = $2
WHERE group_id = $1
`

type IncChatGroupMemberCountParams struct {
	GroupID pgtype.UUID
	Utime   int64
}

func (q *Queries) IncChatGroupMemberCount(ctx context.Context, arg IncChatGroupMemberCountParams) (int64, error) {
	result, err := q.db.Exec(ctx, incChatGroupMemberCount, arg.GroupID, arg.Utime)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listChatDirectMessagesAfter = `-- name: ListChatDirectMessagesAfter :many
SELECT
  message_id::text AS message_id,
  from_user_id::text AS from_user_id,
  to_user_id::text AS to_user_id,
  type,
  content,
  ctime
FROM "chat_direct_message"
WHERE (
  (
    from_user_id = $1 AND to_user_id = $2
  ) OR (
    from_user_id = $2 AND to_user_id = $1
  )
)
  AND (
    ctime > $3 OR
    (ctime = $3 AND message_id > $4)
  )
ORDER BY ctime ASC, message_id ASC
LIMIT $5
`

type ListChatDirectMessagesAfterParams struct {
	FromUserID pgtype.UUID
	ToUserID   pgtype.UUID
	Ctime      int64
	MessageID  pgtype.UUID
	Limit      int32
}

type ListChatDirectMessagesAfterRow struct {
	MessageID  string
	FromUserID string
	ToUserID   string
	Type       string
	Content    string
	Ctime      int64
}

func (q *Queries) ListChatDirectMessagesAfter(ctx context.Context, arg ListChatDirectMessagesAfterParams) ([]ListChatDirectMessagesAfterRow, error) {
	rows, err := q.db.Query(ctx, listChatDirectMessagesAfter,
		arg.FromUserID,
		arg.ToUserID,
		arg.Ctime,
		arg.MessageID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListChatDirectMessagesAfterRow
	for rows.Next() {
		var i ListChatDirectMessagesAfterRow
		if err := rows.Scan(
			&i.MessageID,
			&i.FromUserID,
			&i.ToUserID,
			&i.Type,
			&i.Content,
			&i.Ctime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChatDirectMessagesBefore = `-- name: ListChatDirectMessagesBefore :many
SELECT
  message_id::text AS message_id,
  from_user_id::text AS from_user_id,
  to_user_id::text AS to_user_id,
  type,
  content,
  ctime
FROM "chat_direct_message"
WHERE (
  (
    from_user_id = $1 AND to_user_id = $2
  ) OR (
    from_user_id = $2 AND to_user_id = $1
  )
)
  AND (
    ctime < $3 OR
    (ctime = $3 AND message_id < $4)
  )
ORDER BY ctime DESC, message_id DESC
LIMIT $5
`

type ListChatDirectMessagesBeforeParams struct {
	FromUserID pgtype.UUID
	ToUserID   pgtype.UUID
	Ctime      int64
	MessageID  pgtype.UUID
	Limit      int32
}

type ListChatDirectMessagesBeforeRow struct {
	MessageID  string
	FromUserID string
	ToUserID   string
	Type       string
	Content    string
	Ctime      int64
}

func (q *Queries) ListChatDirectMessagesBefore(ctx context.Context, arg ListChatDirectMessagesBeforeParams) ([]ListChatDirectMessagesBeforeRow, error) {
	rows, err := q.db.Query(ctx, listChatDirectMessagesBefore,
		arg.FromUserID,
		arg.ToUserID,
		arg.Ctime,
		arg.MessageID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListChatDirectMessagesBeforeRow
	for rows.Next() {
		var i ListChatDirectMessagesBeforeRow
		if err := rows.Scan(
			&i.MessageID,
			&i.FromUserID,
			&i.ToUserID,
			&i.Type,
			&i.Content,
			&i.Ctime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChatDirectMessagesLatest = `-- name: ListChatDirectMessagesLatest :many
SELECT
  message_id::text AS message_id,
  from_user_id::text AS from_user_id,
  to_user_id::text AS to_user_id,
  type,
  content,
  ctime
FROM "chat_direct_message"
WHERE (
  from_user_id = $1 AND to_user_id = $2
) OR (
  from_user_id = $2 AND to_user_id = $1
)
ORDER BY ctime DESC, message_id DESC
LIMIT $3
`

type ListChatDirectMessagesLatestParams struct {
	FromUserID pgtype.UUID
	ToUserID   pgtype.UUID
	Limit      int32
}

type ListChatDirectMessagesLatestRow struct {
	MessageID  string
	FromUserID string
	ToUserID   string
	Type       string
	Content    string
	Ctime      int64
}

func (q *Queries) ListChatDirectMessagesLatest(ctx context.Context, arg ListChatDirectMessagesLatestParams) ([]ListChatDirectMessagesLatestRow, error) {
	rows, err := q.db.Query(ctx, listChatDirectMessagesLatest, arg.FromUserID, arg.ToUserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListChatDirectMessagesLatestRow
	for rows.Next() {
		var i ListChatDirectMessagesLatestRow
		if err := rows.Scan(
			&i.MessageID,
			&i.FromUserID,
			&i.ToUserID,
			&i.Type,
			&i.Content,
			&i.Ctime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChatGroupMembersPreviewWithProfile = `-- name: ListChatGroupMembersPreviewWithProfile :many
SELECT
  gm.user_id::text AS user_id,
  COALESCE(ua.username, '') AS username,
  COALESCE(ua.avatar, '') AS avatar,
  gm.role,
  gm.ctime AS join_time
FROM "chat_group_member" gm
LEFT JOIN "user_addition" ua ON ua.user_id = gm.user_id
WHERE gm.group_id = $1
ORDER BY
  CASE gm.role WHEN 'owner' THEN 1 WHEN 'admin' THEN 2 ELSE 3 END,
  gm.ctime ASC
LIMIT $2
`

type ListChatGroupMembersPreviewWithProfileParams struct {
	GroupID pgtype.UUID
	Limit   int32
}

type ListChatGroupMembersPreviewWithProfileRow struct {
	UserID   string
	Username string
	Avatar   string
	Role     string
	JoinTime int64
}

func (q *Queries) ListChatGroupMembersPreviewWithProfile(ctx context.Context, arg ListChatGroupMembersPreviewWithProfileParams) ([]ListChatGroupMembersPreviewWithProfileRow, error) {
	rows, err := q.db.Query(ctx, listChatGroupMembersPreviewWithProfile, arg.GroupID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListChatGroupMembersPreviewWithProfileRow
	for rows.Next() {
		var i ListChatGroupMembersPreviewWithProfileRow
		if err := rows.Scan(
			&i.UserID,
			&i.Username,
			&i.Avatar,
			&i.Role,
			&i.JoinTime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChatGroupMembersWithProfile = `-- name: ListChatGroupMembersWithProfile :many
SELECT
  gm.user_id::text AS user_id,
  COALESCE(ua.username, '') AS username,
  COALESCE(ua.avatar, '') AS avatar,
  gm.role,
  gm.ctime AS join_time
FROM "chat_group_member" gm
LEFT JOIN "user_addition" ua ON ua.user_id = gm.user_id
WHERE gm.group_id = $1
ORDER BY
  CASE gm.role WHEN 'owner' THEN 1 WHEN 'admin' THEN 2 ELSE 3 END,
  gm.ctime ASC
LIMIT $2 OFFSET $3
`

type ListChatGroupMembersWithProfileParams struct {
	GroupID pgtype.UUID
	Limit   int32
	Offset  int32
}

type ListChatGroupMembersWithProfileRow struct {
	UserID   string
	Username string
	Avatar   string
	Role     string
	JoinTime int64
}

func (q *Queries) ListChatGroupMembersWithProfile(ctx context.Context, arg ListChatGroupMembersWithProfileParams) ([]ListChatGroupMembersWithProfileRow, error) {
	rows, err := q.db.Query(ctx, listChatGroupMembersWithProfile, arg.GroupID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListChatGroupMembersWithProfileRow
	for rows.Next() {
		var i ListChatGroupMembersWithProfileRow
		if err := rows.Scan(
			&i.UserID,
			&i.Username,
			&i.Avatar,
			&i.Role,
			&i.JoinTime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChatGroupMessagesAfter = `-- name: ListChatGroupMessagesAfter :many
SELECT
  message_id::text AS message_id,
  group_id::text AS group_id,
  from_user_id::text AS from_user_id,
  type,
  content,
  ctime
FROM "chat_group_message"
WHERE group_id = $1
  AND (
    ctime > $2 OR
    (ctime = $2 AND message_id > $3)
)
ORDER BY ctime ASC, message_id ASC
LIMIT $4
`

type ListChatGroupMessagesAfterParams struct {
	GroupID   pgtype.UUID
	Ctime     int64
	MessageID pgtype.UUID
	Limit     int32
}

type ListChatGroupMessagesAfterRow struct {
	MessageID  string
	GroupID    string
	FromUserID string
	Type       string
	Content    string
	Ctime      int64
}

func (q *Queries) ListChatGroupMessagesAfter(ctx context.Context, arg ListChatGroupMessagesAfterParams) ([]ListChatGroupMessagesAfterRow, error) {
	rows, err := q.db.Query(ctx, listChatGroupMessagesAfter,
		arg.GroupID,
		arg.Ctime,
		arg.MessageID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListChatGroupMessagesAfterRow
	for rows.Next() {
		var i ListChatGroupMessagesAfterRow
		if err := rows.Scan(
			&i.MessageID,
			&i.GroupID,
			&i.FromUserID,
			&i.Type,
			&i.Content,
			&i.Ctime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChatGroupMessagesBefore = `-- name: ListChatGroupMessagesBefore :many
SELECT
  message_id::text AS message_id,
  group_id::text AS group_id,
  from_user_id::text AS from_user_id,
  type,
  content,
  ctime
FROM "chat_group_message"
WHERE group_id = $1
  AND (
    ctime < $2 OR
    (ctime = $2 AND message_id < $3)
  )
ORDER BY ctime DESC, message_id DESC
LIMIT $4
`

type ListChatGroupMessagesBeforeParams struct {
	GroupID   pgtype.UUID
	Ctime     int64
	MessageID pgtype.UUID
	Limit     int32
}

type ListChatGroupMessagesBeforeRow struct {
	MessageID  string
	GroupID    string
	FromUserID string
	Type       string
	Content    string
	Ctime      int64
}

func (q *Queries) ListChatGroupMessagesBefore(ctx context.Context, arg ListChatGroupMessagesBeforeParams) ([]ListChatGroupMessagesBeforeRow, error) {
	rows, err := q.db.Query(ctx, listChatGroupMessagesBefore,
		arg.GroupID,
		arg.Ctime,
		arg.MessageID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListChatGroupMessagesBeforeRow
	for rows.Next() {
		var i ListChatGroupMessagesBeforeRow
		if err := rows.Scan(
			&i.MessageID,
			&i.GroupID,
			&i.FromUserID,
			&i.Type,
			&i.Content,
			&i.Ctime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChatGroupMessagesLatest = `-- name: ListChatGroupMessagesLatest :many
SELECT
  message_id::text AS message_id,
  group_id::text AS group_id,
  from_user_id::text AS from_user_id,
  type,
  content,
  ctime
FROM "chat_group_message"
WHERE group_id = $1
ORDER BY ctime DESC, message_id DESC
LIMIT $2
`

type ListChatGroupMessagesLatestParams struct {
	GroupID pgtype.UUID
	Limit   int32
}

type ListChatGroupMessagesLatestRow struct {
	MessageID  string
	GroupID    string
	FromUserID string
	Type       string
	Content    string
	Ctime      int64
}

func (q *Queries) ListChatGroupMessagesLatest(ctx context.Context, arg ListChatGroupMessagesLatestParams) ([]ListChatGroupMessagesLatestRow, error) {
	rows, err := q.db.Query(ctx, listChatGroupMessagesLatest, arg.GroupID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListChatGroupMessagesLatestRow
	for rows.Next() {
		var i ListChatGroupMessagesLatestRow
		if err := rows.Scan(
			&i.MessageID,
			&i.GroupID,
			&i.FromUserID,
			&i.Type,
			&i.Content,
			&i.Ctime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDiscoverChatGroupsAfter = `-- name: ListDiscoverChatGroupsAfter :many
SELECT
  g.group_id::text AS group_id,
  g.name,
  g.avatar,
  g.member_count,
  g.member_limit,
  md5($2::text || g.group_id::text) AS sort_key
FROM "chat_group" g
WHERE g.member_count < g.member_limit
  AND NOT EXISTS (
    SELECT 1
    FROM "chat_group_member" gm
    WHERE gm.group_id = g.group_id
      AND gm.user_id = $1
  )
  AND (
    md5($2::text || g.group_id::text) > $3::text OR
    (md5($2::text || g.group_id::text) = $3::text AND g.group_id > $4)
  )
ORDER BY sort_key ASC, g.group_id ASC
LIMIT $5
`

type ListDiscoverChatGroupsAfterParams struct {
	UserID  pgtype.UUID
	Column2 string
	Column3 string
	GroupID pgtype.UUID
	Limit   int32
}

type ListDiscoverChatGroupsAfterRow struct {
	GroupID     string
	Name        string
	Avatar      string
	MemberCount int32
	MemberLimit int32
	SortKey     string
}

func (q *Queries) ListDiscoverChatGroupsAfter(ctx context.Context, arg ListDiscoverChatGroupsAfterParams) ([]ListDiscoverChatGroupsAfterRow, error) {
	rows, err := q.db.Query(ctx, listDiscoverChatGroupsAfter,
		arg.UserID,
		arg.Column2,
		arg.Column3,
		arg.GroupID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDiscoverChatGroupsAfterRow
	for rows.Next() {
		var i ListDiscoverChatGroupsAfterRow
		if err := rows.Scan(
			&i.GroupID,
			&i.Name,
			&i.Avatar,
			&i.MemberCount,
			&i.MemberLimit,
			&i.SortKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDiscoverChatGroupsFirst = `-- name: ListDiscoverChatGroupsFirst :many
SELECT
  g.group_id::text AS group_id,
  g.name,
  g.avatar,
  g.member_count,
  g.member_limit,
  md5($2::text || g.group_id::text) AS sort_key
FROM "chat_group" g
WHERE g.member_count < g.member_limit
  AND NOT EXISTS (
    SELECT 1
    FROM "chat_group_member" gm
    WHERE gm.group_id = g.group_id
      AND gm.user_id = $1
  )
ORDER BY sort_key ASC, g.group_id ASC
LIMIT $3
`

type ListDiscoverChatGroupsFirstParams struct {
	UserID  pgtype.UUID
	Column2 string
	Limit   int32
}

type ListDiscoverChatGroupsFirstRow struct {
	GroupID     string
	Name        string
	Avatar      string
	MemberCount int32
	MemberLimit int32
	SortKey     string
}

func (q *Queries) ListDiscoverChatGroupsFirst(ctx context.Context, arg ListDiscoverChatGroupsFirstParams) ([]ListDiscoverChatGroupsFirstRow, error) {
	rows, err := q.db.Query(ctx, listDiscoverChatGroupsFirst, arg.UserID, arg.Column2, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDiscoverChatGroupsFirstRow
	for rows.Next() {
		var i ListDiscoverChatGroupsFirstRow
		if err := rows.Scan(
			&i.GroupID,
			&i.Name,
			&i.Avatar,
			&i.MemberCount,
			&i.MemberLimit,
			&i.SortKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMyChatGroups = `-- name: ListMyChatGroups :many
SELECT
  gm.group_id::text AS group_id,
  g.name,
  g.avatar,
  g.description,
  g.member_limit,
  g.member_count,
  gm.role,
  g.ctime,
  g.utime,
  COALESCE(um.unread_count, 0) AS unread_count,
  COALESCE(lm.from_user_id::text, '') AS last_message_from_user_id,
  COALESCE(ualm.username, '') AS last_message_from_username,
  COALESCE(lm.type, '') AS last_message_type,
  COALESCE(lm.content, '') AS last_message_content,
  COALESCE(lm.ctime, 0) AS last_message_time
FROM "chat_group_member" gm
JOIN "chat_group" g ON g.group_id = gm.group_id
LEFT JOIN LATERAL (
  SELECT COUNT(1) AS unread_count
  FROM "chat_group_message" m2
  WHERE m2.group_id = gm.group_id
    AND m2.ctime > gm.last_seen_time
    AND m2.from_user_id <> gm.user_id
) um ON TRUE
LEFT JOIN LATERAL (
  SELECT m.from_user_id, m.type, m.content, m.ctime
  FROM "chat_group_message" m
  WHERE m.group_id = gm.group_id
  ORDER BY m.ctime DESC, m.message_id DESC
  LIMIT 1
) lm ON TRUE
LEFT JOIN "user_addition" ualm ON ualm.user_id = lm.from_user_id
WHERE gm.user_id = $1
ORDER BY COALESCE(lm.ctime, 0) DESC, g.ctime DESC
`

type ListMyChatGroupsRow struct {
	GroupID                 string
	Name                    string
	Avatar                  string
	Description             string
	MemberLimit             int32
	MemberCount             int32
	Role                    string
	Ctime                   int64
	Utime                   int64
	UnreadCount             int64
	LastMessageFromUserID   interface{}
	LastMessageFromUsername string
	LastMessageType         string
	LastMessageContent      string
	LastMessageTime         int64
}

func (q *Queries) ListMyChatGroups(ctx context.Context, userID pgtype.UUID) ([]ListMyChatGroupsRow, error) {
	rows, err := q.db.Query(ctx, listMyChatGroups, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMyChatGroupsRow
	for rows.Next() {
		var i ListMyChatGroupsRow
		if err := rows.Scan(
			&i.GroupID,
			&i.Name,
			&i.Avatar,
			&i.Description,
			&i.MemberLimit,
			&i.MemberCount,
			&i.Role,
			&i.Ctime,
			&i.Utime,
			&i.UnreadCount,
			&i.LastMessageFromUserID,
			&i.LastMessageFromUsername,
			&i.LastMessageType,
			&i.LastMessageContent,
			&i.LastMessageTime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockChatGroupByID = `-- name: LockChatGroupByID :one
SELECT id, group_id, owner_id, name, avatar, description, member_limit, member_count, ctime, utime FROM "chat_group"
WHERE group_id = $1
LIMIT 1
FOR UPDATE
`

func (q *Queries) LockChatGroupByID(ctx context.Context, groupID pgtype.UUID) (ChatGroup, error) {
	row := q.db.QueryRow(ctx, lockChatGroupByID, groupID)
	var i ChatGroup
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.OwnerID,
		&i.Name,
		&i.Avatar,
		&i.Description,
		&i.MemberLimit,
		&i.MemberCount,
		&i.Ctime,
		&i.Utime,
	)
	return i, err
}

const markChatEventOutboxFailed = `-- name: MarkChatEventOutboxFailed :execrows
UPDATE "chat_event_outbox"
SET status = CASE WHEN attempts + 1 >= $3 THEN 'failed' ELSE 'pending' END,
    attempts = attempts + 1,
    next_retry_at = CASE WHEN attempts + 1 >= $3 THEN 0 ELSE $2 END,
    utime = $4
WHERE id = $1
  AND status = 'publishing'
`

type MarkChatEventOutboxFailedParams struct {
	ID          int64
	NextRetryAt int64
	Attempts    int32
	Utime       int64
}

func (q *Queries) MarkChatEventOutboxFailed(ctx context.Context, arg MarkChatEventOutboxFailedParams) (int64, error) {
	result, err := q.db.Exec(ctx, markChatEventOutboxFailed,
		arg.ID,
		arg.NextRetryAt,
		arg.Attempts,
		arg.Utime,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markChatEventOutboxPublished = `-- name: MarkChatEventOutboxPublished :execrows
UPDATE "chat_event_outbox"
SET status = 'published',
    published_at = $2,
    utime = $2
WHERE id = $1
  AND status = 'publishing'
`

type MarkChatEventOutboxPublishedParams struct {
	ID          int64
	PublishedAt int64
}

func (q *Queries) MarkChatEventOutboxPublished(ctx context.Context, arg MarkChatEventOutboxPublishedParams) (int64, error) {
	result, err := q.db.Exec(ctx, markChatEventOutboxPublished, arg.ID, arg.PublishedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const searchChatGroupsByName = `-- name: SearchChatGroupsByName :many
SELECT
  g.group_id::text AS group_id,
  g.name,
  g.avatar,
  g.member_count,
  g.member_limit
FROM "chat_group" g
WHERE g.name ILIKE ('%' || $1 || '%')
ORDER BY g.member_count DESC, g.ctime DESC
LIMIT $2
`

type SearchChatGroupsByNameParams struct {
	Column1 pgtype.Text
	Limit   int32
}

type SearchChatGroupsByNameRow struct {
	GroupID     string
	Name        string
	Avatar      string
	MemberCount int32
	MemberLimit int32
}

func (q *Queries) SearchChatGroupsByName(ctx context.Context, arg SearchChatGroupsByNameParams) ([]SearchChatGroupsByNameRow, error) {
	rows, err := q.db.Query(ctx, searchChatGroupsByName, arg.Column1, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchChatGroupsByNameRow
	for rows.Next() {
		var i SearchChatGroupsByNameRow
		if err := rows.Scan(
			&i.GroupID,
			&i.Name,
			&i.Avatar,
			&i.MemberCount,
			&i.MemberLimit,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const transferChatGroupOwner = `-- name: TransferChatGroupOwner :execrows
UPDATE "chat_group_member"
SET role = CASE
  WHEN user_id = $2 THEN 'owner'
  WHEN user_id = $3 THEN $4
  ELSE role
END,
utime = $5
WHERE group_id = $1 AND user_id IN ($2, $3)
`

type TransferChatGroupOwnerParams struct {
	GroupID  pgtype.UUID
	UserID   pgtype.UUID
	UserID_2 pgtype.UUID
	Role     string
	Utime    int64
}

func (q *Queries) TransferChatGroupOwner(ctx context.Context, arg TransferChatGroupOwnerParams) (int64, error) {
	result, err := q.db.Exec(ctx, transferChatGroupOwner,
		arg.GroupID,
		arg.UserID,
		arg.UserID_2,
		arg.Role,
		arg.Utime,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateChatGroupMemberLastSeenTime = `-- name: UpdateChatGroupMemberLastSeenTime :execrows
UPDATE "chat_group_member"
SET last_seen_time = $3,
    utime = $3
WHERE group_id = $1 AND user_id = $2
`

type UpdateChatGroupMemberLastSeenTimeParams struct {
	GroupID      pgtype.UUID
	UserID       pgtype.UUID
	LastSeenTime int64
}

func (q *Queries) UpdateChatGroupMemberLastSeenTime(ctx context.Context, arg UpdateChatGroupMemberLastSeenTimeParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateChatGroupMemberLastSeenTime, arg.GroupID, arg.UserID, arg.LastSeenTime)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateChatGroupOwnerID = `-- name: UpdateChatGroupOwnerID :execrows
UPDATE "chat_group"
SET owner_id = $2,
    utime = $3
WHERE group_id = $1
`

type UpdateChatGroupOwnerIDParams struct {
	GroupID pgtype.UUID
	OwnerID pgtype.UUID
	Utime   int64
}

func (q *Queries) UpdateChatGroupOwnerID(ctx context.Context, arg UpdateChatGroupOwnerIDParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateChatGroupOwnerID, arg.GroupID, arg.OwnerID, arg.Utime)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertChatDirectSeen = `-- name: UpsertChatDirectSeen :exec
INSERT INTO "chat_direct_seen" (
  user_id, partner_user_id, last_seen_time, ctime, utime
) VALUES (
  $1, $2, $3, $4, $4
)
ON CONFLICT (user_id, partner_user_id) DO UPDATE
SET last_seen_time = GREATEST("chat_direct_seen".last_seen_time, EXCLUDED.last_seen_time),
    utime = EXCLUDED.utime
`

type UpsertChatDirectSeenParams struct {
	UserID        pgtype.UUID
	PartnerUserID pgtype.UUID
	LastSeenTime  int64
	Ctime         int64
}

func (q *Queries) UpsertChatDirectSeen(ctx context.Context, arg UpsertChatDirectSeenParams) error {
	_, err := q.db.Exec(ctx, upsertChatDirectSeen,
		arg.UserID,
		arg.PartnerUserID,
		arg.LastSeenTime,
		arg.Ctime,
	)
	return err
}
