// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: baby.sql

package baby

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createBaby = `-- name: CreateBaby :exec
INSERT INTO "baby" (baby_id, user_id, name, gender, birthday, avatar, ctime, utime)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type CreateBabyParams struct {
	BabyID   pgtype.UUID
	UserID   pgtype.UUID
	Name     string
	Gender   string
	Birthday int64
	Avatar   string
	Ctime    int64
	Utime    int64
}

func (q *Queries) CreateBaby(ctx context.Context, arg CreateBabyParams) error {
	_, err := q.db.Exec(ctx, createBaby,
		arg.BabyID,
		arg.UserID,
		arg.Name,
		arg.Gender,
		arg.Birthday,
		arg.Avatar,
		arg.Ctime,
		arg.Utime,
	)
	return err
}

const createBabyGrowthRecord = `-- name: CreateBabyGrowthRecord :exec
INSERT INTO "baby_growth_record" (record_id, baby_id, user_id, record_time, height, weight, head_circumference, remark, ctime, utime)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
`

type CreateBabyGrowthRecordParams struct {
	RecordID          pgtype.UUID
	BabyID            pgtype.UUID
	UserID            pgtype.UUID
	RecordTime        int64
	Height            pgtype.Float8
	Weight            pgtype.Float8
	HeadCircumference pgtype.Float8
	Remark            pgtype.Text
	Ctime             int64
	Utime             int64
}

func (q *Queries) CreateBabyGrowthRecord(ctx context.Context, arg CreateBabyGrowthRecordParams) error {
	_, err := q.db.Exec(ctx, createBabyGrowthRecord,
		arg.RecordID,
		arg.BabyID,
		arg.UserID,
		arg.RecordTime,
		arg.Height,
		arg.Weight,
		arg.HeadCircumference,
		arg.Remark,
		arg.Ctime,
		arg.Utime,
	)
	return err
}

const createBabyVaccineRecord = `-- name: CreateBabyVaccineRecord :exec
INSERT INTO "baby_vaccine_record" (record_id, baby_id, dose_id, due_time, status, actual_time, ctime, utime)
VALUES ($1, $2, $3, $4, 'not_given', NULL, $5, $6)
`

type CreateBabyVaccineRecordParams struct {
	RecordID  pgtype.UUID
	BabyID    pgtype.UUID
	DoseID    pgtype.UUID
	DueTime   int64
	Ctime     int64
	Utime     int64
}

func (q *Queries) CreateBabyVaccineRecord(ctx context.Context, arg CreateBabyVaccineRecordParams) error {
	_, err := q.db.Exec(ctx, createBabyVaccineRecord,
		arg.RecordID,
		arg.BabyID,
		arg.DoseID,
		arg.DueTime,
		arg.Ctime,
		arg.Utime,
	)
	return err
}

const getBabyByIDAndUser = `-- name: GetBabyByIDAndUser :one
SELECT id, baby_id, user_id, name, gender, birthday, avatar, ctime, utime FROM "baby" WHERE baby_id = $1 AND user_id = $2 LIMIT 1
`

type GetBabyByIDAndUserParams struct {
	BabyID pgtype.UUID
	UserID pgtype.UUID
}

func (q *Queries) GetBabyByIDAndUser(ctx context.Context, arg GetBabyByIDAndUserParams) (Baby, error) {
	row := q.db.QueryRow(ctx, getBabyByIDAndUser, arg.BabyID, arg.UserID)
	var i Baby
	err := row.Scan(
		&i.ID,
		&i.BabyID,
		&i.UserID,
		&i.Name,
		&i.Gender,
		&i.Birthday,
		&i.Avatar,
		&i.Ctime,
		&i.Utime,
	)
	return i, err
}

const getLatestGrowthByBabyIDAndUser = `-- name: GetLatestGrowthByBabyIDAndUser :one
SELECT id, record_id, baby_id, user_id, record_time, height, weight, head_circumference, remark, ctime, utime FROM "baby_growth_record"
WHERE baby_id = $1 AND user_id = $2
ORDER BY record_time DESC
LIMIT 1
`

type GetLatestGrowthByBabyIDAndUserParams struct {
	BabyID pgtype.UUID
	UserID pgtype.UUID
}

func (q *Queries) GetLatestGrowthByBabyIDAndUser(ctx context.Context, arg GetLatestGrowthByBabyIDAndUserParams) (BabyGrowthRecord, error) {
	row := q.db.QueryRow(ctx, getLatestGrowthByBabyIDAndUser, arg.BabyID, arg.UserID)
	var i BabyGrowthRecord
	err := row.Scan(
		&i.ID,
		&i.RecordID,
		&i.BabyID,
		&i.UserID,
		&i.RecordTime,
		&i.Height,
		&i.Weight,
		&i.HeadCircumference,
		&i.Remark,
		&i.Ctime,
		&i.Utime,
	)
	return i, err
}

const listAllDoses = `-- name: ListAllDoses :many
SELECT d.dose_id, d.vaccine_id, v.name, v.disease, d.recommend_age_days, v.link, v.ctime, v.utime, d.dose_number
FROM "vaccine_dose" d
JOIN "vaccine" v ON v.vaccine_id = d.vaccine_id
ORDER BY v.name ASC, d.dose_number ASC
`

type ListAllDosesRow struct {
	DoseID           pgtype.UUID
	VaccineID        pgtype.UUID
	Name             string
	Disease          string
	RecommendAgeDays int32
	Link             string
	Ctime            int64
	Utime            int64
	DoseNumber       int32
}

func (q *Queries) ListAllDoses(ctx context.Context) ([]ListAllDosesRow, error) {
	rows, err := q.db.Query(ctx, listAllDoses)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAllDosesRow
	for rows.Next() {
		var i ListAllDosesRow
		if err := rows.Scan(
			&i.DoseID,
			&i.VaccineID,
			&i.Name,
			&i.Disease,
			&i.RecommendAgeDays,
			&i.Link,
			&i.Ctime,
			&i.Utime,
			&i.DoseNumber,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBabiesByUserID = `-- name: ListBabiesByUserID :many
SELECT baby_id::text AS baby_id, name, avatar FROM "baby"
WHERE user_id = $1
ORDER BY ctime DESC
`

type ListBabiesByUserIDRow struct {
	BabyID string
	Name   string
	Avatar string
}

func (q *Queries) ListBabiesByUserID(ctx context.Context, userID pgtype.UUID) ([]ListBabiesByUserIDRow, error) {
	rows, err := q.db.Query(ctx, listBabiesByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListBabiesByUserIDRow
	for rows.Next() {
		var i ListBabiesByUserIDRow
		if err := rows.Scan(&i.BabyID, &i.Name, &i.Avatar); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVaccineRecordsByBabyID = `-- name: ListVaccineRecordsByBabyID :many
SELECT d.dose_id::text AS dose_id, v.vaccine_id::text AS vaccine_id, v.name, v.disease, d.dose_number, bvr.due_time, bvr.status, COALESCE(bvr.actual_time, 0) AS actual_time
FROM "baby_vaccine_record" bvr
JOIN "vaccine_dose" d ON d.dose_id = bvr.dose_id
JOIN "vaccine" v ON v.vaccine_id = d.vaccine_id
WHERE bvr.baby_id = $1
ORDER BY v.name ASC, d.dose_number ASC
`

type ListVaccineRecordsByBabyIDRow struct {
	DoseID     string
	VaccineID  string
	Name       string
	Disease    string
	DoseNumber int32
	DueTime    int64
	Status     string
	ActualTime int64
}

func (q *Queries) ListVaccineRecordsByBabyID(ctx context.Context, babyID pgtype.UUID) ([]ListVaccineRecordsByBabyIDRow, error) {
	rows, err := q.db.Query(ctx, listVaccineRecordsByBabyID, babyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListVaccineRecordsByBabyIDRow
	for rows.Next() {
		var i ListVaccineRecordsByBabyIDRow
		if err := rows.Scan(
			&i.DoseID,
			&i.VaccineID,
			&i.Name,
			&i.Disease,
			&i.DoseNumber,
			&i.DueTime,
			&i.Status,
			&i.ActualTime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateVaccineStatusGiven = `-- name: UpdateVaccineStatusGiven :execrows
UPDATE "baby_vaccine_record"
SET status = 'given', actual_time = $3, utime = $4
WHERE baby_id = $1 AND dose_id = $2
`

type UpdateVaccineStatusGivenParams struct {
	BabyID     pgtype.UUID
	DoseID     pgtype.UUID
	ActualTime pgtype.Int8
	Utime      int64
}

func (q *Queries) UpdateVaccineStatusGiven(ctx context.Context, arg UpdateVaccineStatusGivenParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateVaccineStatusGiven,
		arg.BabyID,
		arg.DoseID,
		arg.ActualTime,
		arg.Utime,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateVaccineStatusNotGiven = `-- name: UpdateVaccineStatusNotGiven :execrows
UPDATE "baby_vaccine_record"
SET status = 'not_given', actual_time = NULL, utime = $3
WHERE baby_id = $1 AND dose_id = $2
`

type UpdateVaccineStatusNotGivenParams struct {
	BabyID    pgtype.UUID
	DoseID    pgtype.UUID
	Utime     int64
}

func (q *Queries) UpdateVaccineStatusNotGiven(ctx context.Context, arg UpdateVaccineStatusNotGivenParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateVaccineStatusNotGiven, arg.BabyID, arg.DoseID, arg.Utime)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
