// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: baby.sql

package baby

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createBaby = `-- name: CreateBaby :exec
INSERT INTO "baby" (baby_id, user_id, name, gender, birthday, avatar, ctime, utime)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type CreateBabyParams struct {
	BabyID   pgtype.UUID
	UserID   pgtype.UUID
	Name     string
	Gender   string
	Birthday int64
	Avatar   string
	Ctime    int64
	Utime    int64
}

func (q *Queries) CreateBaby(ctx context.Context, arg CreateBabyParams) error {
	_, err := q.db.Exec(ctx, createBaby,
		arg.BabyID,
		arg.UserID,
		arg.Name,
		arg.Gender,
		arg.Birthday,
		arg.Avatar,
		arg.Ctime,
		arg.Utime,
	)
	return err
}

const createBabyGrowthRecord = `-- name: CreateBabyGrowthRecord :exec
INSERT INTO "baby_growth_record" (record_id, baby_id, record_time, height, weight, head_circumference, remark, ctime, utime, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
`

type CreateBabyGrowthRecordParams struct {
	RecordID          pgtype.UUID
	BabyID            pgtype.UUID
	RecordTime        int64
	Height            pgtype.Float8
	Weight            pgtype.Float8
	HeadCircumference pgtype.Float8
	Remark            pgtype.Text
	Ctime             int64
	Utime             int64
	CreatedBy         pgtype.UUID
}

func (q *Queries) CreateBabyGrowthRecord(ctx context.Context, arg CreateBabyGrowthRecordParams) error {
	_, err := q.db.Exec(ctx, createBabyGrowthRecord,
		arg.RecordID,
		arg.BabyID,
		arg.RecordTime,
		arg.Height,
		arg.Weight,
		arg.HeadCircumference,
		arg.Remark,
		arg.Ctime,
		arg.Utime,
		arg.CreatedBy,
	)
	return err
}

const createBabyVaccineRecord = `-- name: CreateBabyVaccineRecord :exec
INSERT INTO "baby_vaccine_record" (record_id, baby_id, dose_id, due_time, status, actual_time, ctime, utime)
VALUES ($1, $2, $3, $4, 'not_given', NULL, $5, $6)
`

type CreateBabyVaccineRecordParams struct {
	RecordID pgtype.UUID
	BabyID   pgtype.UUID
	DoseID   pgtype.UUID
	DueTime  int64
	Ctime    int64
	Utime    int64
}

func (q *Queries) CreateBabyVaccineRecord(ctx context.Context, arg CreateBabyVaccineRecordParams) error {
	_, err := q.db.Exec(ctx, createBabyVaccineRecord,
		arg.RecordID,
		arg.BabyID,
		arg.DoseID,
		arg.DueTime,
		arg.Ctime,
		arg.Utime,
	)
	return err
}

const createDiaper = `-- name: CreateDiaper :one
INSERT INTO "daily_diaper" (
  diaper_id, baby_id, user_id, change_time, diaper_type,
  pee_color, poop_color, poop_consistency, remark, ctime, utime
) VALUES (
  gen_random_uuid(), $1, $2, $3, $4,
  COALESCE(NULLIF($5, ''), NULL),
  COALESCE(NULLIF($6, ''), NULL),
  COALESCE(NULLIF($7, ''), NULL),
  COALESCE(NULLIF($8, ''), NULL), $9, $9
) RETURNING diaper_id::text AS diaper_id, change_time, diaper_type,
  COALESCE(pee_color, '') AS pee_color,
  COALESCE(poop_color, '') AS poop_color,
  COALESCE(poop_consistency, '') AS poop_consistency,
  COALESCE(remark, '') AS remark
`

type CreateDiaperParams struct {
	BabyID     pgtype.UUID
	UserID     pgtype.UUID
	ChangeTime int64
	DiaperType string
	Column5    interface{}
	Column6    interface{}
	Column7    interface{}
	Column8    interface{}
	Ctime      int64
}

type CreateDiaperRow struct {
	DiaperID        string
	ChangeTime      int64
	DiaperType      string
	PeeColor        string
	PoopColor       string
	PoopConsistency string
	Remark          string
}

func (q *Queries) CreateDiaper(ctx context.Context, arg CreateDiaperParams) (CreateDiaperRow, error) {
	row := q.db.QueryRow(ctx, createDiaper,
		arg.BabyID,
		arg.UserID,
		arg.ChangeTime,
		arg.DiaperType,
		arg.Column5,
		arg.Column6,
		arg.Column7,
		arg.Column8,
		arg.Ctime,
	)
	var i CreateDiaperRow
	err := row.Scan(
		&i.DiaperID,
		&i.ChangeTime,
		&i.DiaperType,
		&i.PeeColor,
		&i.PoopColor,
		&i.PoopConsistency,
		&i.Remark,
	)
	return i, err
}

const createFeeding = `-- name: CreateFeeding :one
INSERT INTO "daily_feeding" (
  feeding_id, baby_id, user_id, feed_time, feed_type, remark, ctime, utime
) VALUES (
  gen_random_uuid(), $1, $2, $3, $4, COALESCE(NULLIF($5, ''), NULL), $6, $6
) RETURNING feeding_id::text AS feeding_id, feed_time, feed_type, COALESCE(remark, '') AS remark
`

type CreateFeedingParams struct {
	BabyID   pgtype.UUID
	UserID   pgtype.UUID
	FeedTime int64
	FeedType string
	Column5  interface{}
	Ctime    int64
}

type CreateFeedingRow struct {
	FeedingID string
	FeedTime  int64
	FeedType  string
	Remark    string
}

func (q *Queries) CreateFeeding(ctx context.Context, arg CreateFeedingParams) (CreateFeedingRow, error) {
	row := q.db.QueryRow(ctx, createFeeding,
		arg.BabyID,
		arg.UserID,
		arg.FeedTime,
		arg.FeedType,
		arg.Column5,
		arg.Ctime,
	)
	var i CreateFeedingRow
	err := row.Scan(
		&i.FeedingID,
		&i.FeedTime,
		&i.FeedType,
		&i.Remark,
	)
	return i, err
}

const deleteBabyPhotos = `-- name: DeleteBabyPhotos :execrows
DELETE FROM "baby_photo"
WHERE baby_id = $1 AND photo_id = ANY($2::uuid[])
`

type DeleteBabyPhotosParams struct {
	BabyID  pgtype.UUID
	Column2 []pgtype.UUID
}

func (q *Queries) DeleteBabyPhotos(ctx context.Context, arg DeleteBabyPhotosParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteBabyPhotos, arg.BabyID, arg.Column2)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getActiveSleep = `-- name: GetActiveSleep :one
SELECT sleep_id::text AS sleep_id, start_time
FROM "daily_sleep"
WHERE baby_id = $1 AND user_id = $2 AND status = 'running'
LIMIT 1
`

type GetActiveSleepParams struct {
	BabyID pgtype.UUID
	UserID pgtype.UUID
}

type GetActiveSleepRow struct {
	SleepID   string
	StartTime int64
}

func (q *Queries) GetActiveSleep(ctx context.Context, arg GetActiveSleepParams) (GetActiveSleepRow, error) {
	row := q.db.QueryRow(ctx, getActiveSleep, arg.BabyID, arg.UserID)
	var i GetActiveSleepRow
	err := row.Scan(&i.SleepID, &i.StartTime)
	return i, err
}

const getBabyByIDAndUser = `-- name: GetBabyByIDAndUser :one
SELECT id, baby_id, user_id, name, gender, birthday, avatar, ctime, utime FROM "baby" WHERE baby_id = $1 AND user_id = $2 LIMIT 1
`

type GetBabyByIDAndUserParams struct {
	BabyID pgtype.UUID
	UserID pgtype.UUID
}

func (q *Queries) GetBabyByIDAndUser(ctx context.Context, arg GetBabyByIDAndUserParams) (Baby, error) {
	row := q.db.QueryRow(ctx, getBabyByIDAndUser, arg.BabyID, arg.UserID)
	var i Baby
	err := row.Scan(
		&i.ID,
		&i.BabyID,
		&i.UserID,
		&i.Name,
		&i.Gender,
		&i.Birthday,
		&i.Avatar,
		&i.Ctime,
		&i.Utime,
	)
	return i, err
}

const getDailyStatsByBaby = `-- name: GetDailyStatsByBaby :one
WITH feed_stats AS (
  SELECT COUNT(*) AS c
  FROM "daily_feeding" f
  WHERE f.baby_id = $1 AND f.feed_time BETWEEN $2 AND $3
),
sleep_stats AS (
  SELECT COALESCE(SUM(LEAST(s.end_time, $3) - GREATEST(s.start_time, $2)), 0)::bigint AS d
  FROM "daily_sleep" s
  WHERE s.baby_id = $1 AND s.status = 'finished' AND s.start_time <= $3 AND s.end_time >= $2
),
diaper_stats AS (
  SELECT COUNT(*) AS c
  FROM "daily_diaper" d
  WHERE d.baby_id = $1 AND d.change_time BETWEEN $2 AND $3
)
SELECT feed_stats.c AS feeding_count, sleep_stats.d AS sleep_duration_ms, diaper_stats.c AS diaper_count
FROM feed_stats, sleep_stats, diaper_stats
`

type GetDailyStatsByBabyParams struct {
	BabyID     pgtype.UUID
	FeedTime   int64
	FeedTime_2 int64
}

type GetDailyStatsByBabyRow struct {
	FeedingCount    int64
	SleepDurationMs int64
	DiaperCount     int64
}

func (q *Queries) GetDailyStatsByBaby(ctx context.Context, arg GetDailyStatsByBabyParams) (GetDailyStatsByBabyRow, error) {
	row := q.db.QueryRow(ctx, getDailyStatsByBaby, arg.BabyID, arg.FeedTime, arg.FeedTime_2)
	var i GetDailyStatsByBabyRow
	err := row.Scan(&i.FeedingCount, &i.SleepDurationMs, &i.DiaperCount)
	return i, err
}

const getDiaperByBabyBetween = `-- name: GetDiaperByBabyBetween :one
SELECT diaper_id::text AS diaper_id, change_time, diaper_type,
  COALESCE(pee_color, '') AS pee_color,
  COALESCE(poop_color, '') AS poop_color,
  COALESCE(poop_consistency, '') AS poop_consistency,
  COALESCE(remark, '') AS remark
FROM "daily_diaper"
WHERE baby_id = $1 AND change_time BETWEEN $2 AND $3
ORDER BY change_time DESC
LIMIT 1
`

type GetDiaperByBabyBetweenParams struct {
	BabyID       pgtype.UUID
	ChangeTime   int64
	ChangeTime_2 int64
}

type GetDiaperByBabyBetweenRow struct {
	DiaperID        string
	ChangeTime      int64
	DiaperType      string
	PeeColor        string
	PoopColor       string
	PoopConsistency string
	Remark          string
}

func (q *Queries) GetDiaperByBabyBetween(ctx context.Context, arg GetDiaperByBabyBetweenParams) (GetDiaperByBabyBetweenRow, error) {
	row := q.db.QueryRow(ctx, getDiaperByBabyBetween, arg.BabyID, arg.ChangeTime, arg.ChangeTime_2)
	var i GetDiaperByBabyBetweenRow
	err := row.Scan(
		&i.DiaperID,
		&i.ChangeTime,
		&i.DiaperType,
		&i.PeeColor,
		&i.PoopColor,
		&i.PoopConsistency,
		&i.Remark,
	)
	return i, err
}

const getGrowthByBabyIDBetween = `-- name: GetGrowthByBabyIDBetween :one
SELECT id, record_id, baby_id, created_by, record_time, height, weight, head_circumference, remark, ctime, updated_by, utime FROM "baby_growth_record"
WHERE baby_id = $1 AND record_time BETWEEN $2 AND $3
ORDER BY record_time DESC
LIMIT 1
`

type GetGrowthByBabyIDBetweenParams struct {
	BabyID       pgtype.UUID
	RecordTime   int64
	RecordTime_2 int64
}

func (q *Queries) GetGrowthByBabyIDBetween(ctx context.Context, arg GetGrowthByBabyIDBetweenParams) (BabyGrowthRecord, error) {
	row := q.db.QueryRow(ctx, getGrowthByBabyIDBetween, arg.BabyID, arg.RecordTime, arg.RecordTime_2)
	var i BabyGrowthRecord
	err := row.Scan(
		&i.ID,
		&i.RecordID,
		&i.BabyID,
		&i.CreatedBy,
		&i.RecordTime,
		&i.Height,
		&i.Weight,
		&i.HeadCircumference,
		&i.Remark,
		&i.Ctime,
		&i.UpdatedBy,
		&i.Utime,
	)
	return i, err
}

const getLatestGrowthByBabyID = `-- name: GetLatestGrowthByBabyID :one
SELECT id, record_id, baby_id, created_by, record_time, height, weight, head_circumference, remark, ctime, updated_by, utime FROM "baby_growth_record"
WHERE baby_id = $1
ORDER BY record_time DESC
LIMIT 1
`

func (q *Queries) GetLatestGrowthByBabyID(ctx context.Context, babyID pgtype.UUID) (BabyGrowthRecord, error) {
	row := q.db.QueryRow(ctx, getLatestGrowthByBabyID, babyID)
	var i BabyGrowthRecord
	err := row.Scan(
		&i.ID,
		&i.RecordID,
		&i.BabyID,
		&i.CreatedBy,
		&i.RecordTime,
		&i.Height,
		&i.Weight,
		&i.HeadCircumference,
		&i.Remark,
		&i.Ctime,
		&i.UpdatedBy,
		&i.Utime,
	)
	return i, err
}

const getLatestNonNullGrowthValuesByBaby = `-- name: GetLatestNonNullGrowthValuesByBaby :one
SELECT
  (SELECT bgr.height FROM "baby_growth_record" bgr WHERE bgr.baby_id = $1 AND bgr.height IS NOT NULL ORDER BY bgr.record_time DESC LIMIT 1) AS height,
  (SELECT bgr.weight FROM "baby_growth_record" bgr WHERE bgr.baby_id = $1 AND bgr.weight IS NOT NULL ORDER BY bgr.record_time DESC LIMIT 1) AS weight,
  (SELECT bgr.head_circumference FROM "baby_growth_record" bgr WHERE bgr.baby_id = $1 AND bgr.head_circumference IS NOT NULL ORDER BY bgr.record_time DESC LIMIT 1) AS head_circumference
`

type GetLatestNonNullGrowthValuesByBabyRow struct {
	Height            pgtype.Float8
	Weight            pgtype.Float8
	HeadCircumference pgtype.Float8
}

func (q *Queries) GetLatestNonNullGrowthValuesByBaby(ctx context.Context, babyID pgtype.UUID) (GetLatestNonNullGrowthValuesByBabyRow, error) {
	row := q.db.QueryRow(ctx, getLatestNonNullGrowthValuesByBaby, babyID)
	var i GetLatestNonNullGrowthValuesByBabyRow
	err := row.Scan(&i.Height, &i.Weight, &i.HeadCircumference)
	return i, err
}

const listAllDoses = `-- name: ListAllDoses :many
SELECT d.dose_id, d.vaccine_id, v.name, v.disease, d.recommend_age_days, v.link, v.ctime, v.utime, d.dose_number
FROM "vaccine_dose" d
JOIN "vaccine" v ON v.vaccine_id = d.vaccine_id
ORDER BY v.name ASC, d.dose_number ASC
`

type ListAllDosesRow struct {
	DoseID           pgtype.UUID
	VaccineID        pgtype.UUID
	Name             string
	Disease          string
	RecommendAgeDays int32
	Link             string
	Ctime            int64
	Utime            int64
	DoseNumber       int32
}

// 列出所有剂次（用于初始化宝宝疫苗记录）
func (q *Queries) ListAllDoses(ctx context.Context) ([]ListAllDosesRow, error) {
	rows, err := q.db.Query(ctx, listAllDoses)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAllDosesRow
	for rows.Next() {
		var i ListAllDosesRow
		if err := rows.Scan(
			&i.DoseID,
			&i.VaccineID,
			&i.Name,
			&i.Disease,
			&i.RecommendAgeDays,
			&i.Link,
			&i.Ctime,
			&i.Utime,
			&i.DoseNumber,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBabiesByUserID = `-- name: ListBabiesByUserID :many
SELECT baby_id::text AS baby_id, name, avatar FROM "baby"
WHERE user_id = $1
ORDER BY ctime DESC
`

type ListBabiesByUserIDRow struct {
	BabyID string
	Name   string
	Avatar string
}

func (q *Queries) ListBabiesByUserID(ctx context.Context, userID pgtype.UUID) ([]ListBabiesByUserIDRow, error) {
	rows, err := q.db.Query(ctx, listBabiesByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListBabiesByUserIDRow
	for rows.Next() {
		var i ListBabiesByUserIDRow
		if err := rows.Scan(&i.BabyID, &i.Name, &i.Avatar); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBabyPhotos = `-- name: ListBabyPhotos :many
SELECT photo_id::text AS photo_id, link, ctime
FROM "baby_photo"
WHERE baby_id = $1
ORDER BY ctime DESC
LIMIT $2 OFFSET $3
`

type ListBabyPhotosParams struct {
	BabyID pgtype.UUID
	Limit  int32
	Offset int32
}

type ListBabyPhotosRow struct {
	PhotoID string
	Link    string
	Ctime   int64
}

func (q *Queries) ListBabyPhotos(ctx context.Context, arg ListBabyPhotosParams) ([]ListBabyPhotosRow, error) {
	rows, err := q.db.Query(ctx, listBabyPhotos, arg.BabyID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListBabyPhotosRow
	for rows.Next() {
		var i ListBabyPhotosRow
		if err := rows.Scan(&i.PhotoID, &i.Link, &i.Ctime); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDiaperByBabyBetween = `-- name: ListDiaperByBabyBetween :many
SELECT diaper_id::text AS diaper_id, change_time, diaper_type,
  COALESCE(pee_color, '') AS pee_color,
  COALESCE(poop_color, '') AS poop_color,
  COALESCE(poop_consistency, '') AS poop_consistency,
  COALESCE(remark, '') AS remark
FROM "daily_diaper"
WHERE baby_id = $1 AND change_time BETWEEN $2 AND $3
ORDER BY change_time ASC
`

type ListDiaperByBabyBetweenParams struct {
	BabyID       pgtype.UUID
	ChangeTime   int64
	ChangeTime_2 int64
}

type ListDiaperByBabyBetweenRow struct {
	DiaperID        string
	ChangeTime      int64
	DiaperType      string
	PeeColor        string
	PoopColor       string
	PoopConsistency string
	Remark          string
}

func (q *Queries) ListDiaperByBabyBetween(ctx context.Context, arg ListDiaperByBabyBetweenParams) ([]ListDiaperByBabyBetweenRow, error) {
	rows, err := q.db.Query(ctx, listDiaperByBabyBetween, arg.BabyID, arg.ChangeTime, arg.ChangeTime_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDiaperByBabyBetweenRow
	for rows.Next() {
		var i ListDiaperByBabyBetweenRow
		if err := rows.Scan(
			&i.DiaperID,
			&i.ChangeTime,
			&i.DiaperType,
			&i.PeeColor,
			&i.PoopColor,
			&i.PoopConsistency,
			&i.Remark,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFeedingByBabyBetween = `-- name: ListFeedingByBabyBetween :many
SELECT feeding_id::text AS feeding_id, feed_time, feed_type, COALESCE(remark, '') AS remark
FROM "daily_feeding"
WHERE baby_id = $1 AND feed_time BETWEEN $2 AND $3
ORDER BY feed_time ASC
`

type ListFeedingByBabyBetweenParams struct {
	BabyID     pgtype.UUID
	FeedTime   int64
	FeedTime_2 int64
}

type ListFeedingByBabyBetweenRow struct {
	FeedingID string
	FeedTime  int64
	FeedType  string
	Remark    string
}

func (q *Queries) ListFeedingByBabyBetween(ctx context.Context, arg ListFeedingByBabyBetweenParams) ([]ListFeedingByBabyBetweenRow, error) {
	rows, err := q.db.Query(ctx, listFeedingByBabyBetween, arg.BabyID, arg.FeedTime, arg.FeedTime_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFeedingByBabyBetweenRow
	for rows.Next() {
		var i ListFeedingByBabyBetweenRow
		if err := rows.Scan(
			&i.FeedingID,
			&i.FeedTime,
			&i.FeedType,
			&i.Remark,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHeadCircumferenceCurveByBabyIDBetween = `-- name: ListHeadCircumferenceCurveByBabyIDBetween :many
SELECT record_time, head_circumference
FROM "baby_growth_record"
WHERE baby_id = $1 AND record_time BETWEEN $2 AND $3 AND head_circumference IS NOT NULL
ORDER BY record_time ASC
`

type ListHeadCircumferenceCurveByBabyIDBetweenParams struct {
	BabyID       pgtype.UUID
	RecordTime   int64
	RecordTime_2 int64
}

type ListHeadCircumferenceCurveByBabyIDBetweenRow struct {
	RecordTime        int64
	HeadCircumference pgtype.Float8
}

func (q *Queries) ListHeadCircumferenceCurveByBabyIDBetween(ctx context.Context, arg ListHeadCircumferenceCurveByBabyIDBetweenParams) ([]ListHeadCircumferenceCurveByBabyIDBetweenRow, error) {
	rows, err := q.db.Query(ctx, listHeadCircumferenceCurveByBabyIDBetween, arg.BabyID, arg.RecordTime, arg.RecordTime_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListHeadCircumferenceCurveByBabyIDBetweenRow
	for rows.Next() {
		var i ListHeadCircumferenceCurveByBabyIDBetweenRow
		if err := rows.Scan(&i.RecordTime, &i.HeadCircumference); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHeightCurveByBabyIDBetween = `-- name: ListHeightCurveByBabyIDBetween :many
SELECT record_time, height
FROM "baby_growth_record"
WHERE baby_id = $1 AND record_time BETWEEN $2 AND $3 AND height IS NOT NULL
ORDER BY record_time ASC
`

type ListHeightCurveByBabyIDBetweenParams struct {
	BabyID       pgtype.UUID
	RecordTime   int64
	RecordTime_2 int64
}

type ListHeightCurveByBabyIDBetweenRow struct {
	RecordTime int64
	Height     pgtype.Float8
}

func (q *Queries) ListHeightCurveByBabyIDBetween(ctx context.Context, arg ListHeightCurveByBabyIDBetweenParams) ([]ListHeightCurveByBabyIDBetweenRow, error) {
	rows, err := q.db.Query(ctx, listHeightCurveByBabyIDBetween, arg.BabyID, arg.RecordTime, arg.RecordTime_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListHeightCurveByBabyIDBetweenRow
	for rows.Next() {
		var i ListHeightCurveByBabyIDBetweenRow
		if err := rows.Scan(&i.RecordTime, &i.Height); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSleepByBabyBetween = `-- name: ListSleepByBabyBetween :many
SELECT sleep_id::text AS session_id, start_time, end_time, duration
FROM "daily_sleep"
WHERE baby_id = $1
  AND status = 'finished'
  AND start_time <= $3
  AND end_time >= $2
ORDER BY start_time ASC
`

type ListSleepByBabyBetweenParams struct {
	BabyID    pgtype.UUID
	EndTime   pgtype.Int8
	StartTime int64
}

type ListSleepByBabyBetweenRow struct {
	SessionID string
	StartTime int64
	EndTime   pgtype.Int8
	Duration  pgtype.Int8
}

func (q *Queries) ListSleepByBabyBetween(ctx context.Context, arg ListSleepByBabyBetweenParams) ([]ListSleepByBabyBetweenRow, error) {
	rows, err := q.db.Query(ctx, listSleepByBabyBetween, arg.BabyID, arg.EndTime, arg.StartTime)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSleepByBabyBetweenRow
	for rows.Next() {
		var i ListSleepByBabyBetweenRow
		if err := rows.Scan(
			&i.SessionID,
			&i.StartTime,
			&i.EndTime,
			&i.Duration,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVaccineRecordsByBabyID = `-- name: ListVaccineRecordsByBabyID :many
SELECT 
  d.dose_id::text AS dose_id,
  v.vaccine_id::text AS vaccine_id,
  v.name,
  v.disease,
  v.link,
  d.dose_number,
  bvr.due_time,
  bvr.status,
  COALESCE(bvr.actual_time, 0) AS actual_time
FROM "baby_vaccine_record" bvr
JOIN "vaccine_dose" d ON d.dose_id = bvr.dose_id
JOIN "vaccine" v ON v.vaccine_id = d.vaccine_id
WHERE bvr.baby_id = $1
ORDER BY v.name ASC, d.dose_number ASC
`

type ListVaccineRecordsByBabyIDRow struct {
	DoseID     string
	VaccineID  string
	Name       string
	Disease    string
	Link       string
	DoseNumber int32
	DueTime    int64
	Status     string
	ActualTime int64
}

func (q *Queries) ListVaccineRecordsByBabyID(ctx context.Context, babyID pgtype.UUID) ([]ListVaccineRecordsByBabyIDRow, error) {
	rows, err := q.db.Query(ctx, listVaccineRecordsByBabyID, babyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListVaccineRecordsByBabyIDRow
	for rows.Next() {
		var i ListVaccineRecordsByBabyIDRow
		if err := rows.Scan(
			&i.DoseID,
			&i.VaccineID,
			&i.Name,
			&i.Disease,
			&i.Link,
			&i.DoseNumber,
			&i.DueTime,
			&i.Status,
			&i.ActualTime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWeightCurveByBabyIDBetween = `-- name: ListWeightCurveByBabyIDBetween :many
SELECT record_time, weight
FROM "baby_growth_record"
WHERE baby_id = $1 AND record_time BETWEEN $2 AND $3 AND weight IS NOT NULL
ORDER BY record_time ASC
`

type ListWeightCurveByBabyIDBetweenParams struct {
	BabyID       pgtype.UUID
	RecordTime   int64
	RecordTime_2 int64
}

type ListWeightCurveByBabyIDBetweenRow struct {
	RecordTime int64
	Weight     pgtype.Float8
}

func (q *Queries) ListWeightCurveByBabyIDBetween(ctx context.Context, arg ListWeightCurveByBabyIDBetweenParams) ([]ListWeightCurveByBabyIDBetweenRow, error) {
	rows, err := q.db.Query(ctx, listWeightCurveByBabyIDBetween, arg.BabyID, arg.RecordTime, arg.RecordTime_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListWeightCurveByBabyIDBetweenRow
	for rows.Next() {
		var i ListWeightCurveByBabyIDBetweenRow
		if err := rows.Scan(&i.RecordTime, &i.Weight); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const startSleep = `-- name: StartSleep :one
WITH ins AS (
  INSERT INTO "daily_sleep" (
    sleep_id, baby_id, user_id, start_time, end_time, duration,
    source, status, ctime, utime
  )
  VALUES (
    gen_random_uuid(), $1, $2, EXTRACT(EPOCH FROM NOW())*1000, NULL, NULL,
    'timer', 'running', EXTRACT(EPOCH FROM NOW())*1000, EXTRACT(EPOCH FROM NOW())*1000
  )
  ON CONFLICT DO NOTHING
  RETURNING sleep_id, baby_id, user_id, start_time
)
SELECT sleep_id::text AS sleep_id, baby_id::text AS baby_id, user_id::text AS user_id, start_time
FROM ins
UNION ALL
SELECT sleep_id::text, baby_id::text, user_id::text, start_time
FROM "daily_sleep"
WHERE baby_id = $1 AND user_id = $2 AND status = 'running'
LIMIT 1
`

type StartSleepParams struct {
	BabyID pgtype.UUID
	UserID pgtype.UUID
}

type StartSleepRow struct {
	SleepID   string
	BabyID    string
	UserID    string
	StartTime int64
}

func (q *Queries) StartSleep(ctx context.Context, arg StartSleepParams) (StartSleepRow, error) {
	row := q.db.QueryRow(ctx, startSleep, arg.BabyID, arg.UserID)
	var i StartSleepRow
	err := row.Scan(
		&i.SleepID,
		&i.BabyID,
		&i.UserID,
		&i.StartTime,
	)
	return i, err
}

const stopSleep = `-- name: StopSleep :one
UPDATE "daily_sleep"
SET
  end_time = EXTRACT(EPOCH FROM NOW())*1000,
  duration = EXTRACT(EPOCH FROM NOW())*1000 - start_time,
  status   = 'finished',
  utime    = EXTRACT(EPOCH FROM NOW())*1000
WHERE sleep_id = $1
RETURNING sleep_id::text AS sleep_id, baby_id::text AS baby_id, user_id::text AS user_id, start_time, end_time, duration
`

type StopSleepRow struct {
	SleepID   string
	BabyID    string
	UserID    string
	StartTime int64
	EndTime   pgtype.Int8
	Duration  pgtype.Int8
}

func (q *Queries) StopSleep(ctx context.Context, sleepID pgtype.UUID) (StopSleepRow, error) {
	row := q.db.QueryRow(ctx, stopSleep, sleepID)
	var i StopSleepRow
	err := row.Scan(
		&i.SleepID,
		&i.BabyID,
		&i.UserID,
		&i.StartTime,
		&i.EndTime,
		&i.Duration,
	)
	return i, err
}

const updateDiaper = `-- name: UpdateDiaper :one
UPDATE "daily_diaper"
SET
  diaper_type      = $3,
  change_time      = $4,
  pee_color        = COALESCE(NULLIF($5, ''), NULL),
  poop_color       = COALESCE(NULLIF($6, ''), NULL),
  poop_consistency = COALESCE(NULLIF($7, ''), NULL),
  remark           = COALESCE(NULLIF($8, ''), NULL),
  utime            = $9
WHERE baby_id = $1 AND diaper_id = $2
RETURNING diaper_id::text AS diaper_id, change_time, diaper_type,
  COALESCE(pee_color, '') AS pee_color,
  COALESCE(poop_color, '') AS poop_color,
  COALESCE(poop_consistency, '') AS poop_consistency,
  COALESCE(remark, '') AS remark
`

type UpdateDiaperParams struct {
	BabyID     pgtype.UUID
	DiaperID   pgtype.UUID
	DiaperType string
	ChangeTime int64
	Column5    interface{}
	Column6    interface{}
	Column7    interface{}
	Column8    interface{}
	Utime      int64
}

type UpdateDiaperRow struct {
	DiaperID        string
	ChangeTime      int64
	DiaperType      string
	PeeColor        string
	PoopColor       string
	PoopConsistency string
	Remark          string
}

func (q *Queries) UpdateDiaper(ctx context.Context, arg UpdateDiaperParams) (UpdateDiaperRow, error) {
	row := q.db.QueryRow(ctx, updateDiaper,
		arg.BabyID,
		arg.DiaperID,
		arg.DiaperType,
		arg.ChangeTime,
		arg.Column5,
		arg.Column6,
		arg.Column7,
		arg.Column8,
		arg.Utime,
	)
	var i UpdateDiaperRow
	err := row.Scan(
		&i.DiaperID,
		&i.ChangeTime,
		&i.DiaperType,
		&i.PeeColor,
		&i.PoopColor,
		&i.PoopConsistency,
		&i.Remark,
	)
	return i, err
}

const updateFeeding = `-- name: UpdateFeeding :one
UPDATE "daily_feeding"
SET
  feed_type = $3,
  feed_time = $4,
  remark    = COALESCE(NULLIF($5, ''), NULL),
  utime     = $6
WHERE baby_id = $1 AND feeding_id = $2
RETURNING feeding_id::text AS feeding_id, feed_time, feed_type, COALESCE(remark, '') AS remark
`

type UpdateFeedingParams struct {
	BabyID    pgtype.UUID
	FeedingID pgtype.UUID
	FeedType  string
	FeedTime  int64
	Column5   interface{}
	Utime     int64
}

type UpdateFeedingRow struct {
	FeedingID string
	FeedTime  int64
	FeedType  string
	Remark    string
}

func (q *Queries) UpdateFeeding(ctx context.Context, arg UpdateFeedingParams) (UpdateFeedingRow, error) {
	row := q.db.QueryRow(ctx, updateFeeding,
		arg.BabyID,
		arg.FeedingID,
		arg.FeedType,
		arg.FeedTime,
		arg.Column5,
		arg.Utime,
	)
	var i UpdateFeedingRow
	err := row.Scan(
		&i.FeedingID,
		&i.FeedTime,
		&i.FeedType,
		&i.Remark,
	)
	return i, err
}

const updateGrowthByRecordID = `-- name: UpdateGrowthByRecordID :exec
UPDATE "baby_growth_record"
SET record_time = $2,
    height = $3,
    weight = $4,
    head_circumference = $5,
    remark = COALESCE(NULLIF($6, ''), remark),
    updated_by = $7,
    utime = $8
WHERE record_id = $1
`

type UpdateGrowthByRecordIDParams struct {
	RecordID          pgtype.UUID
	RecordTime        int64
	Height            pgtype.Float8
	Weight            pgtype.Float8
	HeadCircumference pgtype.Float8
	Column6           interface{}
	UpdatedBy         pgtype.UUID
	Utime             int64
}

func (q *Queries) UpdateGrowthByRecordID(ctx context.Context, arg UpdateGrowthByRecordIDParams) error {
	_, err := q.db.Exec(ctx, updateGrowthByRecordID,
		arg.RecordID,
		arg.RecordTime,
		arg.Height,
		arg.Weight,
		arg.HeadCircumference,
		arg.Column6,
		arg.UpdatedBy,
		arg.Utime,
	)
	return err
}

const updateVaccineStatusGiven = `-- name: UpdateVaccineStatusGiven :execrows
UPDATE "baby_vaccine_record"
SET status = 'given', actual_time = $3, utime = $4
WHERE baby_id = $1 AND dose_id = $2
`

type UpdateVaccineStatusGivenParams struct {
	BabyID     pgtype.UUID
	DoseID     pgtype.UUID
	ActualTime pgtype.Int8
	Utime      int64
}

func (q *Queries) UpdateVaccineStatusGiven(ctx context.Context, arg UpdateVaccineStatusGivenParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateVaccineStatusGiven,
		arg.BabyID,
		arg.DoseID,
		arg.ActualTime,
		arg.Utime,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateVaccineStatusNotGiven = `-- name: UpdateVaccineStatusNotGiven :execrows
UPDATE "baby_vaccine_record"
SET status = 'not_given', actual_time = NULL, utime = $3
WHERE baby_id = $1 AND dose_id = $2
`

type UpdateVaccineStatusNotGivenParams struct {
	BabyID pgtype.UUID
	DoseID pgtype.UUID
	Utime  int64
}

func (q *Queries) UpdateVaccineStatusNotGiven(ctx context.Context, arg UpdateVaccineStatusNotGivenParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateVaccineStatusNotGiven, arg.BabyID, arg.DoseID, arg.Utime)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const uploadBabyPhotos = `-- name: UploadBabyPhotos :many
WITH lnk AS (SELECT unnest($2::text[]) AS link)
INSERT INTO "baby_photo" (photo_id, baby_id, link, ctime, utime)
SELECT gen_random_uuid(), $1, lnk.link, $3, $3 FROM lnk
RETURNING photo_id::text AS photo_id, link, ctime
`

type UploadBabyPhotosParams struct {
	BabyID  pgtype.UUID
	Column2 []string
	Ctime   int64
}

type UploadBabyPhotosRow struct {
	PhotoID string
	Link    string
	Ctime   int64
}

func (q *Queries) UploadBabyPhotos(ctx context.Context, arg UploadBabyPhotosParams) ([]UploadBabyPhotosRow, error) {
	rows, err := q.db.Query(ctx, uploadBabyPhotos, arg.BabyID, arg.Column2, arg.Ctime)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UploadBabyPhotosRow
	for rows.Next() {
		var i UploadBabyPhotosRow
		if err := rows.Scan(&i.PhotoID, &i.Link, &i.Ctime); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
