// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package baby

import (
	"github.com/jackc/pgx/v5/pgtype"
)

// 宝宝表
type Baby struct {
	// 主键ID
	ID int64
	// 宝宝ID
	BabyID pgtype.UUID
	// 所属用户ID(UUID)
	UserID pgtype.UUID
	// 宝宝姓名
	Name string
	// 性别:male/female
	Gender string
	// 生日(毫秒时间戳)
	Birthday int64
	// 宝宝头像URL
	Avatar string
	// 创建时间戳
	Ctime int64
	// 更新时间戳
	Utime int64
}

// 宝宝成长记录表
type BabyGrowthRecord struct {
	// 主键ID
	ID int64
	// 记录ID
	RecordID pgtype.UUID
	// 宝宝ID(外键)
	BabyID pgtype.UUID
	// 用户ID(UUID)
	UserID pgtype.UUID
	// 记录时间(毫秒时间戳)
	RecordTime int64
	// 身高(cm)
	Height pgtype.Float8
	// 体重(kg)
	Weight pgtype.Float8
	// 头围(cm)
	HeadCircumference pgtype.Float8
	// 备注
	Remark pgtype.Text
	// 创建时间戳
	Ctime int64
	// 更新时间戳
	Utime int64
}

// 宝宝相册表
type BabyPhoto struct {
	// 主键ID
	ID int64
	// 相片ID
	PhotoID pgtype.UUID
	// 宝宝ID(外键)
	BabyID pgtype.UUID
	// 详情页面URL
	Link string
	// 描述
	Caption pgtype.Text
	// 创建时间戳
	Ctime int64
	// 更新时间戳
	Utime int64
}

// 宝宝疫苗接种记录表
type BabyVaccineRecord struct {
	// 主键ID
	ID int64
	// 记录ID
	RecordID pgtype.UUID
	// 宝宝ID(外键)
	BabyID pgtype.UUID
	// 疫苗ID(外键)
	VaccineID pgtype.UUID
	// 应接种时间(毫秒)
	DueTime int64
	// 接种状态
	Status string
	// 实际接种时间(毫秒)
	ActualTime pgtype.Int8
	// 创建时间戳
	Ctime int64
	// 更新时间戳
	Utime int64
}

// 疫苗字典表
type Vaccine struct {
	// 主键ID
	ID int64
	// 疫苗ID
	VaccineID pgtype.UUID
	// 疫苗名称
	Name string
	// 预防疾病
	Disease string
	// 推荐接种年龄(天)
	RecommendAgeDays int32
	// 详情页面URL
	Link string
	// 创建时间戳
	Ctime int64
	// 更新时间戳
	Utime int64
}
