package baby

import (
	"nurture/internal/baby/dto"
	"nurture/internal/middleware"
	"nurture/internal/pkg/jwtx"

	"github.com/gin-gonic/gin"
)

func (m *Module) RegisterRoutes(rg *gin.RouterGroup) {
	babyHandler := m.handler

	rg.GET("/changeBaby",
		middleware.Authentication(jwtx.COMMON_USER),
		middleware.BindQueryMiddleware[dto.ChangeBabyReq],
		babyHandler.ChangeBaby,
	)
	rg.POST("/newBaby",
		middleware.Authentication(jwtx.COMMON_USER),
		middleware.BindJsonMiddleware[dto.NewBabyReq],
		babyHandler.NewBaby,
	)
	rg.POST("/growthRecords",
		middleware.Authentication(jwtx.COMMON_USER),
		middleware.BindJsonMiddleware[dto.CreateGrowthReq],
		babyHandler.CreateGrowth,
	)
	rg.GET("/growthRecord",
		middleware.Authentication(jwtx.COMMON_USER),
		middleware.BindQueryMiddleware[dto.GrowthAtReq],
		babyHandler.GetGrowthAt,
	)
	rg.GET("/growthCurve",
		middleware.Authentication(jwtx.COMMON_USER),
		middleware.BindQueryMiddleware[dto.GrowthCurveReq],
		babyHandler.GrowthCurve,
	)
	rg.POST("/:baby_id/daily/sleep/start",
		middleware.Authentication(jwtx.COMMON_USER),
		middleware.BindUriMiddleware[dto.SleepStartUri],
		babyHandler.SleepStart,
	)
	rg.POST("/:baby_id/daily/sleep/stop",
		middleware.Authentication(jwtx.COMMON_USER),
		middleware.BindUriMiddleware[dto.SleepStopUri],
		middleware.BindJsonMiddleware[dto.SleepStopReq],
		babyHandler.SleepStop,
	)
	rg.GET("/:baby_id/daily/sleep/active",
		middleware.Authentication(jwtx.COMMON_USER),
		middleware.BindUriMiddleware[dto.SleepActiveUri],
		babyHandler.SleepActive,
	)
	rg.GET("/:baby_id/daily/sleep/byDate",
		middleware.Authentication(jwtx.COMMON_USER),
		middleware.BindUriMiddleware[dto.SleepListAtUri],
		middleware.BindQueryMiddleware[dto.SleepListAtReq],
		babyHandler.ListSleepAt,
	)
	rg.POST("/:baby_id/daily/feeding",
		middleware.Authentication(jwtx.COMMON_USER),
		middleware.BindUriMiddleware[dto.FeedingCreateUri],
		middleware.BindJsonMiddleware[dto.FeedingCreateReq],
		babyHandler.CreateFeeding,
	)
	rg.PUT("/:baby_id/daily/feeding/:feeding_id",
		middleware.Authentication(jwtx.COMMON_USER),
		middleware.BindUriMiddleware[dto.FeedingUpdateUri],
		middleware.BindJsonMiddleware[dto.FeedingUpdateReq],
		babyHandler.UpdateFeeding,
	)
	rg.GET("/:baby_id/daily/feeding/byDate",
		middleware.Authentication(jwtx.COMMON_USER),
		middleware.BindUriMiddleware[dto.FeedingListAtUri],
		middleware.BindQueryMiddleware[dto.FeedingListAtReq],
		babyHandler.ListFeedingAt,
	)
	rg.POST("/:baby_id/daily/diaper",
		middleware.Authentication(jwtx.COMMON_USER),
		middleware.BindUriMiddleware[dto.DiaperCreateUri],
		middleware.BindJsonMiddleware[dto.DiaperCreateReq],
		babyHandler.CreateDiaper,
	)
	rg.PUT("/:baby_id/daily/diaper/:diaper_id",
		middleware.Authentication(jwtx.COMMON_USER),
		middleware.BindUriMiddleware[dto.DiaperUpdateUri],
		middleware.BindJsonMiddleware[dto.DiaperUpdateReq],
		babyHandler.UpdateDiaper,
	)
	rg.GET("/:baby_id/daily/diaper/byDate",
		middleware.Authentication(jwtx.COMMON_USER),
		middleware.BindUriMiddleware[dto.DiaperGetAtUri],
		middleware.BindQueryMiddleware[dto.DiaperGetAtReq],
		babyHandler.GetDiaperAt,
	)
	rg.GET("/:baby_id/daily/diaper/byDate/list",
		middleware.Authentication(jwtx.COMMON_USER),
		middleware.BindUriMiddleware[dto.DiaperListAtUri],
		middleware.BindQueryMiddleware[dto.DiaperListAtReq],
		babyHandler.ListDiaperAt,
	)
	rg.GET("/:baby_id/daily/stats/byDate",
		middleware.Authentication(jwtx.COMMON_USER),
		middleware.BindUriMiddleware[dto.DailyStatsUri],
		middleware.BindQueryMiddleware[dto.DailyStatsReq],
		babyHandler.DailyStats,
	)
	rg.GET("/profile",
		middleware.Authentication(jwtx.COMMON_USER),
		middleware.BindQueryMiddleware[dto.BabyProfileReq],
		babyHandler.GetProfile,
	)
	rg.GET("/vaccine/getVaccineList",
		middleware.Authentication(jwtx.COMMON_USER),
		middleware.BindQueryMiddleware[dto.GetVaccineListReq],
		babyHandler.GetVaccineList,
	)
	rg.PUT("/vaccine/changeStatus",
		middleware.Authentication(jwtx.COMMON_USER),
		middleware.BindJsonMiddleware[dto.ChangeVaccineStatusReq],
		babyHandler.ChangeVaccineStatus,
	)
	rg.POST("/photo/upload",
		middleware.Authentication(jwtx.COMMON_USER),
		middleware.BindJsonMiddleware[dto.UploadBabyPhotosReq],
		babyHandler.UploadBabyPhotos,
	)
	rg.DELETE("/photo/delete",
		middleware.Authentication(jwtx.COMMON_USER),
		middleware.BindJsonMiddleware[dto.DeleteBabyPhotosReq],
		babyHandler.DeleteBabyPhotos,
	)
	rg.GET("/photo/list",
		middleware.Authentication(jwtx.COMMON_USER),
		middleware.BindQueryMiddleware[dto.ListBabyPhotosReq],
		babyHandler.ListBabyPhotos,
	)
}

func (m *Module) RegisterAdminRoutes(rg *gin.RouterGroup) {
	rg.POST("/vaccines",
		middleware.Authentication(jwtx.ADMIN),
		middleware.BindJsonMiddleware[dto.AdminCreateVaccineReq],
		m.handler.AdminCreateVaccine,
	)
}
