// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package user

import (
	"github.com/jackc/pgx/v5/pgtype"
)

// 用户表
type User struct {
	// 主键ID
	ID int64
	// 用户ID
	UserID pgtype.UUID
	// 创建时间
	Ctime int64
	// 更新时间
	Utime int64
	// 账号
	Account string
	// 密码
	Password string
	// 邮箱
	Email string
	// 用户名
	Username string
	// 头像
	Avatar string
	// 角色
	Role int16
}
