// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user.sql

package user

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :exec
INSERT INTO "user" (
  user_id, ctime, utime, account, password, email, username, avatar, role
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8, $9
)
`

type CreateUserParams struct {
	UserID   pgtype.UUID
	Ctime    int64
	Utime    int64
	Account  pgtype.Text
	Password string
	Email    pgtype.Text
	Username string
	Avatar   string
	Role     int16
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.Exec(ctx, createUser,
		arg.UserID,
		arg.Ctime,
		arg.Utime,
		arg.Account,
		arg.Password,
		arg.Email,
		arg.Username,
		arg.Avatar,
		arg.Role,
	)
	return err
}

const getUserByAccountAndPassword = `-- name: GetUserByAccountAndPassword :one
SELECT id, user_id, ctime, utime, account, password, email, username, avatar, role FROM "user"
WHERE account = $1 AND password = $2 LIMIT 1
`

type GetUserByAccountAndPasswordParams struct {
	Account  pgtype.Text
	Password string
}

func (q *Queries) GetUserByAccountAndPassword(ctx context.Context, arg GetUserByAccountAndPasswordParams) (User, error) {
	row := q.db.QueryRow(ctx, getUserByAccountAndPassword, arg.Account, arg.Password)
	var i User
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Ctime,
		&i.Utime,
		&i.Account,
		&i.Password,
		&i.Email,
		&i.Username,
		&i.Avatar,
		&i.Role,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, user_id, ctime, utime, account, password, email, username, avatar, role FROM "user"
WHERE email = $1 LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email pgtype.Text) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Ctime,
		&i.Utime,
		&i.Account,
		&i.Password,
		&i.Email,
		&i.Username,
		&i.Avatar,
		&i.Role,
	)
	return i, err
}

const updateAvatarByUserID = `-- name: UpdateAvatarByUserID :execrows
UPDATE "user"
SET avatar = $2
WHERE user_id = $1
`

type UpdateAvatarByUserIDParams struct {
	UserID pgtype.UUID
	Avatar string
}

func (q *Queries) UpdateAvatarByUserID(ctx context.Context, arg UpdateAvatarByUserIDParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateAvatarByUserID, arg.UserID, arg.Avatar)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updatePasswordByEmail = `-- name: UpdatePasswordByEmail :execrows
UPDATE "user"
SET password = $2
WHERE email = $1
`

type UpdatePasswordByEmailParams struct {
	Email    pgtype.Text
	Password string
}

func (q *Queries) UpdatePasswordByEmail(ctx context.Context, arg UpdatePasswordByEmailParams) (int64, error) {
	result, err := q.db.Exec(ctx, updatePasswordByEmail, arg.Email, arg.Password)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
