// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user.sql

package user

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :exec
WITH ins AS (
  INSERT INTO "user_base" (
    user_id, ctime, utime, account, password, email, username, gender, role
  ) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, 1
  )
  RETURNING user_id, username, gender, ctime, utime
)
INSERT INTO "user_addition" (
  user_id, username, gender, phone, occupation, birthday, avatar, province, city, ctime, utime
) SELECT
  user_id, username, gender, '', '', 0, '', '', '', ctime, utime
FROM ins
`

type CreateUserParams struct {
	UserID   pgtype.UUID
	Ctime    int64
	Utime    int64
	Account  string
	Password string
	Email    string
	Username string
	Gender   string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.Exec(ctx, createUser,
		arg.UserID,
		arg.Ctime,
		arg.Utime,
		arg.Account,
		arg.Password,
		arg.Email,
		arg.Username,
		arg.Gender,
	)
	return err
}

const getUserByAccountAndPassword = `-- name: GetUserByAccountAndPassword :one
SELECT id, user_id, account, password, email, username, gender, role, ctime, utime FROM "user_base"
WHERE account = $1 AND password = $2 LIMIT 1
`

type GetUserByAccountAndPasswordParams struct {
	Account  string
	Password string
}

func (q *Queries) GetUserByAccountAndPassword(ctx context.Context, arg GetUserByAccountAndPasswordParams) (UserBase, error) {
	row := q.db.QueryRow(ctx, getUserByAccountAndPassword, arg.Account, arg.Password)
	var i UserBase
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Account,
		&i.Password,
		&i.Email,
		&i.Username,
		&i.Gender,
		&i.Role,
		&i.Ctime,
		&i.Utime,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, user_id, account, password, email, username, gender, role, ctime, utime FROM "user_base"
WHERE email = $1 LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (UserBase, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i UserBase
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Account,
		&i.Password,
		&i.Email,
		&i.Username,
		&i.Gender,
		&i.Role,
		&i.Ctime,
		&i.Utime,
	)
	return i, err
}

const updateAvatarByUserID = `-- name: UpdateAvatarByUserID :execrows
UPDATE "user_addition"
SET avatar = $2
WHERE user_id = $1
`

type UpdateAvatarByUserIDParams struct {
	UserID pgtype.UUID
	Avatar string
}

func (q *Queries) UpdateAvatarByUserID(ctx context.Context, arg UpdateAvatarByUserIDParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateAvatarByUserID, arg.UserID, arg.Avatar)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createPartner = `-- name: CreatePartner :exec
INSERT INTO "user_partner"(father, mother, ctime, utime)
VALUES ($1, $2, $3, $3)
ON CONFLICT (father, mother) DO NOTHING
`

type CreatePartnerParams struct {
	Father pgtype.UUID
	Mother pgtype.UUID
	Ctime  int64
}

func (q *Queries) CreatePartner(ctx context.Context, arg CreatePartnerParams) error {
	_, err := q.db.Exec(ctx, createPartner, arg.Father, arg.Mother, arg.Ctime)
	return err
}

const getPartnerByUserID = `-- name: GetPartnerByUserID :one
SELECT father::text AS father, mother::text AS mother
FROM "user_partner"
WHERE father = $1 OR mother = $1
LIMIT 1
`

type GetPartnerByUserIDRow struct {
	Father string
	Mother string
}

func (q *Queries) GetPartnerByUserID(ctx context.Context, userID string) (GetPartnerByUserIDRow, error) {
	row := q.db.QueryRow(ctx, getPartnerByUserID, userID)
	var i GetPartnerByUserIDRow
	err := row.Scan(&i.Father, &i.Mother)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, user_id, account, password, email, username, gender, role, ctime, utime FROM "user_base" WHERE user_id = $1 LIMIT 1
`

func (q *Queries) GetUserByID(ctx context.Context, userID pgtype.UUID) (UserBase, error) {
	row := q.db.QueryRow(ctx, getUserByID, userID)
	var i UserBase
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Account,
		&i.Password,
		&i.Email,
		&i.Username,
		&i.Gender,
		&i.Role,
		&i.Ctime,
		&i.Utime,
	)
	return i, err
}

const updatePasswordByEmail = `-- name: UpdatePasswordByEmail :execrows
UPDATE "user_base"
SET password = $2
WHERE email = $1
`

type UpdatePasswordByEmailParams struct {
	Email    string
	Password string
}

func (q *Queries) UpdatePasswordByEmail(ctx context.Context, arg UpdatePasswordByEmailParams) (int64, error) {
	result, err := q.db.Exec(ctx, updatePasswordByEmail, arg.Email, arg.Password)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateUserAdditionByUserID = `-- name: UpdateUserAdditionByUserID :execrows
UPDATE "user_addition"
SET
  occupation = COALESCE(NULLIF($2, ''), occupation),
  phone      = COALESCE(NULLIF($3, ''), phone),
  province   = COALESCE(NULLIF($4, ''), province),
  city       = COALESCE(NULLIF($5, ''), city),
  avatar     = COALESCE(NULLIF($6, ''), avatar),
  birthday   = COALESCE(NULLIF($7::BIGINT, -1), birthday),
  utime      = $8
WHERE user_id = $1
`

type UpdateUserAdditionByUserIDParams struct {
	UserID  pgtype.UUID
	Column2 interface{}
	Column3 interface{}
	Column4 interface{}
	Column5 interface{}
	Column6 interface{}
	Column7 int64
	Utime   int64
}

func (q *Queries) UpdateUserAdditionByUserID(ctx context.Context, arg UpdateUserAdditionByUserIDParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateUserAdditionByUserID,
		arg.UserID,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Column5,
		arg.Column6,
		arg.Column7,
		arg.Utime,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateGenderByUserID = `-- name: UpdateGenderByUserID :execrows
UPDATE "user_addition"
SET gender = $2, utime = $3
WHERE user_id = $1
`

type UpdateGenderByUserIDParams struct {
	UserID pgtype.UUID
	Gender string
	Utime  int64
}

func (q *Queries) UpdateGenderByUserID(ctx context.Context, arg UpdateGenderByUserIDParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateGenderByUserID, arg.UserID, arg.Gender, arg.Utime)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateBaseGenderByUserID = `-- name: UpdateBaseGenderByUserID :execrows
UPDATE "user_base"
SET gender = $2, utime = $3
WHERE user_id = $1
`

type UpdateBaseGenderByUserIDParams struct {
	UserID pgtype.UUID
	Gender string
	Utime  int64
}

func (q *Queries) UpdateBaseGenderByUserID(ctx context.Context, arg UpdateBaseGenderByUserIDParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateBaseGenderByUserID, arg.UserID, arg.Gender, arg.Utime)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
