services:
  # App Service (Defined for future use)
  nurture-api:
    build:
      context: ..
      dockerfile: deploy/Dockerfile
    container_name: nurture-api
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - nurture-net
    volumes:
      - ../internal/etc/local.yaml:/app/internal/etc/local.yaml
      - ../logs:/app/logs

  # PostgreSQL with pgvector
  postgres:
    container_name: nurture-pg
    image: pgvector/pgvector:pg16
    environment:
      - POSTGRES_USER=nurture
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=nurture
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./schema:/docker-entrypoint-initdb.d
    networks:
      - nurture-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U nurture -d nurture"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Redis
  redis:
    container_name: nurture-redis
    image: redis:7-alpine
    restart: always
    networks:
      - nurture-net
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  # RabbitMQ
  rabbitmq:
    container_name: nurture-rabbitmq
    image: rabbitmq:3.13-management
    environment:
      - RABBITMQ_DEFAULT_USER=nurture
      - RABBITMQ_DEFAULT_PASS=123456
    restart: always
    ports:
      - "15672:15672"
    networks:
      - nurture-net
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 5s
      timeout: 5s
      retries: 10

networks:
  nurture-net:
    driver: bridge

volumes:
  pgdata:
