// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: post.sql

package postdao

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addPostTag = `-- name: AddPostTag :exec
INSERT INTO "post_tag" (post_id, tag_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AddPostTagParams struct {
	PostID pgtype.UUID
	TagID  pgtype.UUID
}

func (q *Queries) AddPostTag(ctx context.Context, arg AddPostTagParams) error {
	_, err := q.db.Exec(ctx, addPostTag, arg.PostID, arg.TagID)
	return err
}

const createPost = `-- name: CreatePost :exec
INSERT INTO "post" (
  post_id, author_id, title, content, status,
  like_count, dislike_count, collect_count, comment_count,
  cover, ctime, utime
) VALUES (
  $1, $2, $3, $4, $5,
  0, 0, 0, 0,
  $6, $7, $8
)
`

type CreatePostParams struct {
	PostID   pgtype.UUID
	AuthorID pgtype.UUID
	Title    string
	Content  string
	Status   string
	Cover    string
	Ctime    int64
	Utime    int64
}

func (q *Queries) CreatePost(ctx context.Context, arg CreatePostParams) error {
	_, err := q.db.Exec(ctx, createPost,
		arg.PostID,
		arg.AuthorID,
		arg.Title,
		arg.Content,
		arg.Status,
		arg.Cover,
		arg.Ctime,
		arg.Utime,
	)
	return err
}

const getPostDetail = `-- name: GetPostDetail :one
SELECT
  p.post_id::text AS post_id,
  p.author_id::text AS author_id,
  COALESCE(ua.username, '') AS author_name,
  COALESCE(ua.avatar, '') AS author_avatar,
  COALESCE(ua.province, '') AS author_province,
  COALESCE(ua.city, '') AS author_city,
  p.title, p.content, p.status,
  p.like_count, p.dislike_count, p.collect_count, p.comment_count,
  p.cover, p.ctime, p.utime,
  COALESCE((
    SELECT b.birthday
    FROM "baby" b
    WHERE b.user_id = p.author_id
    ORDER BY b.ctime DESC
    LIMIT 1
  ), 0) AS birthday,
  COALESCE((
    SELECT array_agg(t.tag_name) FILTER (WHERE t.tag_name IS NOT NULL)
    FROM "post_tag" pt
    JOIN "tag" t ON t.tag_id = pt.tag_id
    WHERE pt.post_id = p.post_id
  ), '{}') AS tags
FROM "post" p
LEFT JOIN "user_addition" ua ON ua.user_id = p.author_id
WHERE p.post_id = $1
`

type GetPostDetailRow struct {
	PostID         string
	AuthorID       string
	AuthorName     string
	AuthorAvatar   string
	AuthorProvince string
	AuthorCity     string
	Title          string
	Content        string
	Status         string
	LikeCount      int32
	DislikeCount   int32
	CollectCount   int32
	CommentCount   int32
	Cover          string
	Ctime          int64
	Utime          int64
	Birthday       interface{}
	Tags           interface{}
}

func (q *Queries) GetPostDetail(ctx context.Context, postID pgtype.UUID) (GetPostDetailRow, error) {
	row := q.db.QueryRow(ctx, getPostDetail, postID)
	var i GetPostDetailRow
	err := row.Scan(
		&i.PostID,
		&i.AuthorID,
		&i.AuthorName,
		&i.AuthorAvatar,
		&i.AuthorProvince,
		&i.AuthorCity,
		&i.Title,
		&i.Content,
		&i.Status,
		&i.LikeCount,
		&i.DislikeCount,
		&i.CollectCount,
		&i.CommentCount,
		&i.Cover,
		&i.Ctime,
		&i.Utime,
		&i.Birthday,
		&i.Tags,
	)
	return i, err
}

const listDraftsByAuthor = `-- name: ListDraftsByAuthor :many
SELECT
  p.post_id::text AS post_id,
  p.author_id::text AS author_id,
  COALESCE(ua.username, '') AS author_name,
  COALESCE(ua.avatar, '') AS author_avatar,
  COALESCE(ua.province, '') AS author_province,
  COALESCE(ua.city, '') AS author_city,
  p.title, p.content, p.status,
  p.like_count, p.dislike_count, p.collect_count, p.comment_count,
  p.cover, p.ctime, p.utime,
  COALESCE((
    SELECT b.birthday
    FROM "baby" b
    WHERE b.user_id = p.author_id
    ORDER BY b.ctime DESC
    LIMIT 1
  ), 0) AS birthday,
  COALESCE((
    SELECT array_agg(t.tag_name) FILTER (WHERE t.tag_name IS NOT NULL)
    FROM "post_tag" pt2
    JOIN "tag" t ON t.tag_id = pt2.tag_id
    WHERE pt2.post_id = p.post_id
  ), '{}') AS tags
FROM "post" p
LEFT JOIN "user_addition" ua ON ua.user_id = p.author_id
WHERE p.author_id = $1 AND p.status = 'draft'
ORDER BY p.ctime DESC
LIMIT $2 OFFSET $3
`

type ListDraftsByAuthorParams struct {
	AuthorID pgtype.UUID
	Limit    int32
	Offset   int32
}

type ListDraftsByAuthorRow struct {
	PostID         string
	AuthorID       string
	AuthorName     string
	AuthorAvatar   string
	AuthorProvince string
	AuthorCity     string
	Title          string
	Content        string
	Status         string
	LikeCount      int32
	DislikeCount   int32
	CollectCount   int32
	CommentCount   int32
	Cover          string
	Ctime          int64
	Utime          int64
	Birthday       interface{}
	Tags           interface{}
}

func (q *Queries) ListDraftsByAuthor(ctx context.Context, arg ListDraftsByAuthorParams) ([]ListDraftsByAuthorRow, error) {
	rows, err := q.db.Query(ctx, listDraftsByAuthor, arg.AuthorID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDraftsByAuthorRow
	for rows.Next() {
		var i ListDraftsByAuthorRow
		if err := rows.Scan(
			&i.PostID,
			&i.AuthorID,
			&i.AuthorName,
			&i.AuthorAvatar,
			&i.AuthorProvince,
			&i.AuthorCity,
			&i.Title,
			&i.Content,
			&i.Status,
			&i.LikeCount,
			&i.DislikeCount,
			&i.CollectCount,
			&i.CommentCount,
			&i.Cover,
			&i.Ctime,
			&i.Utime,
			&i.Birthday,
			&i.Tags,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHomeByCtime = `-- name: ListHomeByCtime :many
SELECT
  p.post_id::text AS post_id,
  p.author_id::text AS author_id,
  COALESCE(ua.username, '') AS author_name,
  COALESCE(ua.avatar, '') AS author_avatar,
  COALESCE(ua.province, '') AS author_province,
  COALESCE(ua.city, '') AS author_city,
  p.title, p.content, p.status,
  p.like_count, p.dislike_count, p.collect_count, p.comment_count,
  p.cover, p.ctime, p.utime,
  COALESCE((
    SELECT b.birthday
    FROM "baby" b
    WHERE b.user_id = p.author_id
    ORDER BY b.ctime DESC
    LIMIT 1
  ), 0) AS birthday,
  COALESCE((
    SELECT array_agg(t.tag_name) FILTER (WHERE t.tag_name IS NOT NULL)
    FROM "post_tag" pt
    JOIN "tag" t ON t.tag_id = pt.tag_id
    WHERE pt.post_id = p.post_id
  ), '{}') AS tags
FROM "post" p
LEFT JOIN "user_addition" ua ON ua.user_id = p.author_id
WHERE p.status = 'published'
ORDER BY p.ctime DESC
LIMIT $1 OFFSET $2
`

type ListHomeByCtimeParams struct {
	Limit  int32
	Offset int32
}

type ListHomeByCtimeRow struct {
	PostID         string
	AuthorID       string
	AuthorName     string
	AuthorAvatar   string
	AuthorProvince string
	AuthorCity     string
	Title          string
	Content        string
	Status         string
	LikeCount      int32
	DislikeCount   int32
	CollectCount   int32
	CommentCount   int32
	Cover          string
	Ctime          int64
	Utime          int64
	Birthday       interface{}
	Tags           interface{}
}

func (q *Queries) ListHomeByCtime(ctx context.Context, arg ListHomeByCtimeParams) ([]ListHomeByCtimeRow, error) {
	rows, err := q.db.Query(ctx, listHomeByCtime, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListHomeByCtimeRow
	for rows.Next() {
		var i ListHomeByCtimeRow
		if err := rows.Scan(
			&i.PostID,
			&i.AuthorID,
			&i.AuthorName,
			&i.AuthorAvatar,
			&i.AuthorProvince,
			&i.AuthorCity,
			&i.Title,
			&i.Content,
			&i.Status,
			&i.LikeCount,
			&i.DislikeCount,
			&i.CollectCount,
			&i.CommentCount,
			&i.Cover,
			&i.Ctime,
			&i.Utime,
			&i.Birthday,
			&i.Tags,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHomeByHot = `-- name: ListHomeByHot :many
SELECT
  p.post_id::text AS post_id,
  p.author_id::text AS author_id,
  COALESCE(ua.username, '') AS author_name,
  COALESCE(ua.avatar, '') AS author_avatar,
  COALESCE(ua.province, '') AS author_province,
  COALESCE(ua.city, '') AS author_city,
  p.title, p.content, p.status,
  p.like_count, p.dislike_count, p.collect_count, p.comment_count,
  p.cover, p.ctime, p.utime,
  COALESCE((
    SELECT b.birthday
    FROM "baby" b
    WHERE b.user_id = p.author_id
    ORDER BY b.ctime DESC
    LIMIT 1
  ), 0) AS birthday,
  COALESCE((
    SELECT array_agg(t.tag_name) FILTER (WHERE t.tag_name IS NOT NULL)
    FROM "post_tag" pt
    JOIN "tag" t ON t.tag_id = pt.tag_id
    WHERE pt.post_id = p.post_id
  ), '{}') AS tags
FROM "post" p
LEFT JOIN "user_addition" ua ON ua.user_id = p.author_id
WHERE p.status = 'published'
ORDER BY (p.like_count*3 + p.comment_count*5 + p.collect_count*4) DESC, p.ctime DESC
LIMIT $1 OFFSET $2
`

type ListHomeByHotParams struct {
	Limit  int32
	Offset int32
}

type ListHomeByHotRow struct {
	PostID         string
	AuthorID       string
	AuthorName     string
	AuthorAvatar   string
	AuthorProvince string
	AuthorCity     string
	Title          string
	Content        string
	Status         string
	LikeCount      int32
	DislikeCount   int32
	CollectCount   int32
	CommentCount   int32
	Cover          string
	Ctime          int64
	Utime          int64
	Birthday       interface{}
	Tags           interface{}
}

func (q *Queries) ListHomeByHot(ctx context.Context, arg ListHomeByHotParams) ([]ListHomeByHotRow, error) {
	rows, err := q.db.Query(ctx, listHomeByHot, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListHomeByHotRow
	for rows.Next() {
		var i ListHomeByHotRow
		if err := rows.Scan(
			&i.PostID,
			&i.AuthorID,
			&i.AuthorName,
			&i.AuthorAvatar,
			&i.AuthorProvince,
			&i.AuthorCity,
			&i.Title,
			&i.Content,
			&i.Status,
			&i.LikeCount,
			&i.DislikeCount,
			&i.CollectCount,
			&i.CommentCount,
			&i.Cover,
			&i.Ctime,
			&i.Utime,
			&i.Birthday,
			&i.Tags,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHomeByRandom = `-- name: ListHomeByRandom :many
SELECT
  p.post_id::text AS post_id,
  p.author_id::text AS author_id,
  COALESCE(ua.username, '') AS author_name,
  COALESCE(ua.avatar, '') AS author_avatar,
  COALESCE(ua.province, '') AS author_province,
  COALESCE(ua.city, '') AS author_city,
  p.title, p.content, p.status,
  p.like_count, p.dislike_count, p.collect_count, p.comment_count,
  p.cover, p.ctime, p.utime,
  COALESCE((
    SELECT b.birthday
    FROM "baby" b
    WHERE b.user_id = p.author_id
    ORDER BY b.ctime DESC
    LIMIT 1
  ), 0) AS birthday,
  COALESCE((
    SELECT array_agg(t.tag_name) FILTER (WHERE t.tag_name IS NOT NULL)
    FROM "post_tag" pt
    JOIN "tag" t ON t.tag_id = pt.tag_id
    WHERE pt.post_id = p.post_id
  ), '{}') AS tags
FROM "post" p
LEFT JOIN "user_addition" ua ON ua.user_id = p.author_id
WHERE p.status = 'published'
ORDER BY md5(p.post_id::text || ($1)::text)
LIMIT $2 OFFSET $3
`

type ListHomeByRandomParams struct {
	Column1 string
	Limit   int32
	Offset  int32
}

type ListHomeByRandomRow struct {
	PostID         string
	AuthorID       string
	AuthorName     string
	AuthorAvatar   string
	AuthorProvince string
	AuthorCity     string
	Title          string
	Content        string
	Status         string
	LikeCount      int32
	DislikeCount   int32
	CollectCount   int32
	CommentCount   int32
	Cover          string
	Ctime          int64
	Utime          int64
	Birthday       interface{}
	Tags           interface{}
}

func (q *Queries) ListHomeByRandom(ctx context.Context, arg ListHomeByRandomParams) ([]ListHomeByRandomRow, error) {
	rows, err := q.db.Query(ctx, listHomeByRandom, arg.Column1, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListHomeByRandomRow
	for rows.Next() {
		var i ListHomeByRandomRow
		if err := rows.Scan(
			&i.PostID,
			&i.AuthorID,
			&i.AuthorName,
			&i.AuthorAvatar,
			&i.AuthorProvince,
			&i.AuthorCity,
			&i.Title,
			&i.Content,
			&i.Status,
			&i.LikeCount,
			&i.DislikeCount,
			&i.CollectCount,
			&i.CommentCount,
			&i.Cover,
			&i.Ctime,
			&i.Utime,
			&i.Birthday,
			&i.Tags,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHomePosts = `-- name: ListHomePosts :many
SELECT
  p.post_id::text AS post_id,
  p.author_id::text AS author_id,
  COALESCE(ua.username, '') AS author_name,
  COALESCE(ua.avatar, '') AS author_avatar,
  COALESCE(ua.province, '') AS author_province,
  COALESCE(ua.city, '') AS author_city,
  p.title, p.content, p.status,
  p.like_count, p.dislike_count, p.collect_count, p.comment_count,
  p.cover, p.ctime, p.utime,
  COALESCE((
    SELECT b.birthday
    FROM "baby" b
    WHERE b.user_id = p.author_id
    ORDER BY b.ctime DESC
    LIMIT 1
  ), 0) AS birthday,
  COALESCE((
    SELECT array_agg(t.tag_name) FILTER (WHERE t.tag_name IS NOT NULL)
    FROM "post_tag" pt
    JOIN "tag" t ON t.tag_id = pt.tag_id
    WHERE pt.post_id = p.post_id
  ), '{}') AS tags
FROM "post" p
LEFT JOIN "user_addition" ua ON ua.user_id = p.author_id
WHERE p.status = $1
ORDER BY 
  CASE WHEN $2 = 'hot' THEN (p.like_count*3 + p.comment_count*5 + p.collect_count*4) ELSE p.ctime END DESC,
  p.ctime DESC
LIMIT $3 OFFSET $4
`

type ListHomePostsParams struct {
	Status  string
	Column2 interface{}
	Limit   int32
	Offset  int32
}

type ListHomePostsRow struct {
	PostID         string
	AuthorID       string
	AuthorName     string
	AuthorAvatar   string
	AuthorProvince string
	AuthorCity     string
	Title          string
	Content        string
	Status         string
	LikeCount      int32
	DislikeCount   int32
	CollectCount   int32
	CommentCount   int32
	Cover          string
	Ctime          int64
	Utime          int64
	Birthday       interface{}
	Tags           interface{}
}

func (q *Queries) ListHomePosts(ctx context.Context, arg ListHomePostsParams) ([]ListHomePostsRow, error) {
	rows, err := q.db.Query(ctx, listHomePosts,
		arg.Status,
		arg.Column2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListHomePostsRow
	for rows.Next() {
		var i ListHomePostsRow
		if err := rows.Scan(
			&i.PostID,
			&i.AuthorID,
			&i.AuthorName,
			&i.AuthorAvatar,
			&i.AuthorProvince,
			&i.AuthorCity,
			&i.Title,
			&i.Content,
			&i.Status,
			&i.LikeCount,
			&i.DislikeCount,
			&i.CollectCount,
			&i.CommentCount,
			&i.Cover,
			&i.Ctime,
			&i.Utime,
			&i.Birthday,
			&i.Tags,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPostsByAuthor = `-- name: ListPostsByAuthor :many
SELECT
  p.post_id::text AS post_id,
  p.author_id::text AS author_id,
  COALESCE(ua.username, '') AS author_name,
  COALESCE(ua.avatar, '') AS author_avatar,
  COALESCE(ua.province, '') AS author_province,
  COALESCE(ua.city, '') AS author_city,
  p.title, p.content, p.status,
  p.like_count, p.dislike_count, p.collect_count, p.comment_count,
  p.cover, p.ctime, p.utime,
  COALESCE((
    SELECT b.birthday
    FROM "baby" b
    WHERE b.user_id = p.author_id
    ORDER BY b.ctime DESC
    LIMIT 1
  ), 0) AS birthday,
  COALESCE((
    SELECT array_agg(t.tag_name) FILTER (WHERE t.tag_name IS NOT NULL)
    FROM "post_tag" pt2
    JOIN "tag" t ON t.tag_id = pt2.tag_id
    WHERE pt2.post_id = p.post_id
  ), '{}') AS tags
FROM "post" p
LEFT JOIN "user_addition" ua ON ua.user_id = p.author_id
WHERE p.author_id = $1 AND p.status = 'published'
ORDER BY p.ctime DESC
LIMIT $2 OFFSET $3
`

type ListPostsByAuthorParams struct {
	AuthorID pgtype.UUID
	Limit    int32
	Offset   int32
}

type ListPostsByAuthorRow struct {
	PostID         string
	AuthorID       string
	AuthorName     string
	AuthorAvatar   string
	AuthorProvince string
	AuthorCity     string
	Title          string
	Content        string
	Status         string
	LikeCount      int32
	DislikeCount   int32
	CollectCount   int32
	CommentCount   int32
	Cover          string
	Ctime          int64
	Utime          int64
	Birthday       interface{}
	Tags           interface{}
}

func (q *Queries) ListPostsByAuthor(ctx context.Context, arg ListPostsByAuthorParams) ([]ListPostsByAuthorRow, error) {
	rows, err := q.db.Query(ctx, listPostsByAuthor, arg.AuthorID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPostsByAuthorRow
	for rows.Next() {
		var i ListPostsByAuthorRow
		if err := rows.Scan(
			&i.PostID,
			&i.AuthorID,
			&i.AuthorName,
			&i.AuthorAvatar,
			&i.AuthorProvince,
			&i.AuthorCity,
			&i.Title,
			&i.Content,
			&i.Status,
			&i.LikeCount,
			&i.DislikeCount,
			&i.CollectCount,
			&i.CommentCount,
			&i.Cover,
			&i.Ctime,
			&i.Utime,
			&i.Birthday,
			&i.Tags,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPostsByAuthorHot = `-- name: ListPostsByAuthorHot :many
SELECT
  p.post_id::text AS post_id,
  p.author_id::text AS author_id,
  COALESCE(ua.username, '') AS author_name,
  COALESCE(ua.avatar, '') AS author_avatar,
  COALESCE(ua.province, '') AS author_province,
  COALESCE(ua.city, '') AS author_city,
  p.title, p.content, p.status,
  p.like_count, p.dislike_count, p.collect_count, p.comment_count,
  p.cover, p.ctime, p.utime,
  COALESCE((
    SELECT b.birthday
    FROM "baby" b
    WHERE b.user_id = p.author_id
    ORDER BY b.ctime DESC
    LIMIT 1
  ), 0) AS birthday,
  COALESCE((
    SELECT array_agg(t.tag_name) FILTER (WHERE t.tag_name IS NOT NULL)
    FROM "post_tag" pt2
    JOIN "tag" t ON t.tag_id = pt2.tag_id
    WHERE pt2.post_id = p.post_id
  ), '{}') AS tags
FROM "post" p
LEFT JOIN "user_addition" ua ON ua.user_id = p.author_id
WHERE p.author_id = $1 AND p.status = 'published'
ORDER BY (p.like_count*3 + p.comment_count*5 + p.collect_count*4) DESC, p.ctime DESC
LIMIT $2 OFFSET $3
`

type ListPostsByAuthorHotParams struct {
	AuthorID pgtype.UUID
	Limit    int32
	Offset   int32
}

type ListPostsByAuthorHotRow struct {
	PostID         string
	AuthorID       string
	AuthorName     string
	AuthorAvatar   string
	AuthorProvince string
	AuthorCity     string
	Title          string
	Content        string
	Status         string
	LikeCount      int32
	DislikeCount   int32
	CollectCount   int32
	CommentCount   int32
	Cover          string
	Ctime          int64
	Utime          int64
	Birthday       interface{}
	Tags           interface{}
}

func (q *Queries) ListPostsByAuthorHot(ctx context.Context, arg ListPostsByAuthorHotParams) ([]ListPostsByAuthorHotRow, error) {
	rows, err := q.db.Query(ctx, listPostsByAuthorHot, arg.AuthorID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPostsByAuthorHotRow
	for rows.Next() {
		var i ListPostsByAuthorHotRow
		if err := rows.Scan(
			&i.PostID,
			&i.AuthorID,
			&i.AuthorName,
			&i.AuthorAvatar,
			&i.AuthorProvince,
			&i.AuthorCity,
			&i.Title,
			&i.Content,
			&i.Status,
			&i.LikeCount,
			&i.DislikeCount,
			&i.CollectCount,
			&i.CommentCount,
			&i.Cover,
			&i.Ctime,
			&i.Utime,
			&i.Birthday,
			&i.Tags,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPostsByTag = `-- name: ListPostsByTag :many
SELECT
  p.post_id::text AS post_id,
  p.author_id::text AS author_id,
  COALESCE(ua.username, '') AS author_name,
  COALESCE(ua.avatar, '') AS author_avatar,
  COALESCE(ua.province, '') AS author_province,
  COALESCE(ua.city, '') AS author_city,
  p.title, p.content, p.status,
  p.like_count, p.dislike_count, p.collect_count, p.comment_count,
  p.cover, p.ctime, p.utime,
  COALESCE((
    SELECT b.birthday
    FROM "baby" b
    WHERE b.user_id = p.author_id
    ORDER BY b.ctime DESC
    LIMIT 1
  ), 0) AS birthday,
  COALESCE((
    SELECT array_agg(t.tag_name) FILTER (WHERE t.tag_name IS NOT NULL)
    FROM "post_tag" pt2
    JOIN "tag" t ON t.tag_id = pt2.tag_id
    WHERE pt2.post_id = p.post_id
  ), '{}') AS tags
FROM "post" p
JOIN "post_tag" pt ON pt.post_id = p.post_id
LEFT JOIN "user_addition" ua ON ua.user_id = p.author_id
WHERE pt.tag_id = $1 AND p.status = $2
ORDER BY p.ctime DESC
LIMIT $3 OFFSET $4
`

type ListPostsByTagParams struct {
	TagID  pgtype.UUID
	Status string
	Limit  int32
	Offset int32
}

type ListPostsByTagRow struct {
	PostID         string
	AuthorID       string
	AuthorName     string
	AuthorAvatar   string
	AuthorProvince string
	AuthorCity     string
	Title          string
	Content        string
	Status         string
	LikeCount      int32
	DislikeCount   int32
	CollectCount   int32
	CommentCount   int32
	Cover          string
	Ctime          int64
	Utime          int64
	Birthday       interface{}
	Tags           interface{}
}

func (q *Queries) ListPostsByTag(ctx context.Context, arg ListPostsByTagParams) ([]ListPostsByTagRow, error) {
	rows, err := q.db.Query(ctx, listPostsByTag,
		arg.TagID,
		arg.Status,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPostsByTagRow
	for rows.Next() {
		var i ListPostsByTagRow
		if err := rows.Scan(
			&i.PostID,
			&i.AuthorID,
			&i.AuthorName,
			&i.AuthorAvatar,
			&i.AuthorProvince,
			&i.AuthorCity,
			&i.Title,
			&i.Content,
			&i.Status,
			&i.LikeCount,
			&i.DislikeCount,
			&i.CollectCount,
			&i.CommentCount,
			&i.Cover,
			&i.Ctime,
			&i.Utime,
			&i.Birthday,
			&i.Tags,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPostsByTagHot = `-- name: ListPostsByTagHot :many
SELECT
  p.post_id::text AS post_id,
  p.author_id::text AS author_id,
  COALESCE(ua.username, '') AS author_name,
  COALESCE(ua.avatar, '') AS author_avatar,
  COALESCE(ua.province, '') AS author_province,
  COALESCE(ua.city, '') AS author_city,
  p.title, p.content, p.status,
  p.like_count, p.dislike_count, p.collect_count, p.comment_count,
  p.cover, p.ctime, p.utime,
  COALESCE((
    SELECT b.birthday
    FROM "baby" b
    WHERE b.user_id = p.author_id
    ORDER BY b.ctime DESC
    LIMIT 1
  ), 0) AS birthday,
  COALESCE((
    SELECT array_agg(t.tag_name) FILTER (WHERE t.tag_name IS NOT NULL)
    FROM "post_tag" pt2
    JOIN "tag" t ON t.tag_id = pt2.tag_id
    WHERE pt2.post_id = p.post_id
  ), '{}') AS tags
FROM "post" p
JOIN "post_tag" pt ON pt.post_id = p.post_id
LEFT JOIN "user_addition" ua ON ua.user_id = p.author_id
WHERE pt.tag_id = $1 AND p.status = 'published'
ORDER BY (p.like_count*3 + p.comment_count*5 + p.collect_count*4) DESC, p.ctime DESC
LIMIT $2 OFFSET $3
`

type ListPostsByTagHotParams struct {
	TagID  pgtype.UUID
	Limit  int32
	Offset int32
}

type ListPostsByTagHotRow struct {
	PostID         string
	AuthorID       string
	AuthorName     string
	AuthorAvatar   string
	AuthorProvince string
	AuthorCity     string
	Title          string
	Content        string
	Status         string
	LikeCount      int32
	DislikeCount   int32
	CollectCount   int32
	CommentCount   int32
	Cover          string
	Ctime          int64
	Utime          int64
	Birthday       interface{}
	Tags           interface{}
}

func (q *Queries) ListPostsByTagHot(ctx context.Context, arg ListPostsByTagHotParams) ([]ListPostsByTagHotRow, error) {
	rows, err := q.db.Query(ctx, listPostsByTagHot, arg.TagID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPostsByTagHotRow
	for rows.Next() {
		var i ListPostsByTagHotRow
		if err := rows.Scan(
			&i.PostID,
			&i.AuthorID,
			&i.AuthorName,
			&i.AuthorAvatar,
			&i.AuthorProvince,
			&i.AuthorCity,
			&i.Title,
			&i.Content,
			&i.Status,
			&i.LikeCount,
			&i.DislikeCount,
			&i.CollectCount,
			&i.CommentCount,
			&i.Cover,
			&i.Ctime,
			&i.Utime,
			&i.Birthday,
			&i.Tags,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchPosts = `-- name: SearchPosts :many
SELECT
  p.post_id::text AS post_id,
  p.author_id::text AS author_id,
  COALESCE(ua.username, '') AS author_name,
  COALESCE(ua.avatar, '') AS author_avatar,
  COALESCE(ua.province, '') AS author_province,
  COALESCE(ua.city, '') AS author_city,
  p.title, p.content, p.status,
  p.like_count, p.dislike_count, p.collect_count, p.comment_count,
  p.cover, p.ctime, p.utime,
  COALESCE((
    SELECT b.birthday
    FROM "baby" b
    WHERE b.user_id = p.author_id
    ORDER BY b.ctime DESC
    LIMIT 1
  ), 0) AS birthday,
  COALESCE((
    SELECT array_agg(t.tag_name) FILTER (WHERE t.tag_name IS NOT NULL)
    FROM "post_tag" pt
    JOIN "tag" t ON t.tag_id = pt.tag_id
    WHERE pt.post_id = p.post_id
  ), '{}') AS tags
FROM "post" p
LEFT JOIN "user_addition" ua ON ua.user_id = p.author_id
WHERE p.title ILIKE $1 AND p.status = $2
ORDER BY p.ctime DESC
LIMIT $3 OFFSET $4
`

type SearchPostsParams struct {
	Title  string
	Status string
	Limit  int32
	Offset int32
}

type SearchPostsRow struct {
	PostID         string
	AuthorID       string
	AuthorName     string
	AuthorAvatar   string
	AuthorProvince string
	AuthorCity     string
	Title          string
	Content        string
	Status         string
	LikeCount      int32
	DislikeCount   int32
	CollectCount   int32
	CommentCount   int32
	Cover          string
	Ctime          int64
	Utime          int64
	Birthday       interface{}
	Tags           interface{}
}

func (q *Queries) SearchPosts(ctx context.Context, arg SearchPostsParams) ([]SearchPostsRow, error) {
	rows, err := q.db.Query(ctx, searchPosts,
		arg.Title,
		arg.Status,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchPostsRow
	for rows.Next() {
		var i SearchPostsRow
		if err := rows.Scan(
			&i.PostID,
			&i.AuthorID,
			&i.AuthorName,
			&i.AuthorAvatar,
			&i.AuthorProvince,
			&i.AuthorCity,
			&i.Title,
			&i.Content,
			&i.Status,
			&i.LikeCount,
			&i.DislikeCount,
			&i.CollectCount,
			&i.CommentCount,
			&i.Cover,
			&i.Ctime,
			&i.Utime,
			&i.Birthday,
			&i.Tags,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchPostsByTitleAndTagCtime = `-- name: SearchPostsByTitleAndTagCtime :many
SELECT
  p.post_id::text AS post_id,
  p.author_id::text AS author_id,
  COALESCE(ua.username, '') AS author_name,
  COALESCE(ua.avatar, '') AS author_avatar,
  COALESCE(ua.province, '') AS author_province,
  COALESCE(ua.city, '') AS author_city,
  p.title, p.content, p.status,
  p.like_count, p.dislike_count, p.collect_count, p.comment_count,
  p.cover, p.ctime, p.utime,
  COALESCE((
    SELECT b.birthday
    FROM "baby" b
    WHERE b.user_id = p.author_id
    ORDER BY b.ctime DESC
    LIMIT 1
  ), 0) AS birthday,
  COALESCE((
    SELECT array_agg(t.tag_name) FILTER (WHERE t.tag_name IS NOT NULL)
    FROM "post_tag" pt
    JOIN "tag" t ON t.tag_id = pt.tag_id
    WHERE pt.post_id = p.post_id
  ), '{}') AS tags
FROM "post" p
JOIN "post_tag" pt2 ON pt2.post_id = p.post_id
LEFT JOIN "user_addition" ua ON ua.user_id = p.author_id
WHERE p.title ILIKE $1 AND pt2.tag_id = $2 AND p.status = 'published'
ORDER BY p.ctime DESC
LIMIT $3 OFFSET $4
`

type SearchPostsByTitleAndTagCtimeParams struct {
	Title  string
	TagID  pgtype.UUID
	Limit  int32
	Offset int32
}

type SearchPostsByTitleAndTagCtimeRow struct {
	PostID         string
	AuthorID       string
	AuthorName     string
	AuthorAvatar   string
	AuthorProvince string
	AuthorCity     string
	Title          string
	Content        string
	Status         string
	LikeCount      int32
	DislikeCount   int32
	CollectCount   int32
	CommentCount   int32
	Cover          string
	Ctime          int64
	Utime          int64
	Birthday       interface{}
	Tags           interface{}
}

func (q *Queries) SearchPostsByTitleAndTagCtime(ctx context.Context, arg SearchPostsByTitleAndTagCtimeParams) ([]SearchPostsByTitleAndTagCtimeRow, error) {
	rows, err := q.db.Query(ctx, searchPostsByTitleAndTagCtime,
		arg.Title,
		arg.TagID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchPostsByTitleAndTagCtimeRow
	for rows.Next() {
		var i SearchPostsByTitleAndTagCtimeRow
		if err := rows.Scan(
			&i.PostID,
			&i.AuthorID,
			&i.AuthorName,
			&i.AuthorAvatar,
			&i.AuthorProvince,
			&i.AuthorCity,
			&i.Title,
			&i.Content,
			&i.Status,
			&i.LikeCount,
			&i.DislikeCount,
			&i.CollectCount,
			&i.CommentCount,
			&i.Cover,
			&i.Ctime,
			&i.Utime,
			&i.Birthday,
			&i.Tags,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchPostsByTitleAndTagHot = `-- name: SearchPostsByTitleAndTagHot :many
SELECT
  p.post_id::text AS post_id,
  p.author_id::text AS author_id,
  COALESCE(ua.username, '') AS author_name,
  COALESCE(ua.avatar, '') AS author_avatar,
  COALESCE(ua.province, '') AS author_province,
  COALESCE(ua.city, '') AS author_city,
  p.title, p.content, p.status,
  p.like_count, p.dislike_count, p.collect_count, p.comment_count,
  p.cover, p.ctime, p.utime,
  COALESCE((
    SELECT b.birthday
    FROM "baby" b
    WHERE b.user_id = p.author_id
    ORDER BY b.ctime DESC
    LIMIT 1
  ), 0) AS birthday,
  COALESCE((
    SELECT array_agg(t.tag_name) FILTER (WHERE t.tag_name IS NOT NULL)
    FROM "post_tag" pt
    JOIN "tag" t ON t.tag_id = pt.tag_id
    WHERE pt.post_id = p.post_id
  ), '{}') AS tags
FROM "post" p
JOIN "post_tag" pt2 ON pt2.post_id = p.post_id
LEFT JOIN "user_addition" ua ON ua.user_id = p.author_id
WHERE p.title ILIKE $1 AND pt2.tag_id = $2 AND p.status = 'published'
ORDER BY (p.like_count*3 + p.comment_count*5 + p.collect_count*4) DESC, p.ctime DESC
LIMIT $3 OFFSET $4
`

type SearchPostsByTitleAndTagHotParams struct {
	Title  string
	TagID  pgtype.UUID
	Limit  int32
	Offset int32
}

type SearchPostsByTitleAndTagHotRow struct {
	PostID         string
	AuthorID       string
	AuthorName     string
	AuthorAvatar   string
	AuthorProvince string
	AuthorCity     string
	Title          string
	Content        string
	Status         string
	LikeCount      int32
	DislikeCount   int32
	CollectCount   int32
	CommentCount   int32
	Cover          string
	Ctime          int64
	Utime          int64
	Birthday       interface{}
	Tags           interface{}
}

func (q *Queries) SearchPostsByTitleAndTagHot(ctx context.Context, arg SearchPostsByTitleAndTagHotParams) ([]SearchPostsByTitleAndTagHotRow, error) {
	rows, err := q.db.Query(ctx, searchPostsByTitleAndTagHot,
		arg.Title,
		arg.TagID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchPostsByTitleAndTagHotRow
	for rows.Next() {
		var i SearchPostsByTitleAndTagHotRow
		if err := rows.Scan(
			&i.PostID,
			&i.AuthorID,
			&i.AuthorName,
			&i.AuthorAvatar,
			&i.AuthorProvince,
			&i.AuthorCity,
			&i.Title,
			&i.Content,
			&i.Status,
			&i.LikeCount,
			&i.DislikeCount,
			&i.CollectCount,
			&i.CommentCount,
			&i.Cover,
			&i.Ctime,
			&i.Utime,
			&i.Birthday,
			&i.Tags,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchPostsByTitleHot = `-- name: SearchPostsByTitleHot :many
SELECT
  p.post_id::text AS post_id,
  p.author_id::text AS author_id,
  COALESCE(ua.username, '') AS author_name,
  COALESCE(ua.avatar, '') AS author_avatar,
  COALESCE(ua.province, '') AS author_province,
  COALESCE(ua.city, '') AS author_city,
  p.title, p.content, p.status,
  p.like_count, p.dislike_count, p.collect_count, p.comment_count,
  p.cover, p.ctime, p.utime,
  COALESCE((
    SELECT b.birthday
    FROM "baby" b
    WHERE b.user_id = p.author_id
    ORDER BY b.ctime DESC
    LIMIT 1
  ), 0) AS birthday,
  COALESCE((
    SELECT array_agg(t.tag_name) FILTER (WHERE t.tag_name IS NOT NULL)
    FROM "post_tag" pt
    JOIN "tag" t ON t.tag_id = pt.tag_id
    WHERE pt.post_id = p.post_id
  ), '{}') AS tags
FROM "post" p
LEFT JOIN "user_addition" ua ON ua.user_id = p.author_id
WHERE p.title ILIKE $1 AND p.status = 'published'
ORDER BY (p.like_count*3 + p.comment_count*5 + p.collect_count*4) DESC, p.ctime DESC
LIMIT $2 OFFSET $3
`

type SearchPostsByTitleHotParams struct {
	Title  string
	Limit  int32
	Offset int32
}

type SearchPostsByTitleHotRow struct {
	PostID         string
	AuthorID       string
	AuthorName     string
	AuthorAvatar   string
	AuthorProvince string
	AuthorCity     string
	Title          string
	Content        string
	Status         string
	LikeCount      int32
	DislikeCount   int32
	CollectCount   int32
	CommentCount   int32
	Cover          string
	Ctime          int64
	Utime          int64
	Birthday       interface{}
	Tags           interface{}
}

func (q *Queries) SearchPostsByTitleHot(ctx context.Context, arg SearchPostsByTitleHotParams) ([]SearchPostsByTitleHotRow, error) {
	rows, err := q.db.Query(ctx, searchPostsByTitleHot, arg.Title, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchPostsByTitleHotRow
	for rows.Next() {
		var i SearchPostsByTitleHotRow
		if err := rows.Scan(
			&i.PostID,
			&i.AuthorID,
			&i.AuthorName,
			&i.AuthorAvatar,
			&i.AuthorProvince,
			&i.AuthorCity,
			&i.Title,
			&i.Content,
			&i.Status,
			&i.LikeCount,
			&i.DislikeCount,
			&i.CollectCount,
			&i.CommentCount,
			&i.Cover,
			&i.Ctime,
			&i.Utime,
			&i.Birthday,
			&i.Tags,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
