// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: post.sql

package postdao

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addPostTag = `-- name: AddPostTag :exec
INSERT INTO "post_tag" (post_id, tag_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AddPostTagParams struct {
	PostID pgtype.UUID
	TagID  pgtype.UUID
}

func (q *Queries) AddPostTag(ctx context.Context, arg AddPostTagParams) error {
	_, err := q.db.Exec(ctx, addPostTag, arg.PostID, arg.TagID)
	return err
}

const createPost = `-- name: CreatePost :exec
INSERT INTO "post" (
  post_id, author_id, title, content, status,
  like_count, dislike_count, collect_count, comment_count,
  cover, ctime, utime
) VALUES (
  $1, $2, $3, $4, $5,
  0, 0, 0, 0,
  $6, $7, $8
)
`

type CreatePostParams struct {
	PostID   pgtype.UUID
	AuthorID pgtype.UUID
	Title    string
	Content  string
	Status   string
	Cover    string
	Ctime    int64
	Utime    int64
}

func (q *Queries) CreatePost(ctx context.Context, arg CreatePostParams) error {
	_, err := q.db.Exec(ctx, createPost,
		arg.PostID,
		arg.AuthorID,
		arg.Title,
		arg.Content,
		arg.Status,
		arg.Cover,
		arg.Ctime,
		arg.Utime,
	)
	return err
}

const getPostDetail = `-- name: GetPostDetail :one
SELECT
  p.post_id::text AS post_id,
  p.author_id::text AS author_id,
  COALESCE(ua.username, '') AS author_name,
  COALESCE(ua.avatar, '') AS author_avatar,
  COALESCE(ua.province, '') AS author_province,
  COALESCE(ua.city, '') AS author_city,
  p.title, p.content, p.status,
  p.like_count, p.dislike_count, p.collect_count, p.comment_count,
  p.cover, p.ctime, p.utime,
  COALESCE(b.birthday, 0) AS birthday,
  COALESCE(array_agg(t.tag_name) FILTER (WHERE t.tag_name IS NOT NULL), '{}') AS tags
FROM "post" p
LEFT JOIN "user_addition" ua ON ua.user_id = p.author_id
LEFT JOIN LATERAL (
  SELECT birthday FROM "baby"
  WHERE user_id = p.author_id
  ORDER BY ctime DESC
  LIMIT 1
) b ON true
LEFT JOIN "post_tag" pt ON pt.post_id = p.post_id
LEFT JOIN "tag" t ON t.tag_id = pt.tag_id
WHERE p.post_id = $1
GROUP BY
  p.post_id, p.author_id, ua.username, ua.avatar, ua.province, ua.city,
  p.title, p.content, p.status, p.like_count, p.dislike_count, p.collect_count, p.comment_count,
  p.cover, p.ctime, p.utime, b.birthday
`

type GetPostDetailRow struct {
	PostID         string
	AuthorID       string
	AuthorName     string
	AuthorAvatar   string
	AuthorProvince string
	AuthorCity     string
	Title          string
	Content        string
	Status         string
	LikeCount      int32
	DislikeCount   int32
	CollectCount   int32
	CommentCount   int32
	Cover          string
	Ctime          int64
	Utime          int64
	Birthday       int64
	Tags           interface{}
}

func (q *Queries) GetPostDetail(ctx context.Context, postID pgtype.UUID) (GetPostDetailRow, error) {
	row := q.db.QueryRow(ctx, getPostDetail, postID)
	var i GetPostDetailRow
	err := row.Scan(
		&i.PostID,
		&i.AuthorID,
		&i.AuthorName,
		&i.AuthorAvatar,
		&i.AuthorProvince,
		&i.AuthorCity,
		&i.Title,
		&i.Content,
		&i.Status,
		&i.LikeCount,
		&i.DislikeCount,
		&i.CollectCount,
		&i.CommentCount,
		&i.Cover,
		&i.Ctime,
		&i.Utime,
		&i.Birthday,
		&i.Tags,
	)
	return i, err
}
