// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dao

import (
	"github.com/jackc/pgx/v5/pgtype"
)

// 宝宝表
type Baby struct {
	// 主键ID
	ID int64
	// 宝宝ID
	BabyID pgtype.UUID
	// 所属用户ID(UUID)
	UserID pgtype.UUID
	// 宝宝姓名
	Name string
	// 性别:male/female
	Gender string
	// 生日(毫秒时间戳)
	Birthday int64
	// 宝宝头像URL
	Avatar string
	// 创建时间戳
	Ctime int64
	// 更新时间戳
	Utime int64
}

// 宝宝成长记录表
type BabyGrowthRecord struct {
	// 主键ID
	ID int64
	// 记录ID
	RecordID pgtype.UUID
	// 宝宝ID(外键)
	BabyID pgtype.UUID
	// 创建者用户ID
	CreatedBy pgtype.UUID
	// 记录时间(毫秒时间戳)
	RecordTime int64
	// 身高(cm)
	Height pgtype.Float8
	// 体重(kg)
	Weight pgtype.Float8
	// 头围(cm)
	HeadCircumference pgtype.Float8
	// 备注
	Remark pgtype.Text
	// 创建时间戳
	Ctime int64
	// 最近更新者用户ID
	UpdatedBy pgtype.UUID
	// 更新时间戳
	Utime int64
}

// 宝宝相册表
type BabyPhoto struct {
	// 主键ID
	ID int64
	// 相片ID
	PhotoID pgtype.UUID
	// 宝宝ID(外键)
	BabyID pgtype.UUID
	// 详情页面URL
	Link string
	// 创建时间戳
	Ctime int64
	// 更新时间戳
	Utime int64
}

// 宝宝疫苗接种记录表
type BabyVaccineRecord struct {
	// 主键ID
	ID int64
	// 记录ID
	RecordID pgtype.UUID
	// 宝宝ID(外键)
	BabyID pgtype.UUID
	// 剂次ID(外键)
	DoseID pgtype.UUID
	// 应接种时间(毫秒)
	DueTime int64
	// 接种状态
	Status string
	// 实际接种时间(毫秒)
	ActualTime pgtype.Int8
	// 创建时间戳
	Ctime int64
	// 更新时间戳
	Utime int64
}

// 收藏表
type Collection struct {
	// 主键ID
	ID int64
	// 收藏ID
	CollectionID pgtype.UUID
	// 用户user_id(UUID)
	UserID pgtype.UUID
	// 帖子ID
	PostID pgtype.UUID
	// 创建时间戳
	Ctime int64
	// 更新时间戳
	Utime int64
}

// 评论表
type Comment struct {
	// 主键ID
	ID int64
	// 评论ID
	CommentID pgtype.UUID
	// 帖子ID
	PostID pgtype.UUID
	// 评论者user_id(UUID)
	UserID pgtype.UUID
	// 父评论ID(一级为NULL)
	ParentID pgtype.UUID
	// 评论正文
	Content pgtype.Text
	// 状态(visible/deleted/hidden)
	Status string
	// 点赞数
	LikeCount int32
	// 回复数(仅统计可见回复)
	ReplyCount int32
	// 创建时间戳
	Ctime int64
	// 更新时间戳
	Utime int64
}

// 评论闭包表
type CommentClosure struct {
	// 主键ID
	ID int64
	// 祖先评论ID
	Ancestor pgtype.UUID
	// 后代评论ID
	Descendant pgtype.UUID
	// 祖先到后代的距离
	Depth int32
}

// 评论点赞表
type CommentLike struct {
	// 主键ID
	ID int64
	// 用户user_id(UUID)
	UserID pgtype.UUID
	// 评论ID
	CommentID pgtype.UUID
	// 创建时间戳
	Ctime int64
	// 更新时间戳
	Utime int64
}

// 换尿布记录表
type DailyDiaper struct {
	// 主键ID
	ID int64
	// 换尿布记录ID
	DiaperID pgtype.UUID
	// 宝宝ID(外键)
	BabyID pgtype.UUID
	// 用户ID(UUID)
	UserID pgtype.UUID
	// 更换时间(毫秒时间戳)
	ChangeTime int64
	// 尿布状态
	DiaperType string
	// 嘘嘘颜色
	PeeColor pgtype.Text
	// 便便颜色
	PoopColor pgtype.Text
	// 便便状态
	PoopConsistency pgtype.Text
	// 备注
	Remark pgtype.Text
	// 创建时间戳
	Ctime int64
	// 更新时间戳
	Utime int64
}

// 喂养记录表
type DailyFeeding struct {
	// 主键ID
	ID int64
	// 喂养记录ID
	FeedingID pgtype.UUID
	// 宝宝ID(外键)
	BabyID pgtype.UUID
	// 用户ID(UUID)
	UserID pgtype.UUID
	// 喂养时间(毫秒时间戳)
	FeedTime int64
	// 喂养方式
	FeedType string
	// 备注
	Remark pgtype.Text
	// 创建时间戳
	Ctime int64
	// 更新时间戳
	Utime int64
}

// 睡眠记录表
type DailySleep struct {
	// 主键ID
	ID int64
	// 睡眠记录ID
	SleepID pgtype.UUID
	// 宝宝ID(外键)
	BabyID pgtype.UUID
	// 用户ID(UUID)
	UserID pgtype.UUID
	// 开始时间(毫秒时间戳)
	StartTime int64
	// 结束时间(毫秒时间戳)
	EndTime pgtype.Int8
	// 睡眠时长(毫秒)
	Duration pgtype.Int8
	// 记录方式(timer/manual)
	Source string
	// 状态(running/finished)
	Status string
	// 备注
	Remark pgtype.Text
	// 创建时间戳
	Ctime int64
	// 更新时间戳
	Utime int64
}

// 点赞/不喜欢表
type LikeDislike struct {
	// 主键ID
	ID int64
	// 用户user_id(UUID)
	UserID pgtype.UUID
	// 帖子ID
	PostID pgtype.UUID
	// like或dislike
	Type string
	// 创建时间戳
	Ctime int64
	// 更新时间戳
	Utime int64
}

// 帖子表
type Post struct {
	// 主键ID
	ID int64
	// 帖子ID
	PostID pgtype.UUID
	// 作者 user_id(UUID)
	AuthorID pgtype.UUID
	// 标题
	Title string
	// 正文
	Content string
	// 状态
	Status string
	// 点赞数
	LikeCount int32
	// 不喜欢数
	DislikeCount int32
	// 收藏数
	CollectCount int32
	// 评论数
	CommentCount int32
	// 封面图URL
	Cover string
	// 创建时间戳
	Ctime int64
	// 更新时间戳
	Utime int64
}

// 帖子-标签关联表
type PostTag struct {
	// 主键ID
	ID int64
	// 帖子ID
	PostID pgtype.UUID
	// 标签ID
	TagID pgtype.UUID
}

// 标签表
type Tag struct {
	// 主键ID
	ID int64
	// 标签ID
	TagID pgtype.UUID
	// 标签名
	TagName string
	// 描述
	Description pgtype.Text
	// 创建时间戳
	Ctime int64
	// 更新时间戳
	Utime int64
}

// 用户扩展信息（冗余用户名、头像、地区）
type UserAddition struct {
	// 主键ID
	ID int64
	// 用户ID(与基础信息一对一)
	UserID pgtype.UUID
	// 用户名（冗余）
	Username string
	// 性别（冗余）
	Gender string
	// 手机号
	Phone string
	// 职业
	Occupation string
	// 生日(毫秒时间戳,未知为0)
	Birthday int64
	// 头像URL
	Avatar string
	// 省
	Province string
	// 市
	City string
	// 创建时间
	Ctime int64
	// 更新时间
	Utime int64
}

// 用户基础信息（注册必填）
type UserBase struct {
	// 主键ID
	ID int64
	// 用户ID
	UserID pgtype.UUID
	// 账号
	Account string
	// 密码
	Password string
	// 邮箱
	Email pgtype.Text
	// 用户名
	Username string
	// 性别:male/female
	Gender string
	// 角色
	Role int16
	// 创建时间
	Ctime int64
	// 更新时间
	Utime int64
}

// 用户关注关系表
type UserFollow struct {
	// 主键ID
	ID int64
	// 关注者用户UUID
	Follower pgtype.UUID
	// 被关注者用户UUID
	Followee pgtype.UUID
	// 关注时间戳
	Ctime int64
	// 更新时间戳
	Utime int64
}

// 用户另一半关系表（父/母）
type UserPartner struct {
	// 主键ID
	ID int64
	// 父亲用户UUID
	Father pgtype.UUID
	// 母亲用户UUID
	Mother pgtype.UUID
	// 创建时间戳
	Ctime int64
	// 更新时间戳
	Utime int64
}

// 用户推荐画像（文本），用于向量检索召回
type UserRecommendProfile struct {
	// 用户 user_id(UUID)
	UserID pgtype.UUID
	// 画像文本
	ProfileText string
	// 更新时间戳
	Utime int64
}

// 疫苗字典表
type Vaccine struct {
	// 主键ID
	ID int64
	// 疫苗ID
	VaccineID pgtype.UUID
	// 疫苗名称
	Name string
	// 预防疾病
	Disease string
	// 详情页面URL
	Link string
	// 创建时间戳
	Ctime int64
	// 更新时间戳
	Utime int64
}

// 疫苗剂次表
type VaccineDose struct {
	// 主键ID
	ID int64
	// 剂次ID
	DoseID pgtype.UUID
	// 疫苗ID(外键)
	VaccineID pgtype.UUID
	// 第几剂(从1开始)
	DoseNumber int32
	// 推荐接种年龄(天)
	RecommendAgeDays int32
	// 创建时间戳
	Ctime int64
	// 更新时间戳
	Utime int64
}
