// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: post.sql

package post

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addPostTag = `-- name: AddPostTag :exec
INSERT INTO "post_tag" (post_id, tag_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AddPostTagParams struct {
	PostID pgtype.UUID
	TagID  pgtype.UUID
}

func (q *Queries) AddPostTag(ctx context.Context, arg AddPostTagParams) error {
	_, err := q.db.Exec(ctx, addPostTag, arg.PostID, arg.TagID)
	return err
}

const tagExists = `-- name: TagExists :one
SELECT EXISTS(SELECT 1 FROM "tag" WHERE tag_id = $1)
`

func (q *Queries) TagExists(ctx context.Context, tagID pgtype.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, tagExists, tagID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const createCollection = `-- name: CreateCollection :execrows
INSERT INTO "collection" (collection_id, user_id, post_id, ctime, utime)
VALUES ($1, $2, $3, $4, $4)
ON CONFLICT (user_id, post_id) DO NOTHING
`

type CreateCollectionParams struct {
	CollectionID pgtype.UUID
	UserID       pgtype.UUID
	PostID       pgtype.UUID
	Ctime        int64
}

func (q *Queries) CreateCollection(ctx context.Context, arg CreateCollectionParams) (int64, error) {
	result, err := q.db.Exec(ctx, createCollection,
		arg.CollectionID,
		arg.UserID,
		arg.PostID,
		arg.Ctime,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createComment = `-- name: CreateComment :exec
INSERT INTO "comment" (
  comment_id, post_id, user_id, parent_id, content, status, like_count, reply_count, ctime, utime
) VALUES (
  $1, $2, $3, $4, $5, 'visible', 0, 0, $6, $7
)
`

type CreateCommentParams struct {
	CommentID pgtype.UUID
	PostID    pgtype.UUID
	UserID    pgtype.UUID
	ParentID  pgtype.UUID
	Content   pgtype.Text
	Ctime     int64
	Utime     int64
}

func (q *Queries) CreateComment(ctx context.Context, arg CreateCommentParams) error {
	_, err := q.db.Exec(ctx, createComment,
		arg.CommentID,
		arg.PostID,
		arg.UserID,
		arg.ParentID,
		arg.Content,
		arg.Ctime,
		arg.Utime,
	)
	return err
}

const createCommentLike = `-- name: CreateCommentLike :execrows
INSERT INTO "comment_like" (user_id, comment_id, ctime, utime)
VALUES ($1, $2, $3, $3)
ON CONFLICT (user_id, comment_id) DO NOTHING
`

type CreateCommentLikeParams struct {
	UserID    pgtype.UUID
	CommentID pgtype.UUID
	Ctime     int64
}

func (q *Queries) CreateCommentLike(ctx context.Context, arg CreateCommentLikeParams) (int64, error) {
	result, err := q.db.Exec(ctx, createCommentLike, arg.UserID, arg.CommentID, arg.Ctime)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createPost = `-- name: CreatePost :exec
INSERT INTO "post" (
  post_id, author_id, title, content, status,
  like_count, dislike_count, collect_count, comment_count,
  cover, ctime, utime
) VALUES (
  $1, $2, $3, $4, $5,
  0, 0, 0, 0,
  $6, $7, $8
)
`

type CreatePostParams struct {
	PostID   pgtype.UUID
	AuthorID pgtype.UUID
	Title    string
	Content  string
	Status   string
	Cover    string
	Ctime    int64
	Utime    int64
}

func (q *Queries) CreatePost(ctx context.Context, arg CreatePostParams) error {
	_, err := q.db.Exec(ctx, createPost,
		arg.PostID,
		arg.AuthorID,
		arg.Title,
		arg.Content,
		arg.Status,
		arg.Cover,
		arg.Ctime,
		arg.Utime,
	)
	return err
}

const createPostLike = `-- name: CreatePostLike :execrows
INSERT INTO "like_dislike" (user_id, post_id, type, ctime, utime)
VALUES ($1, $2, 'like', $3, $3)
ON CONFLICT (user_id, post_id) DO UPDATE
SET type = 'like', utime = $3
WHERE like_dislike.type <> 'like'
`

type CreatePostLikeParams struct {
	UserID pgtype.UUID
	PostID pgtype.UUID
	Ctime  int64
}

func (q *Queries) CreatePostLike(ctx context.Context, arg CreatePostLikeParams) (int64, error) {
	result, err := q.db.Exec(ctx, createPostLike, arg.UserID, arg.PostID, arg.Ctime)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createTag = `-- name: CreateTag :one
INSERT INTO "tag"(tag_id, tag_name, description, ctime, utime)
VALUES ($1, $2, $3, $4, $4)
RETURNING tag_id::text AS tag_id, tag_name, COALESCE(description, '') AS description
`

type CreateTagParams struct {
	TagID       pgtype.UUID
	TagName     string
	Description pgtype.Text
	Ctime       int64
}

type CreateTagRow struct {
	TagID       string
	TagName     string
	Description string
}

// admin
func (q *Queries) CreateTag(ctx context.Context, arg CreateTagParams) (CreateTagRow, error) {
	row := q.db.QueryRow(ctx, createTag,
		arg.TagID,
		arg.TagName,
		arg.Description,
		arg.Ctime,
	)
	var i CreateTagRow
	err := row.Scan(&i.TagID, &i.TagName, &i.Description)
	return i, err
}

const decCommentLikeCount = `-- name: DecCommentLikeCount :execrows
UPDATE "comment"
SET like_count = GREATEST(like_count - 1, 0)
WHERE comment_id = $1
`

func (q *Queries) DecCommentLikeCount(ctx context.Context, commentID pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, decCommentLikeCount, commentID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const decCommentReplyCount = `-- name: DecCommentReplyCount :execrows
UPDATE "comment"
SET reply_count = GREATEST(reply_count - 1, 0)
WHERE comment_id = $1
`

func (q *Queries) DecCommentReplyCount(ctx context.Context, commentID pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, decCommentReplyCount, commentID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const decPostCollectCount = `-- name: DecPostCollectCount :execrows
UPDATE "post"
SET collect_count = GREATEST(collect_count - 1, 0)
WHERE post_id = $1
`

func (q *Queries) DecPostCollectCount(ctx context.Context, postID pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, decPostCollectCount, postID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const decPostCommentCount = `-- name: DecPostCommentCount :execrows
UPDATE "post"
SET comment_count = GREATEST(comment_count - 1, 0)
WHERE post_id = $1
`

func (q *Queries) DecPostCommentCount(ctx context.Context, postID pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, decPostCommentCount, postID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const decPostLikeCount = `-- name: DecPostLikeCount :execrows
UPDATE "post"
SET like_count = GREATEST(like_count - 1, 0)
WHERE post_id = $1
`

func (q *Queries) DecPostLikeCount(ctx context.Context, postID pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, decPostLikeCount, postID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteCollection = `-- name: DeleteCollection :execrows
DELETE FROM "collection"
WHERE user_id = $1 AND post_id = $2
`

type DeleteCollectionParams struct {
	UserID pgtype.UUID
	PostID pgtype.UUID
}

func (q *Queries) DeleteCollection(ctx context.Context, arg DeleteCollectionParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteCollection, arg.UserID, arg.PostID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteCommentLike = `-- name: DeleteCommentLike :execrows
DELETE FROM "comment_like"
WHERE user_id = $1 AND comment_id = $2
`

type DeleteCommentLikeParams struct {
	UserID    pgtype.UUID
	CommentID pgtype.UUID
}

func (q *Queries) DeleteCommentLike(ctx context.Context, arg DeleteCommentLikeParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteCommentLike, arg.UserID, arg.CommentID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteCommentVisibleByOwner = `-- name: DeleteCommentVisibleByOwner :execrows
UPDATE "comment"
SET status = 'deleted', utime = $2
WHERE comment_id = $1 AND user_id = $3 AND status = 'visible'
`

type DeleteCommentVisibleByOwnerParams struct {
	CommentID pgtype.UUID
	Utime     int64
	UserID    pgtype.UUID
}

func (q *Queries) DeleteCommentVisibleByOwner(ctx context.Context, arg DeleteCommentVisibleByOwnerParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteCommentVisibleByOwner, arg.CommentID, arg.Utime, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteDraftByOwner = `-- name: DeleteDraftByOwner :execrows
DELETE FROM "post"
WHERE post_id = $1 AND author_id = $2 AND status = 'draft'
`

type DeleteDraftByOwnerParams struct {
	PostID   pgtype.UUID
	AuthorID pgtype.UUID
}

func (q *Queries) DeleteDraftByOwner(ctx context.Context, arg DeleteDraftByOwnerParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteDraftByOwner, arg.PostID, arg.AuthorID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deletePostLike = `-- name: DeletePostLike :execrows
DELETE FROM "like_dislike"
WHERE user_id = $1 AND post_id = $2 AND type = 'like'
`

type DeletePostLikeParams struct {
	UserID pgtype.UUID
	PostID pgtype.UUID
}

func (q *Queries) DeletePostLike(ctx context.Context, arg DeletePostLikeParams) (int64, error) {
	result, err := q.db.Exec(ctx, deletePostLike, arg.UserID, arg.PostID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deletePostTagsByPost = `-- name: DeletePostTagsByPost :exec
DELETE FROM "post_tag" WHERE post_id = $1
`

func (q *Queries) DeletePostTagsByPost(ctx context.Context, postID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deletePostTagsByPost, postID)
	return err
}

const deletePostTagsByTagID = `-- name: DeletePostTagsByTagID :execrows
DELETE FROM "post_tag" WHERE tag_id = $1
`

// admin
func (q *Queries) DeletePostTagsByTagID(ctx context.Context, tagID pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deletePostTagsByTagID, tagID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteTagByID = `-- name: DeleteTagByID :execrows
DELETE FROM "tag" WHERE tag_id = $1
`

// admin
func (q *Queries) DeleteTagByID(ctx context.Context, tagID pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteTagByID, tagID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getCommentMetaByID = `-- name: GetCommentMetaByID :one
SELECT
  post_id::text AS post_id,
  parent_id,
  status,
  user_id::text AS user_id
FROM "comment"
WHERE comment_id = $1
`

type GetCommentMetaByIDRow struct {
	PostID   string
	ParentID pgtype.UUID
	Status   string
	UserID   string
}

func (q *Queries) GetCommentMetaByID(ctx context.Context, commentID pgtype.UUID) (GetCommentMetaByIDRow, error) {
	row := q.db.QueryRow(ctx, getCommentMetaByID, commentID)
	var i GetCommentMetaByIDRow
	err := row.Scan(
		&i.PostID,
		&i.ParentID,
		&i.Status,
		&i.UserID,
	)
	return i, err
}

const getCommentMinimal = `-- name: GetCommentMinimal :one
SELECT post_id::text AS post_id, status
FROM "comment"
WHERE comment_id = $1
`

type GetCommentMinimalRow struct {
	PostID string
	Status string
}

func (q *Queries) GetCommentMinimal(ctx context.Context, commentID pgtype.UUID) (GetCommentMinimalRow, error) {
	row := q.db.QueryRow(ctx, getCommentMinimal, commentID)
	var i GetCommentMinimalRow
	err := row.Scan(&i.PostID, &i.Status)
	return i, err
}

const getPostDetail = `-- name: GetPostDetail :one
SELECT
  p.post_id::text AS post_id,
  p.author_id::text AS author_id,
  COALESCE(ua.username, '') AS author_name,
  COALESCE(ua.avatar, '') AS author_avatar,
  COALESCE(ua.province, '') AS author_province,
  COALESCE(ua.city, '') AS author_city,
  p.title, p.content, p.status,
  p.like_count, p.dislike_count, p.collect_count, p.comment_count,
  p.cover, p.ctime, p.utime,
  COALESCE((
    SELECT b.birthday
    FROM "baby" b
    WHERE b.user_id = p.author_id
    ORDER BY b.ctime DESC
    LIMIT 1
  ), 0) AS birthday,
  COALESCE((
    SELECT array_agg(t.tag_name) FILTER (WHERE t.tag_name IS NOT NULL)
    FROM "post_tag" pt
    JOIN "tag" t ON t.tag_id = pt.tag_id
    WHERE pt.post_id = p.post_id
  ), '{}') AS tags,
  EXISTS(
    SELECT 1 FROM "like_dislike" ld
    WHERE ld.post_id = p.post_id AND ld.user_id = NULLIF($2, '')::uuid AND ld.type = 'like'
  ) AS is_like,
  EXISTS(
    SELECT 1 FROM "like_dislike" ld2
    WHERE ld2.post_id = p.post_id AND ld2.user_id = NULLIF($2, '')::uuid AND ld2.type = 'dislike'
  ) AS is_dislike,
  EXISTS(
    SELECT 1 FROM "collection" c2
    WHERE c2.post_id = p.post_id AND c2.user_id = NULLIF($2, '')::uuid
  ) AS is_collect
FROM "post" p
LEFT JOIN "user_addition" ua ON ua.user_id = p.author_id
WHERE p.post_id = $1
`

type GetPostDetailParams struct {
	PostID  pgtype.UUID
	Column2 interface{}
}

type GetPostDetailRow struct {
	PostID         string
	AuthorID       string
	AuthorName     string
	AuthorAvatar   string
	AuthorProvince string
	AuthorCity     string
	Title          string
	Content        string
	Status         string
	LikeCount      int32
	DislikeCount   int32
	CollectCount   int32
	CommentCount   int32
	Cover          string
	Ctime          int64
	Utime          int64
	Birthday       interface{}
	Tags           interface{}
	IsLike         bool
	IsDislike      bool
	IsCollect      bool
}

func (q *Queries) GetPostDetail(ctx context.Context, arg GetPostDetailParams) (GetPostDetailRow, error) {
	row := q.db.QueryRow(ctx, getPostDetail, arg.PostID, arg.Column2)
	var i GetPostDetailRow
	err := row.Scan(
		&i.PostID,
		&i.AuthorID,
		&i.AuthorName,
		&i.AuthorAvatar,
		&i.AuthorProvince,
		&i.AuthorCity,
		&i.Title,
		&i.Content,
		&i.Status,
		&i.LikeCount,
		&i.DislikeCount,
		&i.CollectCount,
		&i.CommentCount,
		&i.Cover,
		&i.Ctime,
		&i.Utime,
		&i.Birthday,
		&i.Tags,
		&i.IsLike,
		&i.IsDislike,
		&i.IsCollect,
	)
	return i, err
}

const getPostStatusByID = `-- name: GetPostStatusByID :one
SELECT status FROM "post" WHERE post_id = $1
`

func (q *Queries) GetPostStatusByID(ctx context.Context, postID pgtype.UUID) (string, error) {
	row := q.db.QueryRow(ctx, getPostStatusByID, postID)
	var status string
	err := row.Scan(&status)
	return status, err
}

const incCommentLikeCount = `-- name: IncCommentLikeCount :execrows
UPDATE "comment"
SET like_count = like_count + 1
WHERE comment_id = $1 AND status = 'visible'
`

func (q *Queries) IncCommentLikeCount(ctx context.Context, commentID pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, incCommentLikeCount, commentID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const incCommentReplyCount = `-- name: IncCommentReplyCount :execrows
UPDATE "comment"
SET reply_count = reply_count + 1
WHERE comment_id = $1
`

func (q *Queries) IncCommentReplyCount(ctx context.Context, commentID pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, incCommentReplyCount, commentID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const incPostCollectCount = `-- name: IncPostCollectCount :execrows
UPDATE "post"
SET collect_count = collect_count + 1
WHERE post_id = $1 AND status = 'published'
`

func (q *Queries) IncPostCollectCount(ctx context.Context, postID pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, incPostCollectCount, postID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const incPostCommentCount = `-- name: IncPostCommentCount :execrows
UPDATE "post"
SET comment_count = comment_count + 1
WHERE post_id = $1
`

func (q *Queries) IncPostCommentCount(ctx context.Context, postID pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, incPostCommentCount, postID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const incPostLikeCount = `-- name: IncPostLikeCount :execrows
UPDATE "post"
SET like_count = like_count + 1
WHERE post_id = $1 AND status = 'published'
`

func (q *Queries) IncPostLikeCount(ctx context.Context, postID pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, incPostLikeCount, postID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listCollectionsByCtime = `-- name: ListCollectionsByCtime :many
SELECT
  p.post_id::text AS post_id,
  p.author_id::text AS author_id,
  COALESCE(ua.username, '') AS author_name,
  COALESCE(ua.avatar, '') AS author_avatar,
  COALESCE(ua.province, '') AS author_province,
  COALESCE(ua.city, '') AS author_city,
  p.title, p.content, p.status,
  p.like_count, p.dislike_count, p.collect_count, p.comment_count,
  p.cover, p.ctime, p.utime,
  COALESCE((
    SELECT b.birthday
    FROM "baby" b
    WHERE b.user_id = p.author_id
    ORDER BY b.ctime DESC
    LIMIT 1
  ), 0) AS birthday,
  COALESCE((
    SELECT array_agg(t.tag_name) FILTER (WHERE t.tag_name IS NOT NULL)
    FROM "post_tag" pt
    JOIN "tag" t ON t.tag_id = pt.tag_id
    WHERE pt.post_id = p.post_id
  ), '{}') AS tags,
  EXISTS(
    SELECT 1 FROM "like_dislike" ld
    WHERE ld.post_id = p.post_id AND ld.user_id = NULLIF($1, '')::uuid AND ld.type = 'like'
  ) AS is_like,
  EXISTS(
    SELECT 1 FROM "like_dislike" ld2
    WHERE ld2.post_id = p.post_id AND ld2.user_id = NULLIF($1, '')::uuid AND ld2.type = 'dislike'
  ) AS is_dislike,
  TRUE AS is_collect
FROM "collection" c
JOIN "post" p ON p.post_id = c.post_id
LEFT JOIN "user_addition" ua ON ua.user_id = p.author_id
WHERE c.user_id = NULLIF($1, '')::uuid
ORDER BY c.ctime DESC
LIMIT $2 OFFSET $3
`

type ListCollectionsByCtimeParams struct {
	Column1 interface{}
	Limit   int32
	Offset  int32
}

type ListCollectionsByCtimeRow struct {
	PostID         string
	AuthorID       string
	AuthorName     string
	AuthorAvatar   string
	AuthorProvince string
	AuthorCity     string
	Title          string
	Content        string
	Status         string
	LikeCount      int32
	DislikeCount   int32
	CollectCount   int32
	CommentCount   int32
	Cover          string
	Ctime          int64
	Utime          int64
	Birthday       interface{}
	Tags           interface{}
	IsLike         bool
	IsDislike      bool
	IsCollect      bool
}

func (q *Queries) ListCollectionsByCtime(ctx context.Context, arg ListCollectionsByCtimeParams) ([]ListCollectionsByCtimeRow, error) {
	rows, err := q.db.Query(ctx, listCollectionsByCtime, arg.Column1, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCollectionsByCtimeRow
	for rows.Next() {
		var i ListCollectionsByCtimeRow
		if err := rows.Scan(
			&i.PostID,
			&i.AuthorID,
			&i.AuthorName,
			&i.AuthorAvatar,
			&i.AuthorProvince,
			&i.AuthorCity,
			&i.Title,
			&i.Content,
			&i.Status,
			&i.LikeCount,
			&i.DislikeCount,
			&i.CollectCount,
			&i.CommentCount,
			&i.Cover,
			&i.Ctime,
			&i.Utime,
			&i.Birthday,
			&i.Tags,
			&i.IsLike,
			&i.IsDislike,
			&i.IsCollect,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCollectionsByHot = `-- name: ListCollectionsByHot :many
SELECT
  p.post_id::text AS post_id,
  p.author_id::text AS author_id,
  COALESCE(ua.username, '') AS author_name,
  COALESCE(ua.avatar, '') AS author_avatar,
  COALESCE(ua.province, '') AS author_province,
  COALESCE(ua.city, '') AS author_city,
  p.title, p.content, p.status,
  p.like_count, p.dislike_count, p.collect_count, p.comment_count,
  p.cover, p.ctime, p.utime,
  COALESCE((
    SELECT b.birthday
    FROM "baby" b
    WHERE b.user_id = p.author_id
    ORDER BY b.ctime DESC
    LIMIT 1
  ), 0) AS birthday,
  COALESCE((
    SELECT array_agg(t.tag_name) FILTER (WHERE t.tag_name IS NOT NULL)
    FROM "post_tag" pt2
    JOIN "tag" t ON t.tag_id = pt2.tag_id
    WHERE pt2.post_id = p.post_id
  ), '{}') AS tags,
  EXISTS(
    SELECT 1 FROM "like_dislike" ld
    WHERE ld.post_id = p.post_id AND ld.user_id = NULLIF($1, '')::uuid AND ld.type = 'like'
  ) AS is_like,
  EXISTS(
    SELECT 1 FROM "like_dislike" ld2
    WHERE ld2.post_id = p.post_id AND ld2.user_id = NULLIF($1, '')::uuid AND ld2.type = 'dislike'
  ) AS is_dislike,
  TRUE AS is_collect
FROM "collection" c
JOIN "post" p ON p.post_id = c.post_id
LEFT JOIN "user_addition" ua ON ua.user_id = p.author_id
WHERE c.user_id = NULLIF($1, '')::uuid AND p.status = 'published'
ORDER BY (p.like_count*3 + p.comment_count*5 + p.collect_count*4) DESC, c.ctime DESC
LIMIT $2 OFFSET $3
`

type ListCollectionsByHotParams struct {
	Column1 interface{}
	Limit   int32
	Offset  int32
}

type ListCollectionsByHotRow struct {
	PostID         string
	AuthorID       string
	AuthorName     string
	AuthorAvatar   string
	AuthorProvince string
	AuthorCity     string
	Title          string
	Content        string
	Status         string
	LikeCount      int32
	DislikeCount   int32
	CollectCount   int32
	CommentCount   int32
	Cover          string
	Ctime          int64
	Utime          int64
	Birthday       interface{}
	Tags           interface{}
	IsLike         bool
	IsDislike      bool
	IsCollect      bool
}

func (q *Queries) ListCollectionsByHot(ctx context.Context, arg ListCollectionsByHotParams) ([]ListCollectionsByHotRow, error) {
	rows, err := q.db.Query(ctx, listCollectionsByHot, arg.Column1, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCollectionsByHotRow
	for rows.Next() {
		var i ListCollectionsByHotRow
		if err := rows.Scan(
			&i.PostID,
			&i.AuthorID,
			&i.AuthorName,
			&i.AuthorAvatar,
			&i.AuthorProvince,
			&i.AuthorCity,
			&i.Title,
			&i.Content,
			&i.Status,
			&i.LikeCount,
			&i.DislikeCount,
			&i.CollectCount,
			&i.CommentCount,
			&i.Cover,
			&i.Ctime,
			&i.Utime,
			&i.Birthday,
			&i.Tags,
			&i.IsLike,
			&i.IsDislike,
			&i.IsCollect,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCommentRepliesByCtime = `-- name: ListCommentRepliesByCtime :many
SELECT
  c.comment_id::text AS comment_id,
  c.user_id::text AS user_id,
  COALESCE(ua.username, '') AS username,
  COALESCE(ua.avatar, '') AS avatar,
  c.content,
  c.like_count,
  (SELECT COUNT(1) FROM "comment" ch WHERE ch.parent_id = c.comment_id AND ch.status = 'visible') AS reply_count,
  c.ctime,
  c.utime,
  EXISTS(
    SELECT 1 FROM "comment_like" cl
    WHERE cl.comment_id = c.comment_id AND cl.user_id = NULLIF($4, '')::uuid
  ) AS has_liked
FROM "comment" c
LEFT JOIN "user_addition" ua ON ua.user_id = c.user_id
WHERE c.parent_id = $1 AND c.status = 'visible'
ORDER BY c.ctime DESC
LIMIT $2 OFFSET $3
`

type ListCommentRepliesByCtimeParams struct {
	ParentID pgtype.UUID
	Limit    int32
	Offset   int32
	Column4  interface{}
}

type ListCommentRepliesByCtimeRow struct {
	CommentID  string
	UserID     string
	Username   string
	Avatar     string
	Content    pgtype.Text
	LikeCount  int32
	ReplyCount int64
	Ctime      int64
	Utime      int64
	HasLiked   bool
}

func (q *Queries) ListCommentRepliesByCtime(ctx context.Context, arg ListCommentRepliesByCtimeParams) ([]ListCommentRepliesByCtimeRow, error) {
	rows, err := q.db.Query(ctx, listCommentRepliesByCtime,
		arg.ParentID,
		arg.Limit,
		arg.Offset,
		arg.Column4,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCommentRepliesByCtimeRow
	for rows.Next() {
		var i ListCommentRepliesByCtimeRow
		if err := rows.Scan(
			&i.CommentID,
			&i.UserID,
			&i.Username,
			&i.Avatar,
			&i.Content,
			&i.LikeCount,
			&i.ReplyCount,
			&i.Ctime,
			&i.Utime,
			&i.HasLiked,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCommentRepliesByHot = `-- name: ListCommentRepliesByHot :many
SELECT
  c.comment_id::text AS comment_id,
  c.user_id::text AS user_id,
  COALESCE(ua.username, '') AS username,
  COALESCE(ua.avatar, '') AS avatar,
  c.content,
  c.like_count,
  (SELECT COUNT(1) FROM "comment" ch WHERE ch.parent_id = c.comment_id AND ch.status = 'visible') AS reply_count,
  c.ctime,
  c.utime,
  EXISTS(
    SELECT 1 FROM "comment_like" cl
    WHERE cl.comment_id = c.comment_id AND cl.user_id = NULLIF($4, '')::uuid
  ) AS has_liked
FROM "comment" c
LEFT JOIN "user_addition" ua ON ua.user_id = c.user_id
WHERE c.parent_id = $1 AND c.status = 'visible'
ORDER BY c.like_count DESC, c.ctime DESC
LIMIT $2 OFFSET $3
`

type ListCommentRepliesByHotParams struct {
	ParentID pgtype.UUID
	Limit    int32
	Offset   int32
	Column4  interface{}
}

type ListCommentRepliesByHotRow struct {
	CommentID  string
	UserID     string
	Username   string
	Avatar     string
	Content    pgtype.Text
	LikeCount  int32
	ReplyCount int64
	Ctime      int64
	Utime      int64
	HasLiked   bool
}

func (q *Queries) ListCommentRepliesByHot(ctx context.Context, arg ListCommentRepliesByHotParams) ([]ListCommentRepliesByHotRow, error) {
	rows, err := q.db.Query(ctx, listCommentRepliesByHot,
		arg.ParentID,
		arg.Limit,
		arg.Offset,
		arg.Column4,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCommentRepliesByHotRow
	for rows.Next() {
		var i ListCommentRepliesByHotRow
		if err := rows.Scan(
			&i.CommentID,
			&i.UserID,
			&i.Username,
			&i.Avatar,
			&i.Content,
			&i.LikeCount,
			&i.ReplyCount,
			&i.Ctime,
			&i.Utime,
			&i.HasLiked,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDraftsByAuthor = `-- name: ListDraftsByAuthor :many
SELECT
  p.post_id::text AS post_id,
  p.author_id::text AS author_id,
  COALESCE(ua.username, '') AS author_name,
  COALESCE(ua.avatar, '') AS author_avatar,
  COALESCE(ua.province, '') AS author_province,
  COALESCE(ua.city, '') AS author_city,
  p.title, p.content, p.status,
  p.like_count, p.dislike_count, p.collect_count, p.comment_count,
  p.cover, p.ctime, p.utime,
  COALESCE((
    SELECT b.birthday
    FROM "baby" b
    WHERE b.user_id = p.author_id
    ORDER BY b.ctime DESC
    LIMIT 1
  ), 0) AS birthday,
  COALESCE((
    SELECT array_agg(t.tag_name) FILTER (WHERE t.tag_name IS NOT NULL)
    FROM "post_tag" pt2
    JOIN "tag" t ON t.tag_id = pt2.tag_id
    WHERE pt2.post_id = p.post_id
  ), '{}') AS tags,
  EXISTS(
    SELECT 1 FROM "like_dislike" ld
    WHERE ld.post_id = p.post_id AND ld.user_id = NULLIF($1::text, '')::uuid AND ld.type = 'like'
  ) AS is_like,
  EXISTS(
    SELECT 1 FROM "like_dislike" ld2
    WHERE ld2.post_id = p.post_id AND ld2.user_id = NULLIF($1::text, '')::uuid AND ld2.type = 'dislike'
  ) AS is_dislike,
  EXISTS(
    SELECT 1 FROM "collection" c2
    WHERE c2.post_id = p.post_id AND c2.user_id = NULLIF($1::text, '')::uuid
  ) AS is_collect
FROM "post" p
LEFT JOIN "user_addition" ua ON ua.user_id = p.author_id
WHERE p.author_id = NULLIF($1::text, '')::uuid AND p.status = 'draft'
ORDER BY p.ctime DESC
LIMIT $2 OFFSET $3
`

type ListDraftsByAuthorParams struct {
	Column1 string
	Limit   int32
	Offset  int32
}

type ListDraftsByAuthorRow struct {
	PostID         string
	AuthorID       string
	AuthorName     string
	AuthorAvatar   string
	AuthorProvince string
	AuthorCity     string
	Title          string
	Content        string
	Status         string
	LikeCount      int32
	DislikeCount   int32
	CollectCount   int32
	CommentCount   int32
	Cover          string
	Ctime          int64
	Utime          int64
	Birthday       interface{}
	Tags           interface{}
	IsLike         bool
	IsDislike      bool
	IsCollect      bool
}

func (q *Queries) ListDraftsByAuthor(ctx context.Context, arg ListDraftsByAuthorParams) ([]ListDraftsByAuthorRow, error) {
	rows, err := q.db.Query(ctx, listDraftsByAuthor, arg.Column1, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDraftsByAuthorRow
	for rows.Next() {
		var i ListDraftsByAuthorRow
		if err := rows.Scan(
			&i.PostID,
			&i.AuthorID,
			&i.AuthorName,
			&i.AuthorAvatar,
			&i.AuthorProvince,
			&i.AuthorCity,
			&i.Title,
			&i.Content,
			&i.Status,
			&i.LikeCount,
			&i.DislikeCount,
			&i.CollectCount,
			&i.CommentCount,
			&i.Cover,
			&i.Ctime,
			&i.Utime,
			&i.Birthday,
			&i.Tags,
			&i.IsLike,
			&i.IsDislike,
			&i.IsCollect,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFollowingByCtime = `-- name: ListFollowingByCtime :many
SELECT
  p.post_id::text AS post_id,
  p.author_id::text AS author_id,
  COALESCE(ua.username, '') AS author_name,
  COALESCE(ua.avatar, '') AS author_avatar,
  COALESCE(ua.province, '') AS author_province,
  COALESCE(ua.city, '') AS author_city,
  p.title, p.content, p.status,
  p.like_count, p.dislike_count, p.collect_count, p.comment_count,
  p.cover, p.ctime, p.utime,
  COALESCE((
    SELECT b.birthday
    FROM "baby" b
    WHERE b.user_id = p.author_id
    ORDER BY b.ctime DESC
    LIMIT 1
  ), 0) AS birthday,
  COALESCE((
    SELECT array_agg(t.tag_name) FILTER (WHERE t.tag_name IS NOT NULL)
    FROM "post_tag" pt
    JOIN "tag" t ON t.tag_id = pt.tag_id
    WHERE pt.post_id = p.post_id
  ), '{}') AS tags,
  EXISTS(
    SELECT 1 FROM "like_dislike" ld
    WHERE ld.post_id = p.post_id AND ld.user_id = NULLIF($1, '')::uuid AND ld.type = 'like'
  ) AS is_like,
  EXISTS(
    SELECT 1 FROM "like_dislike" ld2
    WHERE ld2.post_id = p.post_id AND ld2.user_id = NULLIF($1, '')::uuid AND ld2.type = 'dislike'
  ) AS is_dislike,
  EXISTS(
    SELECT 1 FROM "collection" c2
    WHERE c2.post_id = p.post_id AND c2.user_id = NULLIF($1, '')::uuid
  ) AS is_collect
FROM "post" p
JOIN "user_follow" f ON f.followee = p.author_id
LEFT JOIN "user_addition" ua ON ua.user_id = p.author_id
WHERE f.follower = NULLIF($1, '')::uuid AND p.status = 'published'
ORDER BY p.ctime DESC
LIMIT $2 OFFSET $3
`

type ListFollowingByCtimeParams struct {
	Column1 interface{}
	Limit   int32
	Offset  int32
}

type ListFollowingByCtimeRow struct {
	PostID         string
	AuthorID       string
	AuthorName     string
	AuthorAvatar   string
	AuthorProvince string
	AuthorCity     string
	Title          string
	Content        string
	Status         string
	LikeCount      int32
	DislikeCount   int32
	CollectCount   int32
	CommentCount   int32
	Cover          string
	Ctime          int64
	Utime          int64
	Birthday       interface{}
	Tags           interface{}
	IsLike         bool
	IsDislike      bool
	IsCollect      bool
}

func (q *Queries) ListFollowingByCtime(ctx context.Context, arg ListFollowingByCtimeParams) ([]ListFollowingByCtimeRow, error) {
	rows, err := q.db.Query(ctx, listFollowingByCtime, arg.Column1, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFollowingByCtimeRow
	for rows.Next() {
		var i ListFollowingByCtimeRow
		if err := rows.Scan(
			&i.PostID,
			&i.AuthorID,
			&i.AuthorName,
			&i.AuthorAvatar,
			&i.AuthorProvince,
			&i.AuthorCity,
			&i.Title,
			&i.Content,
			&i.Status,
			&i.LikeCount,
			&i.DislikeCount,
			&i.CollectCount,
			&i.CommentCount,
			&i.Cover,
			&i.Ctime,
			&i.Utime,
			&i.Birthday,
			&i.Tags,
			&i.IsLike,
			&i.IsDislike,
			&i.IsCollect,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFollowingByHot = `-- name: ListFollowingByHot :many
SELECT
  p.post_id::text AS post_id,
  p.author_id::text AS author_id,
  COALESCE(ua.username, '') AS author_name,
  COALESCE(ua.avatar, '') AS author_avatar,
  COALESCE(ua.province, '') AS author_province,
  COALESCE(ua.city, '') AS author_city,
  p.title, p.content, p.status,
  p.like_count, p.dislike_count, p.collect_count, p.comment_count,
  p.cover, p.ctime, p.utime,
  COALESCE((
    SELECT b.birthday
    FROM "baby" b
    WHERE b.user_id = p.author_id
    ORDER BY b.ctime DESC
    LIMIT 1
  ), 0) AS birthday,
  COALESCE((
    SELECT array_agg(t.tag_name) FILTER (WHERE t.tag_name IS NOT NULL)
    FROM "post_tag" pt
    JOIN "tag" t ON t.tag_id = pt.tag_id
    WHERE pt.post_id = p.post_id
  ), '{}') AS tags,
  EXISTS(
    SELECT 1 FROM "like_dislike" ld
    WHERE ld.post_id = p.post_id AND ld.user_id = NULLIF($1, '')::uuid AND ld.type = 'like'
  ) AS is_like,
  EXISTS(
    SELECT 1 FROM "like_dislike" ld2
    WHERE ld2.post_id = p.post_id AND ld2.user_id = NULLIF($1, '')::uuid AND ld2.type = 'dislike'
  ) AS is_dislike,
  EXISTS(
    SELECT 1 FROM "collection" c2
    WHERE c2.post_id = p.post_id AND c2.user_id = NULLIF($1, '')::uuid
  ) AS is_collect
FROM "post" p
JOIN "user_follow" f ON f.followee = p.author_id
LEFT JOIN "user_addition" ua ON ua.user_id = p.author_id
WHERE f.follower = NULLIF($1, '')::uuid AND p.status = 'published'
ORDER BY (p.like_count*3 + p.comment_count*5 + p.collect_count*4) DESC, p.ctime DESC
LIMIT $2 OFFSET $3
`

type ListFollowingByHotParams struct {
	Column1 interface{}
	Limit   int32
	Offset  int32
}

type ListFollowingByHotRow struct {
	PostID         string
	AuthorID       string
	AuthorName     string
	AuthorAvatar   string
	AuthorProvince string
	AuthorCity     string
	Title          string
	Content        string
	Status         string
	LikeCount      int32
	DislikeCount   int32
	CollectCount   int32
	CommentCount   int32
	Cover          string
	Ctime          int64
	Utime          int64
	Birthday       interface{}
	Tags           interface{}
	IsLike         bool
	IsDislike      bool
	IsCollect      bool
}

func (q *Queries) ListFollowingByHot(ctx context.Context, arg ListFollowingByHotParams) ([]ListFollowingByHotRow, error) {
	rows, err := q.db.Query(ctx, listFollowingByHot, arg.Column1, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFollowingByHotRow
	for rows.Next() {
		var i ListFollowingByHotRow
		if err := rows.Scan(
			&i.PostID,
			&i.AuthorID,
			&i.AuthorName,
			&i.AuthorAvatar,
			&i.AuthorProvince,
			&i.AuthorCity,
			&i.Title,
			&i.Content,
			&i.Status,
			&i.LikeCount,
			&i.DislikeCount,
			&i.CollectCount,
			&i.CommentCount,
			&i.Cover,
			&i.Ctime,
			&i.Utime,
			&i.Birthday,
			&i.Tags,
			&i.IsLike,
			&i.IsDislike,
			&i.IsCollect,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHomeByCtime = `-- name: ListHomeByCtime :many
SELECT
  p.post_id::text AS post_id,
  p.author_id::text AS author_id,
  COALESCE(ua.username, '') AS author_name,
  COALESCE(ua.avatar, '') AS author_avatar,
  COALESCE(ua.province, '') AS author_province,
  COALESCE(ua.city, '') AS author_city,
  p.title, p.content, p.status,
  p.like_count, p.dislike_count, p.collect_count, p.comment_count,
  p.cover, p.ctime, p.utime,
  COALESCE((
    SELECT b.birthday
    FROM "baby" b
    WHERE b.user_id = p.author_id
    ORDER BY b.ctime DESC
    LIMIT 1
  ), 0) AS birthday,
  COALESCE((
    SELECT array_agg(t.tag_name) FILTER (WHERE t.tag_name IS NOT NULL)
    FROM "post_tag" pt
    JOIN "tag" t ON t.tag_id = pt.tag_id
    WHERE pt.post_id = p.post_id
  ), '{}') AS tags,
  EXISTS(
    SELECT 1 FROM "like_dislike" ld
    WHERE ld.post_id = p.post_id AND ld.user_id = NULLIF($3, '')::uuid AND ld.type = 'like'
  ) AS is_like,
  EXISTS(
    SELECT 1 FROM "like_dislike" ld2
    WHERE ld2.post_id = p.post_id AND ld2.user_id = NULLIF($3, '')::uuid AND ld2.type = 'dislike'
  ) AS is_dislike,
  EXISTS(
    SELECT 1 FROM "collection" c2
    WHERE c2.post_id = p.post_id AND c2.user_id = NULLIF($3, '')::uuid
  ) AS is_collect
FROM "post" p
LEFT JOIN "user_addition" ua ON ua.user_id = p.author_id
WHERE p.status = 'published'
ORDER BY p.ctime DESC
LIMIT $1 OFFSET $2
`

type ListHomeByCtimeParams struct {
	Limit   int32
	Offset  int32
	Column3 interface{}
}

type ListHomeByCtimeRow struct {
	PostID         string
	AuthorID       string
	AuthorName     string
	AuthorAvatar   string
	AuthorProvince string
	AuthorCity     string
	Title          string
	Content        string
	Status         string
	LikeCount      int32
	DislikeCount   int32
	CollectCount   int32
	CommentCount   int32
	Cover          string
	Ctime          int64
	Utime          int64
	Birthday       interface{}
	Tags           interface{}
	IsLike         bool
	IsDislike      bool
	IsCollect      bool
}

func (q *Queries) ListHomeByCtime(ctx context.Context, arg ListHomeByCtimeParams) ([]ListHomeByCtimeRow, error) {
	rows, err := q.db.Query(ctx, listHomeByCtime, arg.Limit, arg.Offset, arg.Column3)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListHomeByCtimeRow
	for rows.Next() {
		var i ListHomeByCtimeRow
		if err := rows.Scan(
			&i.PostID,
			&i.AuthorID,
			&i.AuthorName,
			&i.AuthorAvatar,
			&i.AuthorProvince,
			&i.AuthorCity,
			&i.Title,
			&i.Content,
			&i.Status,
			&i.LikeCount,
			&i.DislikeCount,
			&i.CollectCount,
			&i.CommentCount,
			&i.Cover,
			&i.Ctime,
			&i.Utime,
			&i.Birthday,
			&i.Tags,
			&i.IsLike,
			&i.IsDislike,
			&i.IsCollect,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHomeByHot = `-- name: ListHomeByHot :many
SELECT
  p.post_id::text AS post_id,
  p.author_id::text AS author_id,
  COALESCE(ua.username, '') AS author_name,
  COALESCE(ua.avatar, '') AS author_avatar,
  COALESCE(ua.province, '') AS author_province,
  COALESCE(ua.city, '') AS author_city,
  p.title, p.content, p.status,
  p.like_count, p.dislike_count, p.collect_count, p.comment_count,
  p.cover, p.ctime, p.utime,
  COALESCE((
    SELECT b.birthday
    FROM "baby" b
    WHERE b.user_id = p.author_id
    ORDER BY b.ctime DESC
    LIMIT 1
  ), 0) AS birthday,
  COALESCE((
    SELECT array_agg(t.tag_name) FILTER (WHERE t.tag_name IS NOT NULL)
    FROM "post_tag" pt
    JOIN "tag" t ON t.tag_id = pt.tag_id
    WHERE pt.post_id = p.post_id
  ), '{}') AS tags,
  EXISTS(
    SELECT 1 FROM "like_dislike" ld
    WHERE ld.post_id = p.post_id AND ld.user_id = NULLIF($3, '')::uuid AND ld.type = 'like'
  ) AS is_like,
  EXISTS(
    SELECT 1 FROM "like_dislike" ld2
    WHERE ld2.post_id = p.post_id AND ld2.user_id = NULLIF($3, '')::uuid AND ld2.type = 'dislike'
  ) AS is_dislike,
  EXISTS(
    SELECT 1 FROM "collection" c2
    WHERE c2.post_id = p.post_id AND c2.user_id = NULLIF($3, '')::uuid
  ) AS is_collect
FROM "post" p
LEFT JOIN "user_addition" ua ON ua.user_id = p.author_id
WHERE p.status = 'published'
ORDER BY (p.like_count*3 + p.comment_count*5 + p.collect_count*4) DESC, p.ctime DESC
LIMIT $1 OFFSET $2
`

type ListHomeByHotParams struct {
	Limit   int32
	Offset  int32
	Column3 interface{}
}

type ListHomeByHotRow struct {
	PostID         string
	AuthorID       string
	AuthorName     string
	AuthorAvatar   string
	AuthorProvince string
	AuthorCity     string
	Title          string
	Content        string
	Status         string
	LikeCount      int32
	DislikeCount   int32
	CollectCount   int32
	CommentCount   int32
	Cover          string
	Ctime          int64
	Utime          int64
	Birthday       interface{}
	Tags           interface{}
	IsLike         bool
	IsDislike      bool
	IsCollect      bool
}

func (q *Queries) ListHomeByHot(ctx context.Context, arg ListHomeByHotParams) ([]ListHomeByHotRow, error) {
	rows, err := q.db.Query(ctx, listHomeByHot, arg.Limit, arg.Offset, arg.Column3)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListHomeByHotRow
	for rows.Next() {
		var i ListHomeByHotRow
		if err := rows.Scan(
			&i.PostID,
			&i.AuthorID,
			&i.AuthorName,
			&i.AuthorAvatar,
			&i.AuthorProvince,
			&i.AuthorCity,
			&i.Title,
			&i.Content,
			&i.Status,
			&i.LikeCount,
			&i.DislikeCount,
			&i.CollectCount,
			&i.CommentCount,
			&i.Cover,
			&i.Ctime,
			&i.Utime,
			&i.Birthday,
			&i.Tags,
			&i.IsLike,
			&i.IsDislike,
			&i.IsCollect,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHomeByRandom = `-- name: ListHomeByRandom :many
SELECT
  p.post_id::text AS post_id,
  p.author_id::text AS author_id,
  COALESCE(ua.username, '') AS author_name,
  COALESCE(ua.avatar, '') AS author_avatar,
  COALESCE(ua.province, '') AS author_province,
  COALESCE(ua.city, '') AS author_city,
  p.title, p.content, p.status,
  p.like_count, p.dislike_count, p.collect_count, p.comment_count,
  p.cover, p.ctime, p.utime,
  COALESCE((
    SELECT b.birthday
    FROM "baby" b
    WHERE b.user_id = p.author_id
    ORDER BY b.ctime DESC
    LIMIT 1
  ), 0) AS birthday,
  COALESCE((
    SELECT array_agg(t.tag_name) FILTER (WHERE t.tag_name IS NOT NULL)
    FROM "post_tag" pt
    JOIN "tag" t ON t.tag_id = pt.tag_id
    WHERE pt.post_id = p.post_id
  ), '{}') AS tags,
  EXISTS(
    SELECT 1 FROM "like_dislike" ld
    WHERE ld.post_id = p.post_id AND ld.user_id = NULLIF($4, '')::uuid AND ld.type = 'like'
  ) AS is_like,
  EXISTS(
    SELECT 1 FROM "like_dislike" ld2
    WHERE ld2.post_id = p.post_id AND ld2.user_id = NULLIF($4, '')::uuid AND ld2.type = 'dislike'
  ) AS is_dislike,
  EXISTS(
    SELECT 1 FROM "collection" c2
    WHERE c2.post_id = p.post_id AND c2.user_id = NULLIF($4, '')::uuid
  ) AS is_collect
FROM "post" p
LEFT JOIN "user_addition" ua ON ua.user_id = p.author_id
WHERE p.status = 'published'
ORDER BY md5(p.post_id::text || ($1)::text)
LIMIT $2 OFFSET $3
`

type ListHomeByRandomParams struct {
	Column1 string
	Limit   int32
	Offset  int32
	Column4 interface{}
}

type ListHomeByRandomRow struct {
	PostID         string
	AuthorID       string
	AuthorName     string
	AuthorAvatar   string
	AuthorProvince string
	AuthorCity     string
	Title          string
	Content        string
	Status         string
	LikeCount      int32
	DislikeCount   int32
	CollectCount   int32
	CommentCount   int32
	Cover          string
	Ctime          int64
	Utime          int64
	Birthday       interface{}
	Tags           interface{}
	IsLike         bool
	IsDislike      bool
	IsCollect      bool
}

func (q *Queries) ListHomeByRandom(ctx context.Context, arg ListHomeByRandomParams) ([]ListHomeByRandomRow, error) {
	rows, err := q.db.Query(ctx, listHomeByRandom,
		arg.Column1,
		arg.Limit,
		arg.Offset,
		arg.Column4,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListHomeByRandomRow
	for rows.Next() {
		var i ListHomeByRandomRow
		if err := rows.Scan(
			&i.PostID,
			&i.AuthorID,
			&i.AuthorName,
			&i.AuthorAvatar,
			&i.AuthorProvince,
			&i.AuthorCity,
			&i.Title,
			&i.Content,
			&i.Status,
			&i.LikeCount,
			&i.DislikeCount,
			&i.CollectCount,
			&i.CommentCount,
			&i.Cover,
			&i.Ctime,
			&i.Utime,
			&i.Birthday,
			&i.Tags,
			&i.IsLike,
			&i.IsDislike,
			&i.IsCollect,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHomePosts = `-- name: ListHomePosts :many
SELECT
  p.post_id::text AS post_id,
  p.author_id::text AS author_id,
  COALESCE(ua.username, '') AS author_name,
  COALESCE(ua.avatar, '') AS author_avatar,
  COALESCE(ua.province, '') AS author_province,
  COALESCE(ua.city, '') AS author_city,
  p.title, p.content, p.status,
  p.like_count, p.dislike_count, p.collect_count, p.comment_count,
  p.cover, p.ctime, p.utime,
  COALESCE((
    SELECT b.birthday
    FROM "baby" b
    WHERE b.user_id = p.author_id
    ORDER BY b.ctime DESC
    LIMIT 1
  ), 0) AS birthday,
  COALESCE((
    SELECT array_agg(t.tag_name) FILTER (WHERE t.tag_name IS NOT NULL)
    FROM "post_tag" pt
    JOIN "tag" t ON t.tag_id = pt.tag_id
    WHERE pt.post_id = p.post_id
  ), '{}') AS tags,
  EXISTS(
    SELECT 1 FROM "like_dislike" ld
    WHERE ld.post_id = p.post_id AND ld.user_id = NULLIF($5, '')::uuid AND ld.type = 'like'
  ) AS is_like,
  EXISTS(
    SELECT 1 FROM "like_dislike" ld2
    WHERE ld2.post_id = p.post_id AND ld2.user_id = NULLIF($5, '')::uuid AND ld2.type = 'dislike'
  ) AS is_dislike,
  EXISTS(
    SELECT 1 FROM "collection" c2
    WHERE c2.post_id = p.post_id AND c2.user_id = NULLIF($5, '')::uuid
  ) AS is_collect
FROM "post" p
LEFT JOIN "user_addition" ua ON ua.user_id = p.author_id
WHERE p.status = $1
ORDER BY 
  CASE WHEN $2 = 'hot' THEN (p.like_count*3 + p.comment_count*5 + p.collect_count*4) ELSE p.ctime END DESC,
  p.ctime DESC
LIMIT $3 OFFSET $4
`

type ListHomePostsParams struct {
	Status  string
	Column2 interface{}
	Limit   int32
	Offset  int32
	Column5 interface{}
}

type ListHomePostsRow struct {
	PostID         string
	AuthorID       string
	AuthorName     string
	AuthorAvatar   string
	AuthorProvince string
	AuthorCity     string
	Title          string
	Content        string
	Status         string
	LikeCount      int32
	DislikeCount   int32
	CollectCount   int32
	CommentCount   int32
	Cover          string
	Ctime          int64
	Utime          int64
	Birthday       interface{}
	Tags           interface{}
	IsLike         bool
	IsDislike      bool
	IsCollect      bool
}

func (q *Queries) ListHomePosts(ctx context.Context, arg ListHomePostsParams) ([]ListHomePostsRow, error) {
	rows, err := q.db.Query(ctx, listHomePosts,
		arg.Status,
		arg.Column2,
		arg.Limit,
		arg.Offset,
		arg.Column5,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListHomePostsRow
	for rows.Next() {
		var i ListHomePostsRow
		if err := rows.Scan(
			&i.PostID,
			&i.AuthorID,
			&i.AuthorName,
			&i.AuthorAvatar,
			&i.AuthorProvince,
			&i.AuthorCity,
			&i.Title,
			&i.Content,
			&i.Status,
			&i.LikeCount,
			&i.DislikeCount,
			&i.CollectCount,
			&i.CommentCount,
			&i.Cover,
			&i.Ctime,
			&i.Utime,
			&i.Birthday,
			&i.Tags,
			&i.IsLike,
			&i.IsDislike,
			&i.IsCollect,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMilestonesByAuthor = `-- name: ListMilestonesByAuthor :many
SELECT
  p.post_id::text AS post_id,
  p.author_id::text AS author_id,
  COALESCE(ua.username, '') AS author_name,
  COALESCE(ua.avatar, '') AS author_avatar,
  COALESCE(ua.province, '') AS author_province,
  COALESCE(ua.city, '') AS author_city,
  p.title, p.content, p.status,
  p.like_count, p.dislike_count, p.collect_count, p.comment_count,
  p.cover, p.ctime, p.utime,
  COALESCE((
    SELECT b.birthday
    FROM "baby" b
    WHERE b.user_id = p.author_id
    ORDER BY b.ctime DESC
    LIMIT 1
  ), 0) AS birthday,
  COALESCE((
    SELECT array_agg(t.tag_name) FILTER (WHERE t.tag_name IS NOT NULL)
    FROM "post_tag" pt2
    JOIN "tag" t ON t.tag_id = pt2.tag_id
    WHERE pt2.post_id = p.post_id
  ), '{}') AS tags,
  EXISTS(
    SELECT 1 FROM "like_dislike" ld
    WHERE ld.post_id = p.post_id AND ld.user_id = NULLIF($1::text, '')::uuid AND ld.type = 'like'
  ) AS is_like,
  EXISTS(
    SELECT 1 FROM "like_dislike" ld2
    WHERE ld2.post_id = p.post_id AND ld2.user_id = NULLIF($1::text, '')::uuid AND ld2.type = 'dislike'
  ) AS is_dislike,
  EXISTS(
    SELECT 1 FROM "collection" c2
    WHERE c2.post_id = p.post_id AND c2.user_id = NULLIF($1::text, '')::uuid
  ) AS is_collect
FROM "post" p
LEFT JOIN "user_addition" ua ON ua.user_id = p.author_id
WHERE p.author_id = NULLIF($1::text, '')::uuid AND p.status = 'milestone'
ORDER BY p.ctime DESC
LIMIT $2 OFFSET $3
`

type ListMilestonesByAuthorParams struct {
	Column1 string
	Limit   int32
	Offset  int32
}

type ListMilestonesByAuthorRow struct {
	PostID         string
	AuthorID       string
	AuthorName     string
	AuthorAvatar   string
	AuthorProvince string
	AuthorCity     string
	Title          string
	Content        string
	Status         string
	LikeCount      int32
	DislikeCount   int32
	CollectCount   int32
	CommentCount   int32
	Cover          string
	Ctime          int64
	Utime          int64
	Birthday       interface{}
	Tags           interface{}
	IsLike         bool
	IsDislike      bool
	IsCollect      bool
}

func (q *Queries) ListMilestonesByAuthor(ctx context.Context, arg ListMilestonesByAuthorParams) ([]ListMilestonesByAuthorRow, error) {
	rows, err := q.db.Query(ctx, listMilestonesByAuthor, arg.Column1, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMilestonesByAuthorRow
	for rows.Next() {
		var i ListMilestonesByAuthorRow
		if err := rows.Scan(
			&i.PostID,
			&i.AuthorID,
			&i.AuthorName,
			&i.AuthorAvatar,
			&i.AuthorProvince,
			&i.AuthorCity,
			&i.Title,
			&i.Content,
			&i.Status,
			&i.LikeCount,
			&i.DislikeCount,
			&i.CollectCount,
			&i.CommentCount,
			&i.Cover,
			&i.Ctime,
			&i.Utime,
			&i.Birthday,
			&i.Tags,
			&i.IsLike,
			&i.IsDislike,
			&i.IsCollect,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPostCommentsByCtime = `-- name: ListPostCommentsByCtime :many
SELECT
  c.comment_id::text AS comment_id,
  c.user_id::text AS user_id,
  COALESCE(ua.username, '') AS username,
  COALESCE(ua.avatar, '') AS avatar,
  c.content,
  c.like_count,
  c.reply_count,
  c.ctime,
  c.utime,
  EXISTS(
    SELECT 1 FROM "comment_like" cl
    WHERE cl.comment_id = c.comment_id AND cl.user_id = NULLIF($4, '')::uuid
  ) AS has_liked
FROM "comment" c
LEFT JOIN "user_addition" ua ON ua.user_id = c.user_id
WHERE c.post_id = $1 AND c.parent_id IS NULL AND c.status = 'visible'
ORDER BY c.ctime DESC
LIMIT $2 OFFSET $3
`

type ListPostCommentsByCtimeParams struct {
	PostID  pgtype.UUID
	Limit   int32
	Offset  int32
	Column4 interface{}
}

type ListPostCommentsByCtimeRow struct {
	CommentID  string
	UserID     string
	Username   string
	Avatar     string
	Content    pgtype.Text
	LikeCount  int32
	ReplyCount int32
	Ctime      int64
	Utime      int64
	HasLiked   bool
}

func (q *Queries) ListPostCommentsByCtime(ctx context.Context, arg ListPostCommentsByCtimeParams) ([]ListPostCommentsByCtimeRow, error) {
	rows, err := q.db.Query(ctx, listPostCommentsByCtime,
		arg.PostID,
		arg.Limit,
		arg.Offset,
		arg.Column4,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPostCommentsByCtimeRow
	for rows.Next() {
		var i ListPostCommentsByCtimeRow
		if err := rows.Scan(
			&i.CommentID,
			&i.UserID,
			&i.Username,
			&i.Avatar,
			&i.Content,
			&i.LikeCount,
			&i.ReplyCount,
			&i.Ctime,
			&i.Utime,
			&i.HasLiked,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPostCommentsByHot = `-- name: ListPostCommentsByHot :many
SELECT
  c.comment_id::text AS comment_id,
  c.user_id::text AS user_id,
  COALESCE(ua.username, '') AS username,
  COALESCE(ua.avatar, '') AS avatar,
  c.content,
  c.like_count,
  c.reply_count,
  c.ctime,
  c.utime,
  EXISTS(
    SELECT 1 FROM "comment_like" cl
    WHERE cl.comment_id = c.comment_id AND cl.user_id = NULLIF($4, '')::uuid
  ) AS has_liked
FROM "comment" c
LEFT JOIN "user_addition" ua ON ua.user_id = c.user_id
WHERE c.post_id = $1 AND c.parent_id IS NULL AND c.status = 'visible'
ORDER BY (c.like_count*3 + c.reply_count*5) DESC, c.ctime DESC
LIMIT $2 OFFSET $3
`

type ListPostCommentsByHotParams struct {
	PostID  pgtype.UUID
	Limit   int32
	Offset  int32
	Column4 interface{}
}

type ListPostCommentsByHotRow struct {
	CommentID  string
	UserID     string
	Username   string
	Avatar     string
	Content    pgtype.Text
	LikeCount  int32
	ReplyCount int32
	Ctime      int64
	Utime      int64
	HasLiked   bool
}

func (q *Queries) ListPostCommentsByHot(ctx context.Context, arg ListPostCommentsByHotParams) ([]ListPostCommentsByHotRow, error) {
	rows, err := q.db.Query(ctx, listPostCommentsByHot,
		arg.PostID,
		arg.Limit,
		arg.Offset,
		arg.Column4,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPostCommentsByHotRow
	for rows.Next() {
		var i ListPostCommentsByHotRow
		if err := rows.Scan(
			&i.CommentID,
			&i.UserID,
			&i.Username,
			&i.Avatar,
			&i.Content,
			&i.LikeCount,
			&i.ReplyCount,
			&i.Ctime,
			&i.Utime,
			&i.HasLiked,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPostsByAuthor = `-- name: ListPostsByAuthor :many
SELECT
  p.post_id::text AS post_id,
  p.author_id::text AS author_id,
  COALESCE(ua.username, '') AS author_name,
  COALESCE(ua.avatar, '') AS author_avatar,
  COALESCE(ua.province, '') AS author_province,
  COALESCE(ua.city, '') AS author_city,
  p.title, p.content, p.status,
  p.like_count, p.dislike_count, p.collect_count, p.comment_count,
  p.cover, p.ctime, p.utime,
  COALESCE((
    SELECT b.birthday
    FROM "baby" b
    WHERE b.user_id = p.author_id
    ORDER BY b.ctime DESC
    LIMIT 1
  ), 0) AS birthday,
  COALESCE((
    SELECT array_agg(t.tag_name) FILTER (WHERE t.tag_name IS NOT NULL)
    FROM "post_tag" pt2
    JOIN "tag" t ON t.tag_id = pt2.tag_id
    WHERE pt2.post_id = p.post_id
  ), '{}') AS tags,
  EXISTS(
    SELECT 1 FROM "like_dislike" ld
    WHERE ld.post_id = p.post_id AND ld.user_id = NULLIF($1::text, '')::uuid AND ld.type = 'like'
  ) AS is_like,
  EXISTS(
    SELECT 1 FROM "like_dislike" ld2
    WHERE ld2.post_id = p.post_id AND ld2.user_id = NULLIF($1::text, '')::uuid AND ld2.type = 'dislike'
  ) AS is_dislike,
  EXISTS(
    SELECT 1 FROM "collection" c2
    WHERE c2.post_id = p.post_id AND c2.user_id = NULLIF($1::text, '')::uuid
  ) AS is_collect
FROM "post" p
LEFT JOIN "user_addition" ua ON ua.user_id = p.author_id
WHERE p.author_id = NULLIF($1::text, '')::uuid AND p.status = 'published'
ORDER BY p.ctime DESC
LIMIT $2 OFFSET $3
`

type ListPostsByAuthorParams struct {
	Column1 string
	Limit   int32
	Offset  int32
}

type ListPostsByAuthorRow struct {
	PostID         string
	AuthorID       string
	AuthorName     string
	AuthorAvatar   string
	AuthorProvince string
	AuthorCity     string
	Title          string
	Content        string
	Status         string
	LikeCount      int32
	DislikeCount   int32
	CollectCount   int32
	CommentCount   int32
	Cover          string
	Ctime          int64
	Utime          int64
	Birthday       interface{}
	Tags           interface{}
	IsLike         bool
	IsDislike      bool
	IsCollect      bool
}

func (q *Queries) ListPostsByAuthor(ctx context.Context, arg ListPostsByAuthorParams) ([]ListPostsByAuthorRow, error) {
	rows, err := q.db.Query(ctx, listPostsByAuthor, arg.Column1, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPostsByAuthorRow
	for rows.Next() {
		var i ListPostsByAuthorRow
		if err := rows.Scan(
			&i.PostID,
			&i.AuthorID,
			&i.AuthorName,
			&i.AuthorAvatar,
			&i.AuthorProvince,
			&i.AuthorCity,
			&i.Title,
			&i.Content,
			&i.Status,
			&i.LikeCount,
			&i.DislikeCount,
			&i.CollectCount,
			&i.CommentCount,
			&i.Cover,
			&i.Ctime,
			&i.Utime,
			&i.Birthday,
			&i.Tags,
			&i.IsLike,
			&i.IsDislike,
			&i.IsCollect,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPostsByAuthorHot = `-- name: ListPostsByAuthorHot :many
SELECT
  p.post_id::text AS post_id,
  p.author_id::text AS author_id,
  COALESCE(ua.username, '') AS author_name,
  COALESCE(ua.avatar, '') AS author_avatar,
  COALESCE(ua.province, '') AS author_province,
  COALESCE(ua.city, '') AS author_city,
  p.title, p.content, p.status,
  p.like_count, p.dislike_count, p.collect_count, p.comment_count,
  p.cover, p.ctime, p.utime,
  COALESCE((
    SELECT b.birthday
    FROM "baby" b
    WHERE b.user_id = p.author_id
    ORDER BY b.ctime DESC
    LIMIT 1
  ), 0) AS birthday,
  COALESCE((
    SELECT array_agg(t.tag_name) FILTER (WHERE t.tag_name IS NOT NULL)
    FROM "post_tag" pt2
    JOIN "tag" t ON t.tag_id = pt2.tag_id
    WHERE pt2.post_id = p.post_id
  ), '{}') AS tags,
  EXISTS(
    SELECT 1 FROM "like_dislike" ld
    WHERE ld.post_id = p.post_id AND ld.user_id = NULLIF($1::text, '')::uuid AND ld.type = 'like'
  ) AS is_like,
  EXISTS(
    SELECT 1 FROM "like_dislike" ld2
    WHERE ld2.post_id = p.post_id AND ld2.user_id = NULLIF($1::text, '')::uuid AND ld2.type = 'dislike'
  ) AS is_dislike,
  EXISTS(
    SELECT 1 FROM "collection" c2
    WHERE c2.post_id = p.post_id AND c2.user_id = NULLIF($1::text, '')::uuid
  ) AS is_collect
FROM "post" p
LEFT JOIN "user_addition" ua ON ua.user_id = p.author_id
WHERE p.author_id = NULLIF($1::text, '')::uuid AND p.status = 'published'
ORDER BY (p.like_count*3 + p.comment_count*5 + p.collect_count*4) DESC, p.ctime DESC
LIMIT $2 OFFSET $3
`

type ListPostsByAuthorHotParams struct {
	Column1 string
	Limit   int32
	Offset  int32
}

type ListPostsByAuthorHotRow struct {
	PostID         string
	AuthorID       string
	AuthorName     string
	AuthorAvatar   string
	AuthorProvince string
	AuthorCity     string
	Title          string
	Content        string
	Status         string
	LikeCount      int32
	DislikeCount   int32
	CollectCount   int32
	CommentCount   int32
	Cover          string
	Ctime          int64
	Utime          int64
	Birthday       interface{}
	Tags           interface{}
	IsLike         bool
	IsDislike      bool
	IsCollect      bool
}

func (q *Queries) ListPostsByAuthorHot(ctx context.Context, arg ListPostsByAuthorHotParams) ([]ListPostsByAuthorHotRow, error) {
	rows, err := q.db.Query(ctx, listPostsByAuthorHot, arg.Column1, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPostsByAuthorHotRow
	for rows.Next() {
		var i ListPostsByAuthorHotRow
		if err := rows.Scan(
			&i.PostID,
			&i.AuthorID,
			&i.AuthorName,
			&i.AuthorAvatar,
			&i.AuthorProvince,
			&i.AuthorCity,
			&i.Title,
			&i.Content,
			&i.Status,
			&i.LikeCount,
			&i.DislikeCount,
			&i.CollectCount,
			&i.CommentCount,
			&i.Cover,
			&i.Ctime,
			&i.Utime,
			&i.Birthday,
			&i.Tags,
			&i.IsLike,
			&i.IsDislike,
			&i.IsCollect,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPostsByTag = `-- name: ListPostsByTag :many
SELECT
  p.post_id::text AS post_id,
  p.author_id::text AS author_id,
  COALESCE(ua.username, '') AS author_name,
  COALESCE(ua.avatar, '') AS author_avatar,
  COALESCE(ua.province, '') AS author_province,
  COALESCE(ua.city, '') AS author_city,
  p.title, p.content, p.status,
  p.like_count, p.dislike_count, p.collect_count, p.comment_count,
  p.cover, p.ctime, p.utime,
  COALESCE((
    SELECT b.birthday
    FROM "baby" b
    WHERE b.user_id = p.author_id
    ORDER BY b.ctime DESC
    LIMIT 1
  ), 0) AS birthday,
  COALESCE((
    SELECT array_agg(t.tag_name) FILTER (WHERE t.tag_name IS NOT NULL)
    FROM "post_tag" pt2
    JOIN "tag" t ON t.tag_id = pt2.tag_id
    WHERE pt2.post_id = p.post_id
  ), '{}') AS tags,
  EXISTS(
    SELECT 1 FROM "like_dislike" ld
    WHERE ld.post_id = p.post_id AND ld.user_id = NULLIF($5, '')::uuid AND ld.type = 'like'
  ) AS is_like,
  EXISTS(
    SELECT 1 FROM "like_dislike" ld2
    WHERE ld2.post_id = p.post_id AND ld2.user_id = NULLIF($5, '')::uuid AND ld2.type = 'dislike'
  ) AS is_dislike,
  EXISTS(
    SELECT 1 FROM "collection" c2
    WHERE c2.post_id = p.post_id AND c2.user_id = NULLIF($5, '')::uuid
  ) AS is_collect
FROM "post" p
JOIN "post_tag" pt ON pt.post_id = p.post_id
LEFT JOIN "user_addition" ua ON ua.user_id = p.author_id
WHERE pt.tag_id = $1 AND p.status = $2
ORDER BY p.ctime DESC
LIMIT $3 OFFSET $4
`

type ListPostsByTagParams struct {
	TagID   pgtype.UUID
	Status  string
	Limit   int32
	Offset  int32
	Column5 interface{}
}

type ListPostsByTagRow struct {
	PostID         string
	AuthorID       string
	AuthorName     string
	AuthorAvatar   string
	AuthorProvince string
	AuthorCity     string
	Title          string
	Content        string
	Status         string
	LikeCount      int32
	DislikeCount   int32
	CollectCount   int32
	CommentCount   int32
	Cover          string
	Ctime          int64
	Utime          int64
	Birthday       interface{}
	Tags           interface{}
	IsLike         bool
	IsDislike      bool
	IsCollect      bool
}

func (q *Queries) ListPostsByTag(ctx context.Context, arg ListPostsByTagParams) ([]ListPostsByTagRow, error) {
	rows, err := q.db.Query(ctx, listPostsByTag,
		arg.TagID,
		arg.Status,
		arg.Limit,
		arg.Offset,
		arg.Column5,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPostsByTagRow
	for rows.Next() {
		var i ListPostsByTagRow
		if err := rows.Scan(
			&i.PostID,
			&i.AuthorID,
			&i.AuthorName,
			&i.AuthorAvatar,
			&i.AuthorProvince,
			&i.AuthorCity,
			&i.Title,
			&i.Content,
			&i.Status,
			&i.LikeCount,
			&i.DislikeCount,
			&i.CollectCount,
			&i.CommentCount,
			&i.Cover,
			&i.Ctime,
			&i.Utime,
			&i.Birthday,
			&i.Tags,
			&i.IsLike,
			&i.IsDislike,
			&i.IsCollect,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPostsByTagHot = `-- name: ListPostsByTagHot :many
SELECT
  p.post_id::text AS post_id,
  p.author_id::text AS author_id,
  COALESCE(ua.username, '') AS author_name,
  COALESCE(ua.avatar, '') AS author_avatar,
  COALESCE(ua.province, '') AS author_province,
  COALESCE(ua.city, '') AS author_city,
  p.title, p.content, p.status,
  p.like_count, p.dislike_count, p.collect_count, p.comment_count,
  p.cover, p.ctime, p.utime,
  COALESCE((
    SELECT b.birthday
    FROM "baby" b
    WHERE b.user_id = p.author_id
    ORDER BY b.ctime DESC
    LIMIT 1
  ), 0) AS birthday,
  COALESCE((
    SELECT array_agg(t.tag_name) FILTER (WHERE t.tag_name IS NOT NULL)
    FROM "post_tag" pt2
    JOIN "tag" t ON t.tag_id = pt2.tag_id
    WHERE pt2.post_id = p.post_id
  ), '{}') AS tags,
  EXISTS(
    SELECT 1 FROM "like_dislike" ld
    WHERE ld.post_id = p.post_id AND ld.user_id = NULLIF($4, '')::uuid AND ld.type = 'like'
  ) AS is_like,
  EXISTS(
    SELECT 1 FROM "like_dislike" ld2
    WHERE ld2.post_id = p.post_id AND ld2.user_id = NULLIF($4, '')::uuid AND ld2.type = 'dislike'
  ) AS is_dislike,
  EXISTS(
    SELECT 1 FROM "collection" c2
    WHERE c2.post_id = p.post_id AND c2.user_id = NULLIF($4, '')::uuid
  ) AS is_collect
FROM "post" p
JOIN "post_tag" pt ON pt.post_id = p.post_id
LEFT JOIN "user_addition" ua ON ua.user_id = p.author_id
WHERE pt.tag_id = $1 AND p.status = 'published'
ORDER BY (p.like_count*3 + p.comment_count*5 + p.collect_count*4) DESC, p.ctime DESC
LIMIT $2 OFFSET $3
`

type ListPostsByTagHotParams struct {
	TagID   pgtype.UUID
	Limit   int32
	Offset  int32
	Column4 interface{}
}

type ListPostsByTagHotRow struct {
	PostID         string
	AuthorID       string
	AuthorName     string
	AuthorAvatar   string
	AuthorProvince string
	AuthorCity     string
	Title          string
	Content        string
	Status         string
	LikeCount      int32
	DislikeCount   int32
	CollectCount   int32
	CommentCount   int32
	Cover          string
	Ctime          int64
	Utime          int64
	Birthday       interface{}
	Tags           interface{}
	IsLike         bool
	IsDislike      bool
	IsCollect      bool
}

func (q *Queries) ListPostsByTagHot(ctx context.Context, arg ListPostsByTagHotParams) ([]ListPostsByTagHotRow, error) {
	rows, err := q.db.Query(ctx, listPostsByTagHot,
		arg.TagID,
		arg.Limit,
		arg.Offset,
		arg.Column4,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPostsByTagHotRow
	for rows.Next() {
		var i ListPostsByTagHotRow
		if err := rows.Scan(
			&i.PostID,
			&i.AuthorID,
			&i.AuthorName,
			&i.AuthorAvatar,
			&i.AuthorProvince,
			&i.AuthorCity,
			&i.Title,
			&i.Content,
			&i.Status,
			&i.LikeCount,
			&i.DislikeCount,
			&i.CollectCount,
			&i.CommentCount,
			&i.Cover,
			&i.Ctime,
			&i.Utime,
			&i.Birthday,
			&i.Tags,
			&i.IsLike,
			&i.IsDislike,
			&i.IsCollect,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTags = `-- name: ListTags :many
SELECT 
  tag_id::text AS tag_id,
  tag_name,
  COALESCE(description, '') AS description
FROM "tag"
WHERE ($1 = '' OR tag_name ILIKE '%' || $1 || '%')
ORDER BY ctime DESC
LIMIT $2 OFFSET $3
`

type ListTagsParams struct {
	Column1 interface{}
	Limit   int32
	Offset  int32
}

type ListTagsRow struct {
	TagID       string
	TagName     string
	Description string
}

// admin
func (q *Queries) ListTags(ctx context.Context, arg ListTagsParams) ([]ListTagsRow, error) {
	rows, err := q.db.Query(ctx, listTags, arg.Column1, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTagsRow
	for rows.Next() {
		var i ListTagsRow
		if err := rows.Scan(&i.TagID, &i.TagName, &i.Description); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const publishPost = `-- name: PublishPost :execrows
UPDATE "post"
SET status = 'published', utime = $3
WHERE post_id = $1 AND author_id = $2 AND status = 'draft'
`

type PublishPostParams struct {
	PostID   pgtype.UUID
	AuthorID pgtype.UUID
	Utime    int64
}

func (q *Queries) PublishPost(ctx context.Context, arg PublishPostParams) (int64, error) {
	result, err := q.db.Exec(ctx, publishPost, arg.PostID, arg.AuthorID, arg.Utime)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const searchPosts = `-- name: SearchPosts :many
SELECT
  p.post_id::text AS post_id,
  p.author_id::text AS author_id,
  COALESCE(ua.username, '') AS author_name,
  COALESCE(ua.avatar, '') AS author_avatar,
  COALESCE(ua.province, '') AS author_province,
  COALESCE(ua.city, '') AS author_city,
  p.title, p.content, p.status,
  p.like_count, p.dislike_count, p.collect_count, p.comment_count,
  p.cover, p.ctime, p.utime,
  COALESCE((
    SELECT b.birthday
    FROM "baby" b
    WHERE b.user_id = p.author_id
    ORDER BY b.ctime DESC
    LIMIT 1
  ), 0) AS birthday,
  COALESCE((
    SELECT array_agg(t.tag_name) FILTER (WHERE t.tag_name IS NOT NULL)
    FROM "post_tag" pt
    JOIN "tag" t ON t.tag_id = pt.tag_id
    WHERE pt.post_id = p.post_id
  ), '{}') AS tags,
  EXISTS(
    SELECT 1 FROM "like_dislike" ld
    WHERE ld.post_id = p.post_id AND ld.user_id = NULLIF($5, '')::uuid AND ld.type = 'like'
  ) AS is_like,
  EXISTS(
    SELECT 1 FROM "like_dislike" ld2
    WHERE ld2.post_id = p.post_id AND ld2.user_id = NULLIF($5, '')::uuid AND ld2.type = 'dislike'
  ) AS is_dislike,
  EXISTS(
    SELECT 1 FROM "collection" c2
    WHERE c2.post_id = p.post_id AND c2.user_id = NULLIF($5, '')::uuid
  ) AS is_collect
FROM "post" p
LEFT JOIN "user_addition" ua ON ua.user_id = p.author_id
WHERE p.title ILIKE $1 AND p.status = $2
ORDER BY p.ctime DESC
LIMIT $3 OFFSET $4
`

type SearchPostsParams struct {
	Title   string
	Status  string
	Limit   int32
	Offset  int32
	Column5 interface{}
}

type SearchPostsRow struct {
	PostID         string
	AuthorID       string
	AuthorName     string
	AuthorAvatar   string
	AuthorProvince string
	AuthorCity     string
	Title          string
	Content        string
	Status         string
	LikeCount      int32
	DislikeCount   int32
	CollectCount   int32
	CommentCount   int32
	Cover          string
	Ctime          int64
	Utime          int64
	Birthday       interface{}
	Tags           interface{}
	IsLike         bool
	IsDislike      bool
	IsCollect      bool
}

func (q *Queries) SearchPosts(ctx context.Context, arg SearchPostsParams) ([]SearchPostsRow, error) {
	rows, err := q.db.Query(ctx, searchPosts,
		arg.Title,
		arg.Status,
		arg.Limit,
		arg.Offset,
		arg.Column5,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchPostsRow
	for rows.Next() {
		var i SearchPostsRow
		if err := rows.Scan(
			&i.PostID,
			&i.AuthorID,
			&i.AuthorName,
			&i.AuthorAvatar,
			&i.AuthorProvince,
			&i.AuthorCity,
			&i.Title,
			&i.Content,
			&i.Status,
			&i.LikeCount,
			&i.DislikeCount,
			&i.CollectCount,
			&i.CommentCount,
			&i.Cover,
			&i.Ctime,
			&i.Utime,
			&i.Birthday,
			&i.Tags,
			&i.IsLike,
			&i.IsDislike,
			&i.IsCollect,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchPostsByTitleAndTagCtime = `-- name: SearchPostsByTitleAndTagCtime :many
SELECT
  p.post_id::text AS post_id,
  p.author_id::text AS author_id,
  COALESCE(ua.username, '') AS author_name,
  COALESCE(ua.avatar, '') AS author_avatar,
  COALESCE(ua.province, '') AS author_province,
  COALESCE(ua.city, '') AS author_city,
  p.title, p.content, p.status,
  p.like_count, p.dislike_count, p.collect_count, p.comment_count,
  p.cover, p.ctime, p.utime,
  COALESCE((
    SELECT b.birthday
    FROM "baby" b
    WHERE b.user_id = p.author_id
    ORDER BY b.ctime DESC
    LIMIT 1
  ), 0) AS birthday,
  COALESCE((
    SELECT array_agg(t.tag_name) FILTER (WHERE t.tag_name IS NOT NULL)
    FROM "post_tag" pt
    JOIN "tag" t ON t.tag_id = pt.tag_id
    WHERE pt.post_id = p.post_id
  ), '{}') AS tags,
  EXISTS(
    SELECT 1 FROM "like_dislike" ld
    WHERE ld.post_id = p.post_id AND ld.user_id = NULLIF($5, '')::uuid AND ld.type = 'like'
  ) AS is_like,
  EXISTS(
    SELECT 1 FROM "like_dislike" ld2
    WHERE ld2.post_id = p.post_id AND ld2.user_id = NULLIF($5, '')::uuid AND ld2.type = 'dislike'
  ) AS is_dislike,
  EXISTS(
    SELECT 1 FROM "collection" c2
    WHERE c2.post_id = p.post_id AND c2.user_id = NULLIF($5, '')::uuid
  ) AS is_collect
FROM "post" p
JOIN "post_tag" pt2 ON pt2.post_id = p.post_id
LEFT JOIN "user_addition" ua ON ua.user_id = p.author_id
WHERE p.title ILIKE $1 AND pt2.tag_id = $2 AND p.status = 'published'
ORDER BY p.ctime DESC
LIMIT $3 OFFSET $4
`

type SearchPostsByTitleAndTagCtimeParams struct {
	Title   string
	TagID   pgtype.UUID
	Limit   int32
	Offset  int32
	Column5 interface{}
}

type SearchPostsByTitleAndTagCtimeRow struct {
	PostID         string
	AuthorID       string
	AuthorName     string
	AuthorAvatar   string
	AuthorProvince string
	AuthorCity     string
	Title          string
	Content        string
	Status         string
	LikeCount      int32
	DislikeCount   int32
	CollectCount   int32
	CommentCount   int32
	Cover          string
	Ctime          int64
	Utime          int64
	Birthday       interface{}
	Tags           interface{}
	IsLike         bool
	IsDislike      bool
	IsCollect      bool
}

func (q *Queries) SearchPostsByTitleAndTagCtime(ctx context.Context, arg SearchPostsByTitleAndTagCtimeParams) ([]SearchPostsByTitleAndTagCtimeRow, error) {
	rows, err := q.db.Query(ctx, searchPostsByTitleAndTagCtime,
		arg.Title,
		arg.TagID,
		arg.Limit,
		arg.Offset,
		arg.Column5,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchPostsByTitleAndTagCtimeRow
	for rows.Next() {
		var i SearchPostsByTitleAndTagCtimeRow
		if err := rows.Scan(
			&i.PostID,
			&i.AuthorID,
			&i.AuthorName,
			&i.AuthorAvatar,
			&i.AuthorProvince,
			&i.AuthorCity,
			&i.Title,
			&i.Content,
			&i.Status,
			&i.LikeCount,
			&i.DislikeCount,
			&i.CollectCount,
			&i.CommentCount,
			&i.Cover,
			&i.Ctime,
			&i.Utime,
			&i.Birthday,
			&i.Tags,
			&i.IsLike,
			&i.IsDislike,
			&i.IsCollect,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchPostsByTitleAndTagHot = `-- name: SearchPostsByTitleAndTagHot :many
SELECT
  p.post_id::text AS post_id,
  p.author_id::text AS author_id,
  COALESCE(ua.username, '') AS author_name,
  COALESCE(ua.avatar, '') AS author_avatar,
  COALESCE(ua.province, '') AS author_province,
  COALESCE(ua.city, '') AS author_city,
  p.title, p.content, p.status,
  p.like_count, p.dislike_count, p.collect_count, p.comment_count,
  p.cover, p.ctime, p.utime,
  COALESCE((
    SELECT b.birthday
    FROM "baby" b
    WHERE b.user_id = p.author_id
    ORDER BY b.ctime DESC
    LIMIT 1
  ), 0) AS birthday,
  COALESCE((
    SELECT array_agg(t.tag_name) FILTER (WHERE t.tag_name IS NOT NULL)
    FROM "post_tag" pt
    JOIN "tag" t ON t.tag_id = pt.tag_id
    WHERE pt.post_id = p.post_id
  ), '{}') AS tags,
  EXISTS(
    SELECT 1 FROM "like_dislike" ld
    WHERE ld.post_id = p.post_id AND ld.user_id = NULLIF($5, '')::uuid AND ld.type = 'like'
  ) AS is_like,
  EXISTS(
    SELECT 1 FROM "like_dislike" ld2
    WHERE ld2.post_id = p.post_id AND ld2.user_id = NULLIF($5, '')::uuid AND ld2.type = 'dislike'
  ) AS is_dislike,
  EXISTS(
    SELECT 1 FROM "collection" c2
    WHERE c2.post_id = p.post_id AND c2.user_id = NULLIF($5, '')::uuid
  ) AS is_collect
FROM "post" p
JOIN "post_tag" pt2 ON pt2.post_id = p.post_id
LEFT JOIN "user_addition" ua ON ua.user_id = p.author_id
WHERE p.title ILIKE $1 AND pt2.tag_id = $2 AND p.status = 'published'
ORDER BY (p.like_count*3 + p.comment_count*5 + p.collect_count*4) DESC, p.ctime DESC
LIMIT $3 OFFSET $4
`

type SearchPostsByTitleAndTagHotParams struct {
	Title   string
	TagID   pgtype.UUID
	Limit   int32
	Offset  int32
	Column5 interface{}
}

type SearchPostsByTitleAndTagHotRow struct {
	PostID         string
	AuthorID       string
	AuthorName     string
	AuthorAvatar   string
	AuthorProvince string
	AuthorCity     string
	Title          string
	Content        string
	Status         string
	LikeCount      int32
	DislikeCount   int32
	CollectCount   int32
	CommentCount   int32
	Cover          string
	Ctime          int64
	Utime          int64
	Birthday       interface{}
	Tags           interface{}
	IsLike         bool
	IsDislike      bool
	IsCollect      bool
}

func (q *Queries) SearchPostsByTitleAndTagHot(ctx context.Context, arg SearchPostsByTitleAndTagHotParams) ([]SearchPostsByTitleAndTagHotRow, error) {
	rows, err := q.db.Query(ctx, searchPostsByTitleAndTagHot,
		arg.Title,
		arg.TagID,
		arg.Limit,
		arg.Offset,
		arg.Column5,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchPostsByTitleAndTagHotRow
	for rows.Next() {
		var i SearchPostsByTitleAndTagHotRow
		if err := rows.Scan(
			&i.PostID,
			&i.AuthorID,
			&i.AuthorName,
			&i.AuthorAvatar,
			&i.AuthorProvince,
			&i.AuthorCity,
			&i.Title,
			&i.Content,
			&i.Status,
			&i.LikeCount,
			&i.DislikeCount,
			&i.CollectCount,
			&i.CommentCount,
			&i.Cover,
			&i.Ctime,
			&i.Utime,
			&i.Birthday,
			&i.Tags,
			&i.IsLike,
			&i.IsDislike,
			&i.IsCollect,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchPostsByTitleHot = `-- name: SearchPostsByTitleHot :many
SELECT
  p.post_id::text AS post_id,
  p.author_id::text AS author_id,
  COALESCE(ua.username, '') AS author_name,
  COALESCE(ua.avatar, '') AS author_avatar,
  COALESCE(ua.province, '') AS author_province,
  COALESCE(ua.city, '') AS author_city,
  p.title, p.content, p.status,
  p.like_count, p.dislike_count, p.collect_count, p.comment_count,
  p.cover, p.ctime, p.utime,
  COALESCE((
    SELECT b.birthday
    FROM "baby" b
    WHERE b.user_id = p.author_id
    ORDER BY b.ctime DESC
    LIMIT 1
  ), 0) AS birthday,
  COALESCE((
    SELECT array_agg(t.tag_name) FILTER (WHERE t.tag_name IS NOT NULL)
    FROM "post_tag" pt
    JOIN "tag" t ON t.tag_id = pt.tag_id
    WHERE pt.post_id = p.post_id
  ), '{}') AS tags,
  EXISTS(
    SELECT 1 FROM "like_dislike" ld
    WHERE ld.post_id = p.post_id AND ld.user_id = NULLIF($4, '')::uuid AND ld.type = 'like'
  ) AS is_like,
  EXISTS(
    SELECT 1 FROM "like_dislike" ld2
    WHERE ld2.post_id = p.post_id AND ld2.user_id = NULLIF($4, '')::uuid AND ld2.type = 'dislike'
  ) AS is_dislike,
  EXISTS(
    SELECT 1 FROM "collection" c2
    WHERE c2.post_id = p.post_id AND c2.user_id = NULLIF($4, '')::uuid
  ) AS is_collect
FROM "post" p
LEFT JOIN "user_addition" ua ON ua.user_id = p.author_id
WHERE p.title ILIKE $1 AND p.status = 'published'
ORDER BY (p.like_count*3 + p.comment_count*5 + p.collect_count*4) DESC, p.ctime DESC
LIMIT $2 OFFSET $3
`

type SearchPostsByTitleHotParams struct {
	Title   string
	Limit   int32
	Offset  int32
	Column4 interface{}
}

type SearchPostsByTitleHotRow struct {
	PostID         string
	AuthorID       string
	AuthorName     string
	AuthorAvatar   string
	AuthorProvince string
	AuthorCity     string
	Title          string
	Content        string
	Status         string
	LikeCount      int32
	DislikeCount   int32
	CollectCount   int32
	CommentCount   int32
	Cover          string
	Ctime          int64
	Utime          int64
	Birthday       interface{}
	Tags           interface{}
	IsLike         bool
	IsDislike      bool
	IsCollect      bool
}

func (q *Queries) SearchPostsByTitleHot(ctx context.Context, arg SearchPostsByTitleHotParams) ([]SearchPostsByTitleHotRow, error) {
	rows, err := q.db.Query(ctx, searchPostsByTitleHot,
		arg.Title,
		arg.Limit,
		arg.Offset,
		arg.Column4,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchPostsByTitleHotRow
	for rows.Next() {
		var i SearchPostsByTitleHotRow
		if err := rows.Scan(
			&i.PostID,
			&i.AuthorID,
			&i.AuthorName,
			&i.AuthorAvatar,
			&i.AuthorProvince,
			&i.AuthorCity,
			&i.Title,
			&i.Content,
			&i.Status,
			&i.LikeCount,
			&i.DislikeCount,
			&i.CollectCount,
			&i.CommentCount,
			&i.Cover,
			&i.Ctime,
			&i.Utime,
			&i.Birthday,
			&i.Tags,
			&i.IsLike,
			&i.IsDislike,
			&i.IsCollect,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCommentContentByOwner = `-- name: UpdateCommentContentByOwner :execrows
UPDATE "comment"
SET content = $2, utime = $3
WHERE comment_id = $1 AND user_id = $4 AND status = 'visible'
`

type UpdateCommentContentByOwnerParams struct {
	CommentID pgtype.UUID
	Content   pgtype.Text
	Utime     int64
	UserID    pgtype.UUID
}

func (q *Queries) UpdateCommentContentByOwner(ctx context.Context, arg UpdateCommentContentByOwnerParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateCommentContentByOwner,
		arg.CommentID,
		arg.Content,
		arg.Utime,
		arg.UserID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateDraftByOwner = `-- name: UpdateDraftByOwner :execrows
UPDATE "post"
SET title = $3, content = $4, utime = $5
WHERE post_id = $1 AND author_id = $2 AND status = 'draft'
`

type UpdateDraftByOwnerParams struct {
	PostID   pgtype.UUID
	AuthorID pgtype.UUID
	Title    string
	Content  string
	Utime    int64
}

func (q *Queries) UpdateDraftByOwner(ctx context.Context, arg UpdateDraftByOwnerParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateDraftByOwner,
		arg.PostID,
		arg.AuthorID,
		arg.Title,
		arg.Content,
		arg.Utime,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
