package router

import (
	"nurture/internal/dto"
	"nurture/internal/handler"
	"nurture/internal/middleware"
	"nurture/internal/pkg/jwtx"

	"github.com/gin-gonic/gin"
)

func registerPostRoutes(rg *gin.RouterGroup) {
	postHandler := handler.NewPostHandler()

	rg.GET("",
		middleware.BindQueryMiddleware[dto.PostHomeListReq],
		postHandler.Home,
	)
	rg.GET("/tags",
		middleware.BindQueryMiddleware[dto.TagListReq],
		postHandler.ListTags,
	)
	rg.GET("/tag/:tag_id",
		middleware.BindUriMiddleware[dto.PostTagListReq],
		middleware.BindQueryMiddleware[dto.PostTagListReq],
		postHandler.ListByTag,
	)
	rg.GET("/search",
		middleware.BindQueryMiddleware[dto.PostSearchListReq],
		postHandler.Search,
	)
	rg.GET("/:post_id",
		middleware.BindUriMiddleware[dto.PostDetailReq],
		postHandler.GetDetail,
	)
	rg.POST("/newPost",
		middleware.Authentication(jwtx.COMMON_USER),
		middleware.BindJsonMiddleware[dto.CreatePostReq],
		postHandler.NewPost,
	)
	rg.GET("/mine",
		middleware.Authentication(jwtx.COMMON_USER),
		middleware.BindQueryMiddleware[dto.PostMyListReq],
		postHandler.ListMyPosts,
	)
	rg.GET("/following",
		middleware.Authentication(jwtx.COMMON_USER),
		middleware.BindQueryMiddleware[dto.PostMyListReq],
		postHandler.Following,
	)
	rg.GET("/mine/drafts",
		middleware.Authentication(jwtx.COMMON_USER),
		middleware.BindQueryMiddleware[dto.PostMyListReq],
		postHandler.ListMyDrafts,
	)
	rg.GET("/mine/milestone",
		middleware.Authentication(jwtx.COMMON_USER),
		middleware.BindQueryMiddleware[dto.PostMyListReq],
		postHandler.ListMyMilestones,
	)
	rg.POST("/:post_id/publish",
		middleware.Authentication(jwtx.COMMON_USER),
		middleware.BindUriMiddleware[dto.PublishPostReq],
		postHandler.Publish,
	)
	rg.PUT("/:post_id",
		middleware.Authentication(jwtx.COMMON_USER),
		middleware.BindUriMiddleware[dto.PostDetailReq],
		middleware.BindJsonMiddleware[dto.UpdateDraftReq],
		postHandler.UpdateDraft,
	)
	rg.DELETE("/:post_id",
		middleware.Authentication(jwtx.COMMON_USER),
		middleware.BindUriMiddleware[dto.PostDetailReq],
		postHandler.DeleteDraft,
	)
	rg.DELETE("/:post_id/delete",
		middleware.Authentication(jwtx.COMMON_USER),
		middleware.BindUriMiddleware[dto.PostDetailReq],
		postHandler.DeletePost,
	)
	rg.POST("/:post_id/like",
		middleware.Authentication(jwtx.COMMON_USER),
		middleware.BindUriMiddleware[dto.PostDetailReq],
		postHandler.LikePost,
	)
	rg.DELETE("/:post_id/like",
		middleware.Authentication(jwtx.COMMON_USER),
		middleware.BindUriMiddleware[dto.PostDetailReq],
		postHandler.UnlikePost,
	)
	rg.POST("/:post_id/collect",
		middleware.Authentication(jwtx.COMMON_USER),
		middleware.BindUriMiddleware[dto.PostDetailReq],
		postHandler.CollectPost,
	)
	rg.DELETE("/:post_id/collect",
		middleware.Authentication(jwtx.COMMON_USER),
		middleware.BindUriMiddleware[dto.PostDetailReq],
		postHandler.UncollectPost,
	)
	rg.GET("/mine/collections",
		middleware.Authentication(jwtx.COMMON_USER),
		middleware.BindQueryMiddleware[dto.PostMyListReq],
		postHandler.ListMyCollections,
	)
	rg.POST("/:post_id/comments",
		middleware.Authentication(jwtx.COMMON_USER),
		middleware.BindUriMiddleware[dto.PublishPostReq],
		middleware.BindJsonMiddleware[dto.CreateCommentReq],
		postHandler.CreateComment,
	)
	rg.GET("/:post_id/comments",
		middleware.BindUriMiddleware[dto.PostDetailReq],
		middleware.BindQueryMiddleware[dto.CommentListReq],
		postHandler.ListComments,
	)
	rg.GET("/:post_id/comments/:comment_id/replies",
		middleware.BindUriMiddleware[dto.CommentRepliesReq],
		middleware.BindQueryMiddleware[dto.CommentListReq],
		postHandler.ListReplies,
	)
	rg.DELETE("/comments/:comment_id",
		middleware.Authentication(jwtx.COMMON_USER),
		middleware.BindUriMiddleware[dto.CommentDeleteReq],
		postHandler.DeleteComment,
	)
	rg.PUT("/comments/:comment_id",
		middleware.Authentication(jwtx.COMMON_USER),
		middleware.BindUriMiddleware[dto.CommentUpdateReq],
		middleware.BindJsonMiddleware[dto.UpdateCommentReq],
		postHandler.UpdateComment,
	)
	rg.POST("/comments/:comment_id/like",
		middleware.Authentication(jwtx.COMMON_USER),
		middleware.BindUriMiddleware[dto.CommentLikeReq],
		postHandler.LikeComment,
	)
	rg.DELETE("/comments/:comment_id/like",
		middleware.Authentication(jwtx.COMMON_USER),
		middleware.BindUriMiddleware[dto.CommentLikeReq],
		postHandler.UnlikeComment,
	)
}
