// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dao

import (
	"github.com/jackc/pgx/v5/pgtype"
)

// 用户扩展信息（冗余用户名、头像、地区）
type UserAddition struct {
	// 主键ID
	ID int64
	// 用户ID(与基础信息一对一)
	UserID pgtype.UUID
	// 用户名（冗余）
	Username string
	// 性别（冗余）
	Gender string
	// 手机号
	Phone string
	// 职业
	Occupation string
	// 生日(毫秒时间戳,未知为0)
	Birthday int64
	// 头像URL
	Avatar string
	// 省
	Province string
	// 市
	City string
	// 创建时间
	Ctime int64
	// 更新时间
	Utime int64
}

// 用户基础信息（注册必填）
type UserBase struct {
	// 主键ID
	ID int64
	// 用户ID
	UserID pgtype.UUID
	// 账号
	Account string
	// 密码
	Password string
	// 邮箱
	Email pgtype.Text
	// 用户名
	Username string
	// 性别:male/female
	Gender string
	// 角色
	Role int16
	// 创建时间
	Ctime int64
	// 更新时间
	Utime int64
}

// 用户事件 outbox 表
type UserEventOutbox struct {
	// 主键ID
	ID int64
	// 事件ID(幂等)
	EventID string
	// RabbitMQ 路由键
	RoutingKey string
	// 事件载荷(JSON字符串)
	Payload string
	// 事件状态(pending/publishing/published/failed)
	Status string
	// 发布尝试次数
	Attempts int32
	// 下一次重试时间戳(毫秒)
	NextRetryAt int64
	// 发布时间戳(毫秒)
	PublishedAt int64
	// 创建时间戳(毫秒)
	Ctime int64
	// 更新时间戳(毫秒)
	Utime int64
}

// 用户关注关系表
type UserFollow struct {
	// 主键ID
	ID int64
	// 关注者用户UUID
	Follower pgtype.UUID
	// 被关注者用户UUID
	Followee pgtype.UUID
	// 关注时间戳
	Ctime int64
	// 更新时间戳
	Utime int64
}

// 用户另一半关系表（父/母）
type UserPartner struct {
	// 主键ID
	ID int64
	// 父亲用户UUID
	Father pgtype.UUID
	// 母亲用户UUID
	Mother pgtype.UUID
	// 创建时间戳
	Ctime int64
	// 更新时间戳
	Utime int64
}
