// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user.sql

package dao

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const adminListUsers = `-- name: AdminListUsers :many
SELECT 
  ub.user_id::text AS user_id,
  ub.username,
  COALESCE(ua.avatar, '') AS avatar
FROM "user_base" ub
LEFT JOIN "user_addition" ua ON ua.user_id = ub.user_id
WHERE ($1 = '' OR ub.username ILIKE '%' || $1 || '%')
ORDER BY ub.ctime DESC
LIMIT $2 OFFSET $3
`

type AdminListUsersParams struct {
	Column1 interface{}
	Limit   int32
	Offset  int32
}

type AdminListUsersRow struct {
	UserID   string
	Username string
	Avatar   string
}

// admin
func (q *Queries) AdminListUsers(ctx context.Context, arg AdminListUsersParams) ([]AdminListUsersRow, error) {
	rows, err := q.db.Query(ctx, adminListUsers, arg.Column1, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AdminListUsersRow
	for rows.Next() {
		var i AdminListUsersRow
		if err := rows.Scan(&i.UserID, &i.Username, &i.Avatar); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminUpdateUserRole = `-- name: AdminUpdateUserRole :execrows
UPDATE "user_base"
SET role = $2, utime = $3
WHERE user_id = $1
`

type AdminUpdateUserRoleParams struct {
	UserID pgtype.UUID
	Role   int16
	Utime  int64
}

// admin
func (q *Queries) AdminUpdateUserRole(ctx context.Context, arg AdminUpdateUserRoleParams) (int64, error) {
	result, err := q.db.Exec(ctx, adminUpdateUserRole, arg.UserID, arg.Role, arg.Utime)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const bindEmailByUserID = `-- name: BindEmailByUserID :execrows
UPDATE "user_base"
SET email = $2, utime = $3
WHERE user_id = $1
`

type BindEmailByUserIDParams struct {
	UserID pgtype.UUID
	Email  pgtype.Text
	Utime  int64
}

func (q *Queries) BindEmailByUserID(ctx context.Context, arg BindEmailByUserIDParams) (int64, error) {
	result, err := q.db.Exec(ctx, bindEmailByUserID, arg.UserID, arg.Email, arg.Utime)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createFollow = `-- name: CreateFollow :exec
INSERT INTO "user_follow"(follower, followee, ctime, utime)
VALUES ($1, $2, $3, $3)
ON CONFLICT (follower, followee) DO NOTHING
`

type CreateFollowParams struct {
	Follower pgtype.UUID
	Followee pgtype.UUID
	Ctime    int64
}

func (q *Queries) CreateFollow(ctx context.Context, arg CreateFollowParams) error {
	_, err := q.db.Exec(ctx, createFollow, arg.Follower, arg.Followee, arg.Ctime)
	return err
}

const createPartner = `-- name: CreatePartner :exec
INSERT INTO "user_partner"(father, mother, ctime, utime)
VALUES ($1, $2, $3, $3)
ON CONFLICT (father, mother) DO NOTHING
`

type CreatePartnerParams struct {
	Father pgtype.UUID
	Mother pgtype.UUID
	Ctime  int64
}

func (q *Queries) CreatePartner(ctx context.Context, arg CreatePartnerParams) error {
	_, err := q.db.Exec(ctx, createPartner, arg.Father, arg.Mother, arg.Ctime)
	return err
}

const createUser = `-- name: CreateUser :exec
WITH ins AS (
  INSERT INTO "user_base" (
    user_id, ctime, utime, account, password, email, username, gender, role
  ) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, 1
  )
  RETURNING user_id, username, gender, ctime, utime
)
INSERT INTO "user_addition" (
  user_id, username, gender, phone, occupation, birthday, avatar, province, city, ctime, utime
) SELECT
  user_id, username, gender, '', '', 0, '', '', '', ctime, utime
FROM ins
`

type CreateUserParams struct {
	UserID   pgtype.UUID
	Ctime    int64
	Utime    int64
	Account  string
	Password string
	Email    pgtype.Text
	Username string
	Gender   string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.Exec(ctx, createUser,
		arg.UserID,
		arg.Ctime,
		arg.Utime,
		arg.Account,
		arg.Password,
		arg.Email,
		arg.Username,
		arg.Gender,
	)
	return err
}

const deleteFollow = `-- name: DeleteFollow :execrows
DELETE FROM "user_follow"
WHERE follower = $1 AND followee = $2
`

type DeleteFollowParams struct {
	Follower pgtype.UUID
	Followee pgtype.UUID
}

func (q *Queries) DeleteFollow(ctx context.Context, arg DeleteFollowParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteFollow, arg.Follower, arg.Followee)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getMyProfile = `-- name: GetMyProfile :one
SELECT 
  ub.user_id::text AS user_id,
  ub.account,
  COALESCE(ub.email, '') AS email,
  ub.username,
  ub.gender,
  ua.avatar,
  ua.phone,
  ua.occupation,
  ua.birthday,
  ua.province,
  ua.city,
  ub.ctime,
  ub.utime
FROM "user_base" ub
JOIN "user_addition" ua ON ua.user_id = ub.user_id
WHERE ub.user_id = $1
LIMIT 1
`

type GetMyProfileRow struct {
	UserID     string
	Account    string
	Email      string
	Username   string
	Gender     string
	Avatar     string
	Phone      string
	Occupation string
	Birthday   int64
	Province   string
	City       string
	Ctime      int64
	Utime      int64
}

func (q *Queries) GetMyProfile(ctx context.Context, userID pgtype.UUID) (GetMyProfileRow, error) {
	row := q.db.QueryRow(ctx, getMyProfile, userID)
	var i GetMyProfileRow
	err := row.Scan(
		&i.UserID,
		&i.Account,
		&i.Email,
		&i.Username,
		&i.Gender,
		&i.Avatar,
		&i.Phone,
		&i.Occupation,
		&i.Birthday,
		&i.Province,
		&i.City,
		&i.Ctime,
		&i.Utime,
	)
	return i, err
}

const getPartnerByUserID = `-- name: GetPartnerByUserID :one
SELECT father::text AS father, mother::text AS mother
FROM "user_partner"
WHERE father = $1 OR mother = $1
LIMIT 1
`

type GetPartnerByUserIDRow struct {
	Father string
	Mother string
}

func (q *Queries) GetPartnerByUserID(ctx context.Context, father pgtype.UUID) (GetPartnerByUserIDRow, error) {
	row := q.db.QueryRow(ctx, getPartnerByUserID, father)
	var i GetPartnerByUserIDRow
	err := row.Scan(&i.Father, &i.Mother)
	return i, err
}

const getUserByAccount = `-- name: GetUserByAccount :one
SELECT id, user_id, account, password, email, username, gender, role, ctime, utime FROM "user_base"
WHERE account = $1
LIMIT 1
`

func (q *Queries) GetUserByAccount(ctx context.Context, account string) (UserBase, error) {
	row := q.db.QueryRow(ctx, getUserByAccount, account)
	var i UserBase
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Account,
		&i.Password,
		&i.Email,
		&i.Username,
		&i.Gender,
		&i.Role,
		&i.Ctime,
		&i.Utime,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, user_id, account, password, email, username, gender, role, ctime, utime FROM "user_base"
WHERE email = $1::varchar
LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, dollar_1 string) (UserBase, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, dollar_1)
	var i UserBase
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Account,
		&i.Password,
		&i.Email,
		&i.Username,
		&i.Gender,
		&i.Role,
		&i.Ctime,
		&i.Utime,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, user_id, account, password, email, username, gender, role, ctime, utime FROM "user_base"
WHERE user_id = $1
LIMIT 1
`

func (q *Queries) GetUserByID(ctx context.Context, userID pgtype.UUID) (UserBase, error) {
	row := q.db.QueryRow(ctx, getUserByID, userID)
	var i UserBase
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Account,
		&i.Password,
		&i.Email,
		&i.Username,
		&i.Gender,
		&i.Role,
		&i.Ctime,
		&i.Utime,
	)
	return i, err
}

const isFollowing = `-- name: IsFollowing :one
SELECT EXISTS(
  SELECT 1 FROM "user_follow"
  WHERE follower = $1 AND followee = $2
) AS is_following
`

type IsFollowingParams struct {
	Follower pgtype.UUID
	Followee pgtype.UUID
}

func (q *Queries) IsFollowing(ctx context.Context, arg IsFollowingParams) (bool, error) {
	row := q.db.QueryRow(ctx, isFollowing, arg.Follower, arg.Followee)
	var is_following bool
	err := row.Scan(&is_following)
	return is_following, err
}

const isPhoneUsed = `-- name: IsPhoneUsed :one
SELECT EXISTS(
  SELECT 1 FROM "user_addition"
  WHERE phone = $1 AND phone <> '' AND user_id <> $2
) AS is_phone_used
`

type IsPhoneUsedParams struct {
	Phone  string
	UserID pgtype.UUID
}

func (q *Queries) IsPhoneUsed(ctx context.Context, arg IsPhoneUsedParams) (bool, error) {
	row := q.db.QueryRow(ctx, isPhoneUsed, arg.Phone, arg.UserID)
	var is_phone_used bool
	err := row.Scan(&is_phone_used)
	return is_phone_used, err
}

const listFollowersByUserID = `-- name: ListFollowersByUserID :many
SELECT 
  ub.user_id::text AS user_id,
  ub.username,
  ua.avatar,
  uf.ctime AS follow_time
FROM "user_follow" uf
JOIN "user_base" ub ON ub.user_id = uf.follower
JOIN "user_addition" ua ON ua.user_id = uf.follower
WHERE uf.followee = $1
ORDER BY uf.ctime DESC
LIMIT $2 OFFSET $3
`

type ListFollowersByUserIDParams struct {
	Followee pgtype.UUID
	Limit    int32
	Offset   int32
}

type ListFollowersByUserIDRow struct {
	UserID     string
	Username   string
	Avatar     string
	FollowTime int64
}

func (q *Queries) ListFollowersByUserID(ctx context.Context, arg ListFollowersByUserIDParams) ([]ListFollowersByUserIDRow, error) {
	rows, err := q.db.Query(ctx, listFollowersByUserID, arg.Followee, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFollowersByUserIDRow
	for rows.Next() {
		var i ListFollowersByUserIDRow
		if err := rows.Scan(
			&i.UserID,
			&i.Username,
			&i.Avatar,
			&i.FollowTime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFollowingByUserID = `-- name: ListFollowingByUserID :many
SELECT 
  ub.user_id::text AS user_id,
  ub.username,
  ua.avatar,
  uf.ctime AS follow_time
FROM "user_follow" uf
JOIN "user_base" ub ON ub.user_id = uf.followee
JOIN "user_addition" ua ON ua.user_id = uf.followee
WHERE uf.follower = $1
ORDER BY uf.ctime DESC
LIMIT $2 OFFSET $3
`

type ListFollowingByUserIDParams struct {
	Follower pgtype.UUID
	Limit    int32
	Offset   int32
}

type ListFollowingByUserIDRow struct {
	UserID     string
	Username   string
	Avatar     string
	FollowTime int64
}

func (q *Queries) ListFollowingByUserID(ctx context.Context, arg ListFollowingByUserIDParams) ([]ListFollowingByUserIDRow, error) {
	rows, err := q.db.Query(ctx, listFollowingByUserID, arg.Follower, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFollowingByUserIDRow
	for rows.Next() {
		var i ListFollowingByUserIDRow
		if err := rows.Scan(
			&i.UserID,
			&i.Username,
			&i.Avatar,
			&i.FollowTime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBaseGenderByUserID = `-- name: UpdateBaseGenderByUserID :execrows
UPDATE "user_base"
SET gender = $2, utime = $3
WHERE user_id = $1
`

type UpdateBaseGenderByUserIDParams struct {
	UserID pgtype.UUID
	Gender string
	Utime  int64
}

func (q *Queries) UpdateBaseGenderByUserID(ctx context.Context, arg UpdateBaseGenderByUserIDParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateBaseGenderByUserID, arg.UserID, arg.Gender, arg.Utime)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateGenderByUserID = `-- name: UpdateGenderByUserID :execrows
UPDATE "user_addition"
SET gender = $2, utime = $3
WHERE user_id = $1
`

type UpdateGenderByUserIDParams struct {
	UserID pgtype.UUID
	Gender string
	Utime  int64
}

func (q *Queries) UpdateGenderByUserID(ctx context.Context, arg UpdateGenderByUserIDParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateGenderByUserID, arg.UserID, arg.Gender, arg.Utime)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updatePasswordByEmail = `-- name: UpdatePasswordByEmail :execrows
UPDATE "user_base"
SET password = $2
WHERE email = $1
`

type UpdatePasswordByEmailParams struct {
	Email    pgtype.Text
	Password string
}

func (q *Queries) UpdatePasswordByEmail(ctx context.Context, arg UpdatePasswordByEmailParams) (int64, error) {
	result, err := q.db.Exec(ctx, updatePasswordByEmail, arg.Email, arg.Password)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updatePasswordByUserID = `-- name: UpdatePasswordByUserID :execrows
UPDATE "user_base"
SET password = $2, utime = $3
WHERE user_id = $1
`

type UpdatePasswordByUserIDParams struct {
	UserID   pgtype.UUID
	Password string
	Utime    int64
}

func (q *Queries) UpdatePasswordByUserID(ctx context.Context, arg UpdatePasswordByUserIDParams) (int64, error) {
	result, err := q.db.Exec(ctx, updatePasswordByUserID, arg.UserID, arg.Password, arg.Utime)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateUserAdditionByUserID = `-- name: UpdateUserAdditionByUserID :execrows
UPDATE "user_addition"
SET
  occupation = COALESCE(NULLIF($2, ''), occupation),
  phone      = COALESCE(NULLIF($3, ''), phone),
  province   = COALESCE(NULLIF($4, ''), province),
  city       = COALESCE(NULLIF($5, ''), city),
  avatar     = COALESCE(NULLIF($6, ''), avatar),
  birthday   = COALESCE(NULLIF($7::BIGINT, -1), birthday),
  utime      = $8
WHERE user_id = $1
`

type UpdateUserAdditionByUserIDParams struct {
	UserID  pgtype.UUID
	Column2 interface{}
	Column3 interface{}
	Column4 interface{}
	Column5 interface{}
	Column6 interface{}
	Column7 int64
	Utime   int64
}

func (q *Queries) UpdateUserAdditionByUserID(ctx context.Context, arg UpdateUserAdditionByUserIDParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateUserAdditionByUserID,
		arg.UserID,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Column5,
		arg.Column6,
		arg.Column7,
		arg.Utime,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
